### ISSUE TITLE
Confirm before closing popup if the chart/character/dialogue is unsaved

### ISSUE THREAD

**Issue by NAEL2XD** [JordanSantiagoYT/FNF-JS-Engine#418]
### What feature do you want to get added on the **base** engine?

title

would REALLY be very useful if you clicked the x button on accident and then losing all of the unsaved progress, and that happend too many times and made me do ALL OF IT ALL OVER AGAIN if i didn't have a saved chart

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by NAEL2XD** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/108278470/ad1fbb02-af35-4e0b-af34-7dbdd5638452

example

**Comment by moxie-coder** [comment]
this *does* seem like a good idea, I might have an way to implement it

**Comment by Stefan2008Git** [comment]
> this _does_ seem like a good idea, I might have an way to implement it

It's time to switch on HaxeUI tho

**Comment by NAEL2XD** [comment]
Is it gonna be closed for inactivity??

**Comment by moxie-coder** [comment]
> Is it gonna be closed for inactivity?? I hope not because dunno if you're still working on it.

I'll get to this at some point

**Comment by moxie-coder** [comment]
coming back to this, I saw 0.7/1.0 added this feature iirc, so I might be able to use that

**Comment by PatoFlamejanteTV** [comment]
cool idea!
