### ISSUE TITLE
strange glitch

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-JS-Engine#444]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

https://github.com/user-attachments/assets/bbe667af-9958-479c-b99f-cf31bd0852c1

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
I don’t get it, what’s the problem here?

**Comment by dimafut** [comment]
the screen freezes completely, but the game and sound still work

**Comment by moxie-coder** [comment]
> the screen freezes completely, but the game and sound still work

then wait for it to work

**Comment by dimafut** [comment]
over 20 minutes of waiting, also I discovered, that this bug happens when I turning off function called "enable note colors"

**Comment by FuseIsHere813** [comment]
maybe turn it on then?

@moxie-coder this issue is stale btw

**Comment by moxie-coder** [comment]
> maybe turn it on then?
> 
> @moxie-coder this issue is stale btw

I know, I forgot to fix this in the meantime

**Comment by moxie-coder** [comment]
I’ve been unable to replicate myself so I’m gonna assume you have a weak pc
