### ISSUE TITLE
the song won't pause if you lag the game and pause

### ISSUE THREAD

**Issue by NAEL2XD** [JordanSantiagoYT/FNF-JS-Engine#453]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

https://github.com/user-attachments/assets/1ed2d6c9-c6e9-4424-ac8f-a859d3a95e9b

only happens if the game is lagging, and no there is nothing running in the background still playing the music, this is REAL TIME

### Command Prompt/Terminal/Crash logs (if existing)

```bash
noh!!!
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
1. enter a song with a shit ton of notes
2. lag the game
3. pause
4. the music won't pause?

btw if you resume it'll go to whetever position the song is
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only DiscordClient.hx (only edited ID)

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by NAEL2XD** [comment]
i used commit 7bc8c5b btw

**Comment by NAEL2XD** [comment]
@JordanSantiagoYT

**Comment by mcagabe19** [comment]
guh this is exists on base game aswell wdym

**Comment by moxie-coder** [comment]
yeah this happens on base psych
