### ISSUE TITLE
Character editor silhouette

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-JS-Engine#454]
### What feature do you want to get added on the **base** engine?

Pretty self explainitory. I find it hard to keep characters in the same position without some frame of refernce so a silhouette of dad or something in the character editor would be nice to have consistent character placement

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by moxie-coder** [comment]
there already is a ghost character feature

**Comment by SMWpalkia** [comment]
if you're talking about the pose ghosts that's not what im referring to. im talking about something like this

https://github.com/user-attachments/assets/4d6cfd00-ae41-440d-a4ec-a2b23a038c3c

**Comment by moxie-coder** [comment]
you're basically asking for an feature that already exists dude 🤦🏻
