### ISSUE TITLE
unknown fps

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-JS-Engine#455]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

the error came out of nowhere

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Error: Could not process argument Warning: Ignoring unknown fps=""
Invalid character: :
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
NO
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
what were you trying to do?

**Comment by bimbifan** [comment]
> what were you trying to do?

nothing. this is clean code.

**Comment by JordanSantiagoYT** [comment]
well.. at least send a video/ss of the error

**Comment by JordanSantiagoYT** [comment]
ok, so i was getting the workflows back up and running and noticed that the error mentioned in this issue appeared.
![image](https://github.com/user-attachments/assets/4a06e482-64f3-4e0c-9337-128b4a626a95)

**Comment by max4th** [comment]
got the same warning when I used lime test windows
here's a screenshot:
![error](https://github.com/user-attachments/assets/5a462551-2ec5-4cc9-82a8-d2ca209c0d92)

**Comment by JordanSantiagoYT** [comment]
well, it didn't pop up your directory, so maybe wait, that's what happened when the workflow got the warning

**Comment by max4th** [comment]
read this:
https://github.com/orgs/community/discussions/133998#discussioncomment-10183721

**Comment by moxie-coder** [comment]
![image](https://github.com/user-attachments/assets/e36b1114-8d92-45e6-9a00-814af5301947)

ok I found what triggers it, but the fps value is there weirdly 🤔

**Comment by moxie-coder** [comment]
> read this: https://github.com/orgs/community/discussions/133998#discussion-6992237

you should make that an issue [here](https://github.com/openfl/lime/tree/95baa58effaff3f6158d642873dd329a8f6e048a), not there

**Comment by moxie-coder** [comment]
I'mma assume this is fixed now since I also noticed the actions run before that commit didn't have that warning
