### ISSUE TITLE
I Don know how to run the Linux JSEngine can any Linux users help me (PS how to get strident crisis ui)

### ISSUE THREAD

**Issue by Ghost2000gmd** [JordanSantiagoYT/FNF-JS-Engine#461]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

v

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JordanSantiagoYT** [comment]
1, i don't know either.

2. this engine doesn't have the strident crisis ui 😭😭

**Comment by moxie-coder** [comment]
I have Linux

1 what is your problem? like have you tried double clicking the game executable?
2 I can go add it in since I do have the repo

**Comment by mcagabe19** [comment]
1. get linux build
2. extract
3. open terminal cd into js engine folder
4. chmod +x JSEngine
5. to launch ./JSEngine

**Comment by mcagabe19** [comment]
if u have any issues like `GLIBC`, u need update ur OS

**Comment by mcagabe19** [comment]
for mods it's same as windows afaik

**Comment by Stefan2008Git** [comment]
> 1. get linux build
> 
>     2. extract
> 
>     3. open terminal cd into js engine folder
> 
>     4. chmod +x ./JSEngine
> 
>     5. to launch type ./JSEngine

![michael-scott-happy-cry](https://github.com/user-attachments/assets/5aa94423-8176-4305-ac9a-f53f93b792b9)
