### ISSUE TITLE
error during rendering mode

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-JS-Engine#462]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

![Friday Night Funkin'_ JS Engine - the-eyes-of-god (Freeplay) 27 07 2024 22_16_28](https://github.com/user-attachments/assets/ca23601c-dc82-4381-a98e-a3243075f8b7)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
flixel/graphics/tile/FlxDrawQuadsItem.hx (Line 121)
flixel/FlxCamera.hx (Line 772)
flixel/FlxGame.hx (Line 873)
flixel/FlxGame.hx (Line 565)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
this.. doesn't specifically help tell me whether or not rendering mode causes it

**Comment by JordanSantiagoYT** [comment]
however i will look into it soon.

**Comment by dimafut** [comment]
ok

**Comment by dimafut** [comment]
at first 2 attempts this song just crashed without error, but on 3rd time finally it showed an error

**Comment by dimafut** [comment]
but the chart have 5m notes, so that's can be the problem

**Comment by dimafut** [comment]
Sorry, but is there any news about this strange bug?

**Comment by JordanSantiagoYT** [comment]
i've been rendering a lot of stuff and this error has not occurred to me
.

**Comment by dimafut** [comment]
this happens on VERY BIG charts, like 5M+ notes, but today 1 situation happened, I chartes an song with 1.6M notes, and it takes 4 HOURS of rendering

**Comment by moxie-coder** [comment]
this issue is old now so imma close it, but idk how exactly to fix that really
