### ISSUE TITLE
Am I doing something wrong in the character editor?

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-JS-Engine#471]
### What is your question?

Whenever I try to create a new playable character in the editor, [a bunch of weird things](https://drive.google.com/drive/folders/1N5ujIIPBU606CZC3iW-3PWqX6kBWJTo1?usp=drive_link) happen that I don't know how to fix and seems very inconsistent between character

**Comment by moxie-coder** [comment]
I don’t get I’ll most of this just seems to work intentionally, as for that character not saving, are you using the mod folders and not the base game folders? because you have to reload the game otherwise I think

**Comment by SMWpalkia** [comment]
im using the mod folders which ive never needed to reload the game to work, if by reload the game you mean closing and reopening.

whenever i close and reopen the chart editor, the values for character and camera positions swap between negative and postive
reloading the character changes their placement occassionally
at 1:15 in the second video the placement of the lefts and rights change between the editor and in the game and only shows up in the character editor when i close and reopen it
the no antialiasing and flip x buttons get checked and unchecked whenever i reload the character or open the editor again and i don't even press them
i have to turn on and off flip x just for some characters to display correctly

**Comment by SMWpalkia** [comment]
https://github.com/user-attachments/assets/4f1de665-17b8-479e-bd77-9a8d13c5173b

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/20a52cd4-7a70-47cf-8d69-49f30f3df522)
hello??
