### ISSUE TITLE
Rendering mode(not 1.20 mode) not working

### ISSUE THREAD

**Issue by mihaillov** [JordanSantiagoYT/FNF-JS-Engine#475]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

When i use default not classic rendering mode,there is no results of render after song,the command prompt is stay until close.The video cant open on capcut.On vegas it opens,but it's no rendered song but this turns into black screen

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JordanSantiagoYT** [comment]
do you have `ffmpeg.exe` placed in the SAME folder that `JSEngine.exe` is in?

**Comment by mihaillov** [comment]
> do you have `ffmpeg.exe` placed in the SAME folder that `JSEngine.exe` is in?

Yes

**Comment by mihaillov** [comment]
only classic rendering mode working!I'm on JS Engine 1.30.0

**Comment by JordanSantiagoYT** [comment]
are you actually letting the song finish?

**Comment by mihaillov** [comment]
nope,now test the render

**Comment by mihaillov** [comment]
i testing and i send the video

**Comment by JordanSantiagoYT** [comment]
ok, so to clarify.. you aren't letting the song finish.





there's your issue

**Comment by mihaillov** [comment]
There is a script that skips the coutdown

**Comment by mihaillov** [comment]
Like hortas edition

**Comment by JordanSantiagoYT** [comment]
okay

**Comment by mihaillov** [comment]
bruh,i need to wait?Song is already ended and no result screen ._.

**Comment by JordanSantiagoYT** [comment]
can't you show me a recording of that happening

**Comment by mihaillov** [comment]
ye!

**Comment by mihaillov** [comment]
video is uploading on google drive,link will be soon

**Comment by mihaillov** [comment]
https://drive.google.com/file/d/1DzXb5g1Uytqmk--S2No-pe54FBhc3xdn/view?usp=sharing

**Comment by JordanSantiagoYT** [comment]
OH

you're not supposed to render a song while in story mode

**Comment by mihaillov** [comment]
It worked but vegas turn this video into Black screen:the movie

**Comment by mihaillov** [comment]
Trying on capcut now

**Comment by mihaillov** [comment]
Yeeeeeeeeeeeee it works on capcut.Thank you very much Jordan!It's my fault,bruh
