### ISSUE TITLE
Compiling bug

### ISSUE THREAD

**Issue by EthanMG228** [JordanSantiagoYT/FNF-JS-Engine#478]
### What is your question?

lime isnt a program. i launched windows.bat and it said finished. i launched lime test windows but it says lime isnt a program. HELP!!

**Comment by JordanSantiagoYT** [comment]
and just to be clear, did you setup haxelib BEFORE running the setup bat file

**Comment by mcagabe19** [comment]
basically `haxelib run lime setup -alias -y`
