### ISSUE TITLE
Having a Problem with the "Special Audio" Feature

### ISSUE THREAD

**Issue by cwill2010** [JordanSantiagoYT/FNF-JS-Engine#479]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

So, I tried using the some method as adding erect song to the game, but it doesn't work if I enter the audio name, regardless if I click "Reload Audio".

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, loading custom songs, events, and characters into base engine.

**Comment by JordanSantiagoYT** [comment]
when loading a song with the special audio name, it will append the special name to the end of the audio file, so if you put "erect" it'll look for "Inst-erect" and "Voices-erect".

**Comment by cwill2010** [comment]
Ok, thank you very much!!

**Comment by moxie-coder** [comment]
np
