### ISSUE TITLE
Softlock on results screen

### ISSUE THREAD

**Issue by TeraByte-Official** [JordanSantiagoYT/FNF-JS-Engine#481]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

If you press 7 at the same time a song ends, the game gets stuck on a blank screen and you have to close and reopen the game.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Press 7 on the same frame a song ends. More consistent if your framerate is really low.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
how are you so sure that this can occur? i've tried and have been unable to replicate the issue, even on 3 FPS.

**Comment by JordanSantiagoYT** [comment]
Also tried 1 FPS to make it even easier, and it still didn't occur LOL

**Comment by TeraByte-Official** [comment]
Did some more testing, and I noticed this occurs every time the song ends. I think it might be a local thing idk?

**Comment by JordanSantiagoYT** [comment]
oh

might just be a local thing then since it doesn't occur to me

**Comment by TeraByte-Official** [comment]
Weird.

**Comment by TeraByte-Official** [comment]
oh wait i figured it out its bc i have results screen on

**Comment by NonsensicalGH** [comment]
Yeah this also happens to me :/
It Only Happens when you have the results screen on btw

**Comment by PatoFlamejanteTV** [comment]
that happened in my phone, but never in my pc.

**Comment by PatoFlamejanteTV** [comment]
> that happened in my phone, but never in my pc.

Nevermind, **i tried again on PC and on android and i got softlocked too**, but it is not an blank screen, **that's an checkerboard yellow pattern screen with no text**, and every time i clicked _Enter/Space_, the squares moves to the left.

https://github.com/user-attachments/assets/a0a01074-6bd5-4d05-a6a9-91c70e3501a4

**_Btw i was on render mode in the pc and in the mobile._**
