### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Official3Gamer** [JordanSantiagoYT/FNF-JS-Engine#482]
### What is your question?

Is there any way to remove week 1-7 in js engine?

I want to make a mod for js engine without the week 1-7 in the way

I have tried to use lua scripts to hide the weeks but that didnt work.

**Comment by JordanSantiagoYT** [comment]
if you want to just remove the weeks from the story menu, go into assets/weeks and delete every file in there

**Comment by moxie-coder** [comment]
> if you want to just remove the weeks from the story menu, go into assets/weeks and delete every file in there

that's usually not ideal for compiled builds, since it'll still look for those assets in general

**Comment by JordanSantiagoYT** [comment]
> > if you want to just remove the weeks from the story menu, go into assets/weeks and delete every file in there
> 
> that's usually not ideal for compiled builds, since it'll still look for those assets in general

i mean if you really want to just remove every file related to base game, there's no easy way to do that as youd have to modify the Project.xml, remove and edit various files etc.

**Comment by moxie-coder** [comment]
> > > if you want to just remove the weeks from the story menu, go into assets/weeks and delete every file in there
> > 
> > 
> > that's usually not ideal for compiled builds, since it'll still look for those assets in general
> 
> i mean if you really want to just remove every file related to base game, there's no easy way to do that as youd have to modify the Project.xml, remove and edit various files etc.

yeah it’s generally not possible without the source code
