### ISSUE TITLE
Custom Text always set to Game Camera and not UI Camera

### ISSUE THREAD

**Issue by TheKamboy** [JordanSantiagoYT/FNF-JS-Engine#483]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I have noticed with some of the mods that use custom text that used to be in the UI camera are now in the In Game Camera.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Use the latest version of JS Engine
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by TheKamboy** [comment]
Looks like from looking into the mods I have installed the default camera for custom text is now the game camera

**Comment by JordanSantiagoYT** [comment]
hey there! just wanted to let you know that i've already identified this issue and fixed it in 1.32.0.

**Comment by TheKamboy** [comment]
> hey there! just wanted to let you know that i've already identified this issue and fixed it in 1.32.0.

Good to know! Thanks!
