### ISSUE TITLE
find ffmpeg better

### ISSUE THREAD

**Issue by cabfile** [JordanSantiagoYT/FNF-JS-Engine#484]
### What feature do you want to get added on the **base** engine?

currently, the engine seems to just check if an ffmpeg windows executable is in the same directory as the engine. now, this would be okay during development, but this method was, in fact, left as is.

you see, this is problematic for:
* people with ffmpeg (in a different directory) in PATH, meaning it can be ran from everywhere
* linux users

so my suggestion is to simply attempt to run `ffmpeg` when booting up the engine. if that fails, its safe to assume ffmpeg is not present.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
hey there. just wanted to state that there's a problem with this.

JSE can only run files that are in its same directory, or folders within that directory.

This means that even if you set FFmpeg in your environment variables, the engine will NOT find ffmpeg anyway and it won't work. ive tested this.

**Comment by JordanSantiagoYT** [comment]
i've also created an edit of the code that finds ffmpeg in your Environment Variables, and even though it currently can find your ffmpeg path now, it still doesn't work anyway.

here's the code:

![image](https://github.com/user-attachments/assets/034b48bd-8fb4-4cc1-a71f-d935e96f7a5e)

It does find ffmpeg if you have it in your Environment Variables:
![image](https://github.com/user-attachments/assets/3d413903-a74c-43f6-ae07-07cb95fa4d3e)

however, even then trying to run it with ffmpegPath doesn't work.

**Comment by JordanSantiagoYT** [comment]
also, i literally have edited the code past its actual release to handle looking for ffmpeg in linux, not just windows

i want to get it working for mac too, but have no idea if it ends with a file extension or not

**Comment by cabfile** [comment]
> JSE can only run files that are in its same directory, or folders within that directory.

...[???????](https://haxe.org/manual/std-input-output-process.html)

**Comment by JordanSantiagoYT** [comment]
> > JSE can only run files that are in its same directory, or folders within that directory.
> 
> ...[???????](https://haxe.org/manual/std-input-output-process.html)


fun fact:
https://github.com/user-attachments/assets/3de3ec6f-8ad9-47ef-8b52-896238a6caf5

**Comment by JordanSantiagoYT** [comment]
take 2 (no ffmpegExists check)

https://github.com/user-attachments/assets/59b23d9d-bdee-4e56-a6f2-59d24eb5d86c

**Comment by cabfile** [comment]
ok i have no idea what sort of thing you're doing that makes ffmpeg not run

my original lua rendering mode worked completely fine mind you:
```lua
function onCreatePost()
	if enabled then
		addHaxeLibrary("Application", "lime.app")
		addHaxeLibrary("Rectangle", "lime.math")
		addHaxeLibrary("Process", "sys.io")
		if addAudio then
			runHaxeCode([[
				setVar('process', new Process('ffmpeg', ['-v', 'quiet', '-y', '-f', 'rawvideo', '-pix_fmt', 'rgba', '-s', ]]..wWidth..[[ + 'x' + ]]..wHeight..[[, '-r', ]] .. fps .. [[, '-i', '-', '-i', './mods/songs/'+Paths.formatToSongPath("]]..songName..[[")+'/Inst.ogg', '-i', './mods/songs/'+Paths.formatToSongPath("]]..songName..[[")+'/Voices.ogg', '-filter_complex', '[1:a][2:a]amix=inputs=2[a]', '-map', '0:v', '-map', '[a]', '-c:v', ']]..codec..[[', '-shortest', ']]..outputFile..[[']));
			]])
		else
			runHaxeCode([[
				setVar('process', new Process('ffmpeg', ['-v', 'quiet', '-y', '-f', 'rawvideo', '-pix_fmt', 'rgba', '-s', ]]..wWidth..[[ + 'x' + ]]..wHeight..[[, '-r', ]] .. fps .. [[, '-i', '-', '-c:v', ']]..codec..[[', ']]..outputFile..[[']));
			]])
		end
		setPropertyFromClass("openfl.Lib", "application.window.width", wWidth)
		setPropertyFromClass("openfl.Lib", "application.window.height", wHeight)
		setPropertyFromClass("openfl.Lib", "application.window.title", "Beginning rendering once countdown hits 0")
		setPropertyFromClass("flixel.FlxG", "autoPause", false)
	end
end
```
and i had ffmpeg in PATH, not near the engine's executable

**Comment by cabfile** [comment]
maybe, just MAYBE the issue is in the haxe/haxeflixel version

i dont know though

**Comment by JordanSantiagoYT** [comment]
> ok i have no idea what sort of thing you're doing that makes ffmpeg not run


well i mean i just removed the ffmpegExists check and rendering doesn't run if ffmpeg isn't where jsengine is
