### ISSUE TITLE
Credit icon

### ISSUE THREAD

**Issue by PleaseEnterUsernameHere** [JordanSantiagoYT/FNF-JS-Engine#485]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

how do i use le credit icon
i have no damn clue how to use it nor do i see a way how to-

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by NAEL2XD** [comment]
Create a folder at mods/images/credits and just put some image here.

For Credits follow this:

**Comment by PleaseEnterUsernameHere** [comment]
i meant in like a song
cuz in the song a 'credit icon' can be applied
is it the same way as that or is it different?

**Comment by JordanSantiagoYT** [comment]
to put a song's credit icon, you have to put the name of the credit icon's png here
![image](https://github.com/user-attachments/assets/48d0ac8d-3fc3-49fa-a97d-d38b0d1cc73a)

To make the credit icon work, it must be placed inside `mods/images/songCreators/`. the same applies for credits bars, they must be put in `mods/images/songHeadings/`.
