### ISSUE TITLE
why this HEPPINING IM THROWING AHH HELP

### ISSUE THREAD

**Issue by AUTISTICFNF** [JordanSantiagoYT/FNF-JS-Engine#487]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![image](https://github.com/user-attachments/assets/b02df1c1-5287-4ed3-afc3-f945e4944611)
![image_2024-08-12_182351990](https://github.com/user-attachments/assets/46b9fad8-25eb-4a8b-9357-068ad83736df)
WHAT

THERE IS A HARD JASON ITS LYING

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by AUTISTICFNF** [comment]
![image_2024-08-12_182602165](https://github.com/user-attachments/assets/749b61c9-c5be-406b-8100-95aae0a16684)
![image_2024-08-12_182603651](https://github.com/user-attachments/assets/d6873e46-dd19-461c-9cf9-cc81047ca4c3)
![image](https://github.com/user-attachments/assets/058e5666-6dc5-4ba3-bf50-9da71df61829)
![image](https://github.com/user-attachments/assets/3208f38d-6ddb-4f0e-96a3-5dc571ab6b4f)
![image](https://github.com/user-attachments/assets/42512392-d54f-4cde-93de-77e97ca6309f)
vvvv
![image](https://github.com/user-attachments/assets/341371ae-c0e2-4a15-9499-46c1d82ecd11)
![image](https://github.com/user-attachments/assets/838809af-3c1f-4c2d-8541-f24a626a3754)
![image](https://github.com/user-attachments/assets/613b0d7d-94fe-4196-b0f5-2e970e2bbc45)
v
![image](https://github.com/user-attachments/assets/ab9ba235-e3b7-47cd-bfe1-6af99e1bf6fd)
vvv

**Comment by moxie-coder** [comment]
you need to use the mods folder, not the assets folder
