### ISSUE TITLE
screenshot bug

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#491]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

when I take a screenshot it doesn't finish the animation of it taking a screenshot and it's stuck with a slightly white tinted screen with the screenshot in the corner
this was found in 0.29
![bug](https://github.com/user-attachments/assets/1aad5dc1-b31f-46b5-b64b-c640e03100a4)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
none
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
just take a screenshot at the right frame at the end of a song
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no source code was modded. I only added characters, scripts, songs, noteskins

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
![image](https://github.com/user-attachments/assets/ba8403bf-35a1-4cff-9475-4b519843420c)

that might be why

**Comment by moxie-coder** [comment]
since you did it during a transition
