### ISSUE TITLE
Option to Disable the Splash Screen.

### ISSUE THREAD

**Issue by FuseIsHere813** [JordanSantiagoYT/FNF-JS-Engine#492]
### What feature do you want to get added on the **base** engine?

I know this could be hassle-free by pressing enter, but how about it becomes MORE hassle-free by an option in the options menu somewhere, so for every bootup, the startup state will automatically skip to the title screen, unless the option is set to false.

the option concept is somewhat like this:
![image](https://github.com/user-attachments/assets/ca903403-809e-4c29-b5c9-f171f6906d40)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by moxie-coder** [comment]
sure I can do that

**Comment by FuseIsHere813** [comment]
thank you! @moxie-coder

**Comment by moxie-coder** [comment]
> thank you! @moxie-coder

np
