### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Oreo-GT** [JordanSantiagoYT/FNF-JS-Engine#493]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

when i try to go in JS Engine it crashes while this happened now, i dont know why its crashing?

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Nope
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by moxie-coder** [comment]
I swear to god

you need to show crash logs or we can't really help fix the problem

**Comment by FuseIsHere813** [comment]
does it crash with a popup??? or does it crash like without anything, if so, that's a fatal error (idk) for you

**Comment by moxie-coder** [comment]
> does it crash with a popup??? or does it crash like without anything, if so, that's a fatal error (idk) for you

usually fatal errors can be caught in an terminal, and the new crash handler I added _should_ be able to catch them but it's unlikely

**Comment by FuseIsHere813** [comment]
i see your point, maybe it's like _too_ too fatal for JSE to survive. / jokes aside, i don't know why that happens with a low chance

**Comment by PatoFlamejanteTV** [comment]
Prob is the noteskin glitch. Try this:

> Open the menu and if the engine can't find the option you already have in the list it'll automatically set it to the first entry in the list

#503
