### ISSUE TITLE
Can't compile modified JS Engine

### ISSUE THREAD

**Issue by mihaillov** [JordanSantiagoYT/FNF-JS-Engine#494]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
source/flixel/FlxGame.hx:6: characters 8-39 : Type not found : flixel.util.typeLimit.NextState
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\source\import.hx:25: characters 8-29 : Type not found : flixel.sound.FlxSound
source/flixel/FlxGame.hx:96: characters 20-29 : Type not found : NextState
how i can fix that?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

TitleState.hx,StartupState.hx,PlayState.hx,MainMenuState.hx,CreditsState.hx

**Comment by moxie-coder** [comment]
update flixel to 5.6.2

**Comment by mihaillov** [comment]
ok i try it

**Comment by mihaillov** [comment]
for some reason it asks for 5.8.0,is this normal?

**Comment by moxie-coder** [comment]
> for some reason it asks for 5.8.0,is this normal?

`haxelib set flixel 5.6.2`

**Comment by mihaillov** [comment]
i set this version,now this error:source/PlayState.hx:32: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,2/flixel/addons/transition/FlxTransitionableState.hx:81: lines 81-90 : Warning : switchTo is deprecated, use startOutro
source/PlayState.hx:1880: characters 51-67 : Type not found : FlxRuntimeShader

**Comment by moxie-coder** [comment]
> i set this version,now this error:source/PlayState.hx:32: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,2/flixel/addons/transition/FlxTransitionableState.hx:81: lines 81-90 : Warning : switchTo is deprecated, use startOutro source/PlayState.hx:1880: characters 51-67 : Type not found : FlxRuntimeShader

`haxelib update flixel-addons --always`

**Comment by mihaillov** [comment]
same error,nothing changed

**Comment by moxie-coder** [comment]
> same error,nothing changed

then do `haxelib install flixel-addons` since it might've not updated properly

**Comment by moxie-coder** [comment]
or `haxelib set flixel-addons 3.2.3 --always` if it did install but not switch versions

**Comment by mihaillov** [comment]
C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by FuseIsHere813** [comment]
install visual studio 2019

**Comment by moxie-coder** [comment]
> C:\Users\mihap\Desktop\P-831 Edition\Expungas Edition\FNF-JS-Engine-main\export\release\windows\obj>setlocal enabledelayedexpansion Warning: Could not find Visual Studio VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC

you need Visual studio and the MSVC compiler which you can get by selecting the C++ workflow in the installer

**Comment by mihaillov** [comment]
ok,but not installable anymore on microsoft site(i using wayback machine to find 2019)

**Comment by moxie-coder** [comment]
> install visual studio 2019 / it's required packages

Microsoft removed the downloads for it

**Comment by moxie-coder** [comment]
> ok,but not installable anymore on microsoft site(i using wayback machine to find 2019)

it'll be fine with 2022

**Comment by mihaillov** [comment]
ok

**Comment by FuseIsHere813** [comment]
> > install visual studio 2019 / it's required packages
> 
> Microsoft removed the downloads for it (which is very fucking dumb)

too bad there's archives of it lo-

**Comment by moxie-coder** [comment]
I know lol, it’s fine with 2022 either way

**Comment by FuseIsHere813** [comment]
very clever way tbh, never thought of vs2022 actually working

**Comment by mihaillov** [comment]
too late,downloading the vs2019 with c++ things

**Comment by mihaillov** [comment]
it worked
