### ISSUE TITLE
Um

### ISSUE THREAD

**Issue by NonsensicalGH** [JordanSantiagoYT/FNF-JS-Engine#496]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

The "Inst" In the song file keeps playing if you entered Character editor (from song)

https://github.com/user-attachments/assets/4de7ee02-d12d-499d-a3aa-8a932a9dab13

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
No
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/c538eaa9-6386-4333-b540-ee6dd729ce51)
already fixed.
