### ISSUE TITLE
what's better version with optimized?

### ISSUE THREAD

**Issue by helpmesd** [JordanSantiagoYT/FNF-JS-Engine#497]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

what's better version with optimized?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by FuseIsHere813** [comment]
what?

**Comment by moxie-coder** [comment]
currently the newer versions past 1.28, but can you be more specific

**Comment by moxie-coder** [comment]
you also used the wrong template too -_-
