### ISSUE TITLE
how do i get ffmpeg to work?

### ISSUE THREAD

**Issue by melon2212** [JordanSantiagoYT/FNF-JS-Engine#498]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

trying to render something.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

if adding mods count, then yes.

**Comment by moxie-coder** [comment]
you need to make sure ffmpeg is in the game folder or in the path

**Comment by JordanSantiagoYT** [comment]
it has to be in the same folder as JSEngine.

why can't you just put it in your path?
because i've tested and RM doesn't start if ffmpeg is NOT located in the same folder as JSEngine.
