### ISSUE TITLE
Freeplay And song bug

### ISSUE THREAD

**Issue by einbuis07** [JordanSantiagoYT/FNF-JS-Engine#499]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

When i start a song from freeplay then the game is crashing idk what's happening

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
When i start a song from freeplay then the game is crashing idk what's happening
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
…can you give crash logs and show the error message?

**Comment by einbuis07** [comment]
uh i didn't type that: Game dosen't makes crash log

**Comment by moxie-coder** [comment]
> uh i didn't type that: Game dosen't makes crash log

I can’t help you if you can’t provide a reason as to why the game crashed

**Comment by einbuis07** [comment]
it crashing after this update in previous version this was'nt happen

**Comment by einbuis07** [comment]
i think it's code problem

**Comment by einbuis07** [comment]
idk

**Comment by einbuis07** [comment]
after this update it starts crash

**Comment by moxie-coder** [comment]
okay @einbuis07 sorry for doubting you, I was able to replicate with the note shaders option turned off, turning them back on fixes it

**Comment by moxie-coder** [comment]
Edit: okay nvm turns out my pc is just low on ram, so yeah nvm

**Comment by moxie-coder** [comment]
@einbuis07 can you try running the game from command prompt and see what error shows up?

**Comment by einbuis07** [comment]
ill try

**Comment by einbuis07** [comment]
![image](https://github.com/user-attachments/assets/81f3b36e-1df5-475f-9f17-3cb6a3ca4a21)

**Comment by einbuis07** [comment]
cmd shows that

**Comment by moxie-coder** [comment]
well, I don’t see any errors so looks like it is a low end pc issue

**Comment by einbuis07** [comment]
:(
