### ISSUE TITLE
Add Language Section in Settings

### ISSUE THREAD

**Issue by einbuis07** [JordanSantiagoYT/FNF-JS-Engine#500]
### What feature do you want to get added on the **base** engine?

Can you add "Language" Section in Settings

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by moxie-coder** [comment]
maybe, soon

**Comment by einbuis07** [comment]
ok

**Comment by mcagabe19** [comment]
well I aint doing texts for mobile

**Comment by PatoFlamejanteTV** [comment]
Cool idea, but probably no one is going to make an .json translating 3435 texts to 63576 languages

**Comment by PatoFlamejanteTV** [comment]
so yeah were not doin allat lil bro
