### ISSUE TITLE
JORDAN SANTIAGO Forgot To Create notesplashes Folder!

### ISSUE THREAD

**Issue by einbuis07** [JordanSantiagoYT/FNF-JS-Engine#501]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

When i play song with enabled note splashes then it dosen't works but id disabled note splashes then song works
Jordan Santiago Create note splashes Folder!!

### Command Prompt/Terminal/Crash logs (if existing)

```bash
UHHHH
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
…they literally do work, did you even update properly?

**Comment by einbuis07** [comment]
Yea??

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/e6c82938-70ee-4a27-b1c0-9b6b8c8e7ffe)
You did not read the changelog.

**Comment by JordanSantiagoYT** [comment]
It says "You must go in the Visuals & UI menu to reset your Note Splash skin settings."
