### ISSUE TITLE
Js Engine just crashes when i select an song (the main songs and custom)

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#503]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Hi, today i opened the JS engine and installed the most update ([A Slightly BIG Update - 1.32.0](https://github.com/JordanSantiagoYT/FNF-JS-Engine/releases/tag/1.32.0)), but now **EVERY song just crashes when i open.**

_**Heres some videos of the bug:**_

https://github.com/user-attachments/assets/8bcfd239-3da0-44a8-9386-e6bad0c46247

https://github.com/user-attachments/assets/7f47a074-66e9-4518-8959-850e3021c029

### Command Prompt/Terminal/Crash logs (if existing)

```bash
PS C:\Users\mcmco\Downloads\FNF-JS-Engine> C:\Users\mcmco\Downloads\FNF-JS-Engine\JSEngine.exe
PS C:\Users\mcmco\Downloads\FNF-JS-Engine> source/DiscordClient.hx:82: Discord Client initialized
source/TitleState.hx:119: checking for update
source/TitleState.hx:132: version online: 1.32.0, your version: 1.32.0
source/TitleState.hx:139: the versions match!
source/FreeplayState.hx:656: bopeebo
source/FreeplayState.hx:670: CURRENT WEEK: week1
source/LoadingState.hx:162: Setting asset folder to shared
source/PlayState.hx:1907: Anim speed: 1.01
source/Conductor.hx:156: new BPM map BUDDY []
source/Paths.hx:84: null
source/Paths.hx:88: noteskins/NOTE_assets
source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes/noteSplashes-psych_engine.png)
source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes/noteSplashes-psych_engine.png)
source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes/noteSplashes-psych_engine.png)
source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes/noteSplashes-psych_engine.png)
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
open an random song
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by NonsensicalGH** [comment]
Yeah it happens to me too :/

**Comment by PatoFlamejanteTV** [comment]
nvm i just fixed it by going to **Options > Visuals and UI > Go to the splash settings and Make this: Left Arrow, Right Arrow** _(yes, you gonna just make that with arrow keys)_


https://github.com/user-attachments/assets/291f84b5-373d-4bd8-af43-2aba77b7bea7

**Comment by JordanSantiagoYT** [comment]
> nvm i just fixed it by going to **Options > Visuals and UI > Go to the splash settings and Make this: Left Arrow, Right Arrow** _(yes, you gonna just make that with arrow keys)_
> 
>  bandicam.2024-08-23.16-35-21-300.mp4

you do not need to do all of that, just open the menu and if the engine can't find the option you already have in the list it'll automatically set it to the first entry in the list
