### ISSUE TITLE
Crash Without Crash Logs

### ISSUE THREAD

**Issue by NonsensicalGH** [JordanSantiagoYT/FNF-JS-Engine#504]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Um what

https://github.com/user-attachments/assets/b13d0481-d0a2-459c-985c-4fcfca9f618e

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by NonsensicalGH** [comment]
When it is with the black screen, it crashes

**Comment by JordanSantiagoYT** [comment]
can you try opening it in a command prompt, see if that does anything

**Comment by NonsensicalGH** [comment]
How do i do that

**Comment by JordanSantiagoYT** [comment]
step 1. Win + R, type "cmd" in the box
step 2. put in "cd (your JSE directory)"
step 3. type "JSEngine"

**Comment by NonsensicalGH** [comment]
NVM IT WAS THE NOTESPLASH IN THE CHART EDITOR-

**Comment by JordanSantiagoYT** [comment]
brub
