### ISSUE TITLE
Latest Commit to fix note scaling un-centered notes

### ISSUE THREAD

**Issue by TheKamboy** [JordanSantiagoYT/FNF-JS-Engine#505]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

notes are now not centered

![image](https://github.com/user-attachments/assets/6f59de97-83ea-41f1-a970-1bdd7ae144e2)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
use the latest commit
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
not much i can do to fix this considering: 
![image](https://github.com/user-attachments/assets/89c8cfa7-7fb3-4d14-9cf3-ef948419207d)

**Comment by TheKamboy** [comment]
> not much i can do to fix this considering: 
> ![image](https://github.com/user-attachments/assets/89c8cfa7-7fb3-4d14-9cf3-ef948419207d)
> 

Alright

**Comment by JordanSantiagoYT** [comment]
OK SO THE FIX FOR THIS WAS LITERALLY TO MOVE THE UPDATEHITBOX BELOW THIS STATEMENT INTO IT
![image](https://github.com/user-attachments/assets/73536841-b1a3-4273-badb-d601389e6556)

**Comment by JordanSantiagoYT** [comment]
unfortunately, it seems now i have a NEW issue relating to this: If you turn off the Enable Color Shader option and add a Hurt Note, it doesn't crash but the HN is instead uncentered

**Comment by JordanSantiagoYT** [comment]
update 2: it turns out the way to fix this is by simply not calling centerOffsets and centerOrigin.

but.. that's required to make the RGB Shader notes centered

**Comment by moxie-coder** [comment]
> update 2: it turns out the way to fix this is by simply not calling centerOffsets and centerOrigin.
> 
> but.. that's required to make the RGB Shader notes centered

then do it when they're not enabled

**Comment by JordanSantiagoYT** [comment]
ok
