### ISSUE TITLE
Game crash on song open

### ISSUE THREAD

**Issue by TeraByte-Official** [JordanSantiagoYT/FNF-JS-Engine#506]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

If you try to open a song, the game just closes.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Open any song through story mode or freeplay
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by NAEL2XD** [comment]
Use any version except for 1.32

**Comment by newfuckingplayer** [comment]
ok i kinda fixed it by resetting my noteskins to default but whenever i load a song with hurt notes i get crashed

**Comment by newfuckingplayer** [comment]
and sometimes when i load a song with no hurt notes it crashes in some section

**Comment by newfuckingplayer** [comment]
ok wait it may be because it has like a hurt note in the section that makes it crash

**Comment by TeraByte-Official** [comment]
> ok i kinda fixed it by resetting my noteskins to default but whenever i load a song with hurt notes i get crashed

Doesn't work for me

**Comment by TeraByte-Official** [comment]
Realized I need to change some of my settings or it won't work, but I'm not entirely sure which setting specifically

**Comment by TeraByte-Official** [comment]
i literally reset. literally reset everything in the. the graphics & ui menu and. and it still. doesnt work.

**Comment by TeraByte-Official** [comment]
i literally reset. literally reset every setting and. and it still. doesnt work.

**Comment by JordanSantiagoYT** [comment]
can you.. try opening the game with a command prompt

**Comment by newfuckingplayer** [comment]
it returned null

**Comment by newfuckingplayer** [comment]
it may be because theres like no hurt noteskin???

**Comment by newfuckingplayer** [comment]
nope

**Comment by JordanSantiagoYT** [comment]
can i have a full log?

**Comment by TeraByte-Official** [comment]
```source/DiscordClient.hx:82: Discord Client initialized
source/TitleState.hx:119: checking for update
source/TitleState.hx:132: version online: 1.32.0, your version: 1.32.0
source/TitleState.hx:139: the versions match!
source/DiscordClient.hx:60: (Discord) Connected to User (irember135)
source/FreeplayState.hx:656: looking-for-starworld
source/FreeplayState.hx:670: CURRENT WEEK: windixtra
source/LoadingState.hx:162: Setting asset folder to shared
source/PlayState.hx:1907: Anim speed: 1
source/Conductor.hx:156: new BPM map BUDDY []
source/Paths.hx:84:
source/Paths.hx:88: noteskins/NOTE_assets
source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes.png)
source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes.png)
source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes/noteSplashes-psych_engine.png)
source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes/noteSplashes-psych_engine.png)```

**Comment by TeraByte-Official** [comment]
it's because the note splash textures don't exist
![image](https://github.com/user-attachments/assets/6a9ae95e-5e15-43f3-beeb-13528f4ab8dd)

**Comment by moxie-coder** [comment]
it was fixed in the latest versions

**Comment by JordanSantiagoYT** [comment]
> it's because the note splash textures don't exist ![image](https://private-user-images.githubusercontent.com/105992370/361146857-6a9ae95e-5e15-43f3-beeb-13528f4ab8dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDk5MTMsIm5iZiI6MTcyNDUwOTYxMywicGF0aCI6Ii8xMDU5OTIzNzAvMzYxMTQ2ODU3LTZhOWFlOTVlLTVlMTUtNDNmMy1iZWViLTEzNTI4ZjRhYjhkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQxNDI2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTg4ODIxOTFjZTllMjAzM2VlNDM3Njc3NDkyZGEyNTUyZTAyYWZjY2Q2OGI0NWFkNzdkMTliN2EwODk3NDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8BxW3d8rf31mTysfnWUko_NA-685S7wUM_iBnL0S7QA)

1. the notesplashes were moved to 'images/noteSplsahes'
2. that note splash doesn't exist, i replaced the defaults so you have to go to the Visuals & UI menu to reset it

**Comment by TeraByte-Official** [comment]
??
![image](https://github.com/user-attachments/assets/e209ec06-f07d-4bda-a199-e2dc39b9d562)

**Comment by JordanSantiagoYT** [comment]
did you update properly?

**Comment by JordanSantiagoYT** [comment]
because it should be there

**Comment by TeraByte-Official** [comment]
its not even in the latest version .zip

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/43973528-37aa-4baf-83c8-9989c31bd111)

**Comment by JordanSantiagoYT** [comment]
that's in the zip file i downloaded.

**Comment by TeraByte-Official** [comment]
its not there for me

**Comment by JordanSantiagoYT** [comment]
try reinstalling the engine.

**Comment by JordanSantiagoYT** [comment]
for simplification, download a zip file of 1.32.0 then extract its contents into your JSE directory.

**Comment by TeraByte-Official** [comment]
nope
![image](https://github.com/user-attachments/assets/ddee1474-99d5-43c3-a8ec-f3bf95759e6d)

**Comment by JordanSantiagoYT** [comment]
are you sure that's the right js engine build?

**Comment by TeraByte-Official** [comment]
yes

**Comment by JordanSantiagoYT** [comment]
sort files by name

**Comment by JordanSantiagoYT** [comment]
WAIT

**Comment by JordanSantiagoYT** [comment]
YOU'RE LOOKING IN ASSETS/IMAGES

**Comment by JordanSantiagoYT** [comment]
the folder is located in `assets/shared/images`

**Comment by TeraByte-Official** [comment]
yea its there

**Comment by JordanSantiagoYT** [comment]
okay so you do have the right build

**Comment by JordanSantiagoYT** [comment]
just.. don't load any songs that have the splash skin set to "noteSplashes", i'm working on getting 1.32.1 out

**Comment by TeraByte-Official** [comment]
kk

**Comment by bineapple-lol** [comment]
Turning off shaders fixed it for me
maybe shaders could be turned off automatically upon song loading as a workaround or smth?

**Comment by JordanSantiagoYT** [comment]
> just.. don't load any songs that have the splash skin set to "noteSplashes", i'm working on getting 1.32.1 out which will fix this

UPDATE: 1.32.1 is now out!! notesplash crashes should hopefully be fixed!
