### ISSUE TITLE
Difficulties resetting note colors

### ISSUE THREAD

**Issue by bineapple-lol** [JordanSantiagoYT/FNF-JS-Engine#507]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Shift + R doesn't reset the regular note colors, and only works on pixel notes temporarily before going back to previous settings upon going out and back into the menu.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Changed normal and pixel note colors, exited out and back into settings, attempted to reset normal note colors (and fail), reset pixel note colors, exit note colors editor (still in settings), go back into note colors editor
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by bineapple-lol** [comment]
See this issue also https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/506.

**Comment by TeraByte-Official** [comment]
hi i wrote that issue

**Comment by JordanSantiagoYT** [comment]
> ### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!
> Shift + R doesn't reset the regular note colors, and only works on pixel notes temporarily before going back to previous settings upon going out and back into the menu.

can you show me a video of this? for me it works perfectly fine

**Comment by bineapple-lol** [comment]
> > ### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!
> > Shift + R doesn't reset the regular note colors, and only works on pixel notes temporarily before going back to previous settings upon going out and back into the menu.
> 
> can you show me a video of this? for me it works perfectly fine

I'll send it later

**Comment by SuperRyan0308** [comment]
https://github.com/user-attachments/assets/cd53a94f-b979-46b1-bd71-b39ccb85bb0b

**Comment by JordanSantiagoYT** [comment]
Try opening it with a command prompt, and show me the command prompt's output.

step 1. Win + R, type "cmd" in the box
step 2. put in "cd (your JSE directory)"
step 3. type "JSEngine"

**Comment by SuperRyan0308** [comment]
I don't think I know how to find the directory

**Comment by JordanSantiagoYT** [comment]
Uploading 2024-08-24 09-52-43.mp4…

here's a clip of how to get your directory

**Comment by SuperRyan0308** [comment]
C:\Users\rjkel\Downloads\FNF-JS-Engine


I don't own the "main" version

**Comment by moxie-coder** [comment]
> C:\Users\rjkel\Downloads\FNF-JS-Engine
> 
> I don't own the "main" version

that's the repo you cloned locally, the main version is just the git branch

**Comment by JordanSantiagoYT** [comment]
that's fine, just the directory that contains your JSE files

**Comment by SuperRyan0308** [comment]
I got it opened now

**Comment by JordanSantiagoYT** [comment]
for me, it's C:\Users\j\Downloads\FNF-JSEngine-main\export\release\windows\bin because its my compiled build

**Comment by SuperRyan0308** [comment]
ok maybe it's a bug, because I got it opened with a command but it still crashes

**Comment by JordanSantiagoYT** [comment]
does it give any output?

**Comment by JordanSantiagoYT** [comment]
like does the command prompt show anything when it crashes

**Comment by SuperRyan0308** [comment]
oh no its returning null NOOOO (assets/images/noteSplashes.png)

**Comment by JordanSantiagoYT** [comment]
oh

**Comment by JordanSantiagoYT** [comment]
it's because the chart's notesplash thing is 'noteSplashes', so when the game is initializing the note splashes it tries to initialize the config file for that skin, but it can't do that which outputs a crash

**Comment by JordanSantiagoYT** [comment]
i've fixed that in a recent commit

**Comment by moxie-coder** [comment]
> oh no its returning null NOOOO (assets/images/noteSplashes.png)

that's not a crash

**Comment by JordanSantiagoYT** [comment]
\

> > oh no its returning null NOOOO (assets/images/noteSplashes.png)
> 
> that's not a crash

i mean i tried playing a song which had the notesplash file set to 'noteSplashes' and it crashed for me

**Comment by JordanSantiagoYT** [comment]
i've since fixed that

**Comment by moxie-coder** [comment]
just show the full thing for christ sake, it would make things so much easier if you did

**Comment by moxie-coder** [comment]
> \
> 
> > > oh no its returning null NOOOO (assets/images/noteSplashes.png)
> > 
> > 
> > that's not a crash
> 
> i mean i tried playing a song which had the notesplash file set to 'noteSplashes' and it crashed for me

alright

**Comment by SuperRyan0308** [comment]
C:\Users\rjkel\Downloads\FNF-JS-Engine>source/DiscordClient.hx:82: Discord Client initialized
source/TitleState.hx:119: checking for update
source/TitleState.hx:132: version online: 1.32.0, your version: 1.32.0
source/TitleState.hx:139: the versions match!
source/FreeplayState.hx:656: fuming
source/FreeplayState.hx:670: CURRENT WEEK: bambi
source/LoadingState.hx:162: Setting asset folder to shared
source/PlayState.hx:1907: Anim speed: 1
source/Conductor.hx:156: new BPM map BUDDY []
source/Paths.hx:84:
source/Paths.hx:88: noteskins/NOTE_assets
source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes.png)
source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes.png)

**Comment by JordanSantiagoYT** [comment]
> C:\Users\rjkel\Downloads\FNF-JS-Engine>source/DiscordClient.hx:82: Discord Client initialized source/TitleState.hx:119: checking for update source/TitleState.hx:132: version online: 1.32.0, your version: 1.32.0 source/TitleState.hx:139: the versions match! source/FreeplayState.hx:656: fuming source/FreeplayState.hx:670: CURRENT WEEK: bambi source/LoadingState.hx:162: Setting asset folder to shared source/PlayState.hx:1907: Anim speed: 1 source/Conductor.hx:156: new BPM map BUDDY [] source/Paths.hx:84: source/Paths.hx:88: noteskins/NOTE_assets source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes.png) source/Paths.hx:552: oh no its returning null NOOOO (assets/images/noteSplashes.png)

alright, so its the notesplash crash i fixed

**Comment by moxie-coder** [comment]
yeah this was fixed in the latest versions

**Comment by bineapple-lol** [comment]
> > ### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!
> > Shift + R doesn't reset the regular note colors, and only works on pixel notes temporarily before going back to previous settings upon going out and back into the menu.
> 
> can you show me a video of this? for me it works perfectly fine

Uploading bug.mp4…

**Comment by JordanSantiagoYT** [comment]
yeah, this works fine for me so not much i can do for you.

https://github.com/user-attachments/assets/a27a2c11-bfc3-4931-ac23-50f479770e14

**Comment by bineapple-lol** [comment]
boowomp
