### ISSUE TITLE
Anti-crash for loading missing songs in week selector

### ISSUE THREAD

**Issue by nxvelveteen** [JordanSantiagoYT/FNF-JS-Engine#508]
### What feature do you want to get added on the **base** engine?

read the title

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
because Story Mode song loading is more complex, this will be more difficult to implement.

**Comment by JordanSantiagoYT** [comment]
however, i will consider it

**Comment by moxie-coder** [comment]
> because Story Mode song loading is more complex, this will be more difficult to implement.

pretty sure 0.7/1.0 added this

**Comment by JordanSantiagoYT** [comment]
> > because Story Mode song loading is more complex, this will be more difficult to implement.
> 
> pretty sure 0.7/1.0 added this

ive checked and im pretty sure it only prevents a crash if the first song in the week is missing

**Comment by Stefan2008Git** [comment]
> > > because Story Mode song loading is more complex, this will be more difficult to implement.
> > 
> > 
> > pretty sure 0.7/1.0 added this
> 
> ive checked and im pretty sure it only prevents a crash if the first song in the week is missing

No, it only happens if you have a "missing" week file

**Comment by moxie-coder** [comment]
technically added in recent commit
