### ISSUE TITLE
Constant crash

### ISSUE THREAD

**Issue by PleaseEnterUsernameHere** [JordanSantiagoYT/FNF-JS-Engine#509]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

i downloaded the new update, changed my note colors, and now whenever i try to load a song, it just crashes the game
it doesnt give me a crash log either, and this happens with _every single song_
i don't know what to do, please help!

### Command Prompt/Terminal/Crash logs (if existing)

```bash
it didn't generate any crash logs.
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
no
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only thing i edited was adding new songs and the note colors

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
can you.. open the game with a command prompt

**Comment by bineapple-lol** [comment]
Disable your shaders in Options > Graphics > Shaders and try again

**Comment by PleaseEnterUsernameHere** [comment]
@bineapple-lol
didnt work, still going kaput

trying jordan's way rn, and i pray that make js engine worky

**Comment by PleaseEnterUsernameHere** [comment]
@JordanSantiagoYT

that just made the game crash _instantly,_ though it did give me this:
![image](https://github.com/user-attachments/assets/7dd25a61-9d8c-4664-9b1e-bb9cf682f261)

**Comment by bineapple-lol** [comment]
Try to download the missing file and put it in
https://www.mediafire.com/file/hm31gbnar3owsbi/titleEnter.xml/file

**Comment by JordanSantiagoYT** [comment]
did you also CD to the JSE directory? from what ive tried you can't just copy and paste the JSE file because there's issues with that (mainly you won't be able to get past the startup screen)

**Comment by PleaseEnterUsernameHere** [comment]
@JordanSantiagoYT

just tried to CD, but it told me JSEngine.exe does not exist even though it does.
![image](https://github.com/user-attachments/assets/78b214ec-0fed-4922-80dc-27a1e2b80742)

**Comment by PleaseEnterUsernameHere** [comment]
fuck i didnt mean to close it

**Comment by Dimarar** [comment]
> can you.. open the game with a command prompt
> 
> step 1. Win + R, type "cmd" in the box step 2. put in "cd (your JSE directory)" step 3. type "JSEngine"
> 
> also, please update to 1.32.1 if you see a 'oh no its returning null NOOO (assets/images/noteSplashes.png)' thing in the CMD Prompt
![image](https://github.com/user-attachments/assets/08a8b9bd-6b84-4160-804c-b6e85de990f2)
well

**Comment by Eware-0** [comment]
i am having the same error, it just crashes after selecting a song, any song, latest version., was working before the latest update

**Comment by JordanSantiagoYT** [comment]
go to the visuals & UI options menu to reset your noteskin and splash skins to default
.

**Comment by RedImpostorsSon** [comment]
I have the same issue
