### ISSUE TITLE
Togglable splash screen

### ISSUE THREAD

**Issue by nxvelveteen** [JordanSantiagoYT/FNF-JS-Engine#510]
### What feature do you want to get added on the **base** engine?

In my opinion the fire in the hole meme is kinda dead now and I mostly just want to have the normal splash screen show up instead. You should be able to toggle between fire in the hole, js engine, and random.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by moxie-coder** [comment]
duplicate of #492

**Comment by moxie-coder** [comment]
also it was already fucking added
