### ISSUE TITLE
Crash in songs where more than 100k notes what doing?

### ISSUE THREAD

**Issue by helpmesd** [JordanSantiagoYT/FNF-JS-Engine#512]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

im download the new update from github im copy file with mods what's im dowloading and start a fine spamtrack crash what doing?????

### Command Prompt/Terminal/Crash logs (if existing)

```bash
dont have
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
im just start song with more than 100k and all
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by helpmesd** [comment]
> if it's still crashing, let me see a command prompt output:

![Desktop_240825_2002](https://github.com/user-attachments/assets/11c5216b-c244-44b7-9a4f-ce228601690f)

**Comment by helpmesd** [comment]
i set default why here type physics engine.png

**Comment by JordanSantiagoYT** [comment]
did you actually open the visuals & ui menu

**Comment by helpmesd** [comment]
yes

**Comment by helpmesd** [comment]
now crashed any song ;( maybe reinstall?

**Comment by JordanSantiagoYT** [comment]
idk then, because im pretty sure 1.32.2 is supposed to fix the bug that sets your default note splash to "Psych Engine"

**Comment by helpmesd** [comment]
> idk then, because im pretty sure 1.32.2 is supposed to fix the bug that sets your default note splash to "Psych Engine"

check maybe

**Comment by helpmesd** [comment]
maybe dont fix that

**Comment by moxie-coder** [comment]
> maybe dont fix that

don't tell us how to do our job, if it wasn't fixed we would have more problems

**Comment by PatoFlamejanteTV** [comment]
I had same problem, check this:
https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/503#issuecomment-2307762745
