### ISSUE TITLE
Softcoded achievements?

### ISSUE THREAD

**Issue by nxvelveteen** [JordanSantiagoYT/FNF-JS-Engine#513]
### What feature do you want to get added on the **base** engine?

psych engine 1.0 has it and it was a feature I had been wanting for a while even before that
if you don't want to add it that's fine

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
that's.. already been a thing

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/221c49e1-253b-4768-9a0f-7754fb70dcdf)

**Comment by nxvelveteen** [comment]
oh ok then
are there any video tutorials for this?

**Comment by JordanSantiagoYT** [comment]
i mean.. since softcoded achievements are new to PE, not really?

**Comment by nxvelveteen** [comment]
ok

**Comment by JordanSantiagoYT** [comment]
however, i don't like that custom achievements system and am actually going to rework it so adding custom achievements is actually possible and easy to do
