### ISSUE TITLE
No option to change noteskin

### ISSUE THREAD

**Issue by BostinTeaParty** [JordanSantiagoYT/FNF-JS-Engine#514]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

No option to change noteskin
![image](https://github.com/user-attachments/assets/eac7da19-9ecd-4bcf-a184-0b8af9c6257c)

![image](https://github.com/user-attachments/assets/0fd76367-952e-4d1a-98e1-9c28c9189e80)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
It just happened after updating to 1.32.2
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by BostinTeaParty** [comment]
![image](https://github.com/user-attachments/assets/91a82894-bcdb-460c-815a-8268e71b5785)

**Comment by BostinTeaParty** [comment]
![Untitled design](https://github.com/user-attachments/assets/2f0122e1-7843-454f-b94b-aa0b19361e6e)

**Comment by BostinTeaParty** [comment]
hold on, the update didnt friggin install any note assets whatsoever?

**Comment by moxie-coder** [comment]
they were moved into a different folder

**Comment by BostinTeaParty** [comment]
Had to reinstall JS Engine and move my mods

**Comment by BostinTeaParty** [comment]
and yes, i did reset settings to default before, and it set it to psych engine

**Comment by JordanSantiagoYT** [comment]
> hold on, the update didnt friggin install any note assets whatsoever? ![image](https://private-user-images.githubusercontent.com/65133896/361257105-9f40f9dc-b812-4087-a0e7-f68315258f06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjEzNzEsIm5iZiI6MTcyNDcyMTA3MSwicGF0aCI6Ii82NTEzMzg5Ni8zNjEyNTcxMDUtOWY0MGY5ZGMtYjgxMi00MDg3LWEwZTctZjY4MzE1MjU4ZjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAxMTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTVkODA2MDQxZWJlNzhhZmE5MTE3YTdiN2RjY2UxZjg5YmY4MzAyNWU5YWRlMGYwZTc3YjljYjkwZDllZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qd7_o7DquTOFhH3nMgTihGv42UIoF2DuQvWDcjxznL4)

btw the folder's in assets/shared/images, not assets/images
