### ISSUE TITLE
Crash when trying to enter a song

### ISSUE THREAD

**Issue by Elytra-pixel** [JordanSantiagoYT/FNF-JS-Engine#515]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

1.32.2

### Command Prompt/Terminal/Crash logs (if existing)

```bash
It crashed without a crashlog i have proof of it (check next field)
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
I had like 1.29.something and i had the note color mode set to be by character and i disabled it when i tried making a mod and crashed when placing a note on the chart editor it crashed

i have a video but its on a mod i have been making for a while that i just updated the Engine today

https://drive.google.com/file/d/1m4XEmuV-G16TN3CX82RJjxsc9tw-t-tI/view?usp=sharing
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didnt edit anything

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by helpmesd** [comment]
if still crashes doing another splash but not physcs engine

**Comment by Elytra-pixel** [comment]
i disabled that and it didnt work Char-Based note i might try to disable it in an older version

**Comment by Elytra-pixel** [comment]
i will try disabling everything about notes

**Comment by Eware-0** [comment]
any fix? there is one mod that crashes on the new update that i have

**Comment by Elytra-pixel** [comment]
I had to wait to till the settings file updated to try ty for the help

**Comment by moxie-coder** [comment]
np
