### ISSUE TITLE
game either crashes or bugs out when entering any song

### ISSUE THREAD

**Issue by bsaweee** [JordanSantiagoYT/FNF-JS-Engine#517]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

when going into a song the ram usage skyrockets to 300+ mb and if im even able to load the whole song the timer is messed up showing 1 -1 1, and when i try to press a note the game crashes even with everything default.

### Command Prompt/Terminal/Crash logs (if existing)

```bash
source/Paths.hx:84: noteskins/NOTE_assets
source/Paths.hx:88: noteskins/NOTE_assets
source/FreeplayState.hx:656: stress-hard
source/FreeplayState.hx:670: CURRENT WEEK: week7
source/LoadingState.hx:162: Setting asset folder to week7
source/PlayState.hx:1901 : Anim speed: 1 source/Conductor.hx:156: new BPM map BUDDY []
source/Paths.hx:84: null
source/Paths.hx:88: noteskins/NOTE_assets
source/Paths.hx:553: oh no its returning null NO000 (assets/images/noteSplashes/noteSplashes-psych_engine.png)
source/Paths.hx:553: oh no its returning null NOOOO (assets/images/noteSplashes/noteSplashes-psych_engine.png) source/Paths.hx:553: oh no its returning null NOOOO (assets/images/noteSplashes/noteSplashes-psych_engine.png)
source/Paths.hx:553: oh no its returning null NO000 (assets/images/noteSplashes/noteSplashes-psych_engine.png)
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
just entering a song will do it
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
was already fixed in newer versions
