### ISSUE TITLE
why did my game crash if i choose a song or week for real

### ISSUE THREAD

**Issue by kyleinvoice** [JordanSantiagoYT/FNF-JS-Engine#519]
### What feature do you want to get added on the **base** engine?

https://github.com/user-attachments/assets/eaae8007-f388-4232-a69b-38bd36b9c52b

### To test your sight, and reliability, please select the option of what should NOT be requested.

Actual feedback

**Comment by kyleinvoice** [comment]
why

**Comment by JordanSantiagoYT** [comment]
Wrong template.

**Comment by JordanSantiagoYT** [comment]
use the Bug one.

**Comment by kyleinvoice** [comment]
where

**Comment by kyleinvoice** [comment]
like what template like what folder

**Comment by kyleinvoice** [comment]
is it the example_mods folder

**Comment by JordanSantiagoYT** [comment]
the bug issue template..

**Comment by moxie-coder** [comment]
> is it the example_mods folder

the bug template on github retard

**Comment by kyleinvoice** [comment]
it's fixed

**Comment by moxie-coder** [comment]
ok
