### ISSUE TITLE
again with no mods

### ISSUE THREAD

**Issue by kyleinvoice** [JordanSantiagoYT/FNF-JS-Engine#520]
### What feature do you want to get added on the **base** engine?

https://github.com/user-attachments/assets/80564a19-09cb-4fd3-893e-bcdd36a48e95

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by NAEL2XD** [comment]
have you tried use the version <1.29? would usually work best with it

**Comment by JordanSantiagoYT** [comment]
can you please go in the visuals & ui menu and reset/change your noteskin/splash skin options?

also, not only did you fail the test again, you also used the wrong template again

**Comment by JordanSantiagoYT** [comment]
for better clarification, you used the wrong issue template.

**Comment by moxie-coder** [comment]
okay when uploading images, make sure you *wait* for it to finish

**Comment by moxie-coder** [comment]
![image](https://github.com/user-attachments/assets/e1c6bfad-f317-461e-a5d7-eb3004ce892f)

**Comment by kyleinvoice** [comment]
it's more then a oreo

**Comment by kyleinvoice** [comment]
![Uploading oreo.png…]()

**Comment by kyleinvoice** [comment]
![Uploading oreo.png…]()
