### ISSUE TITLE
Vocal files still try to load when "Has voice track" is unchecked

### ISSUE THREAD

**Issue by nxvelveteen** [JordanSantiagoYT/FNF-JS-Engine#521]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Even when "Has voice track" is unselected, the engine still tries to load the voice track files and crashes because there are none
The song folder I'm trying to load just has a single "Inst.ogg" file for instrumental + vocals and the folder name itself has dashes instead of spaces for extra measure

### Command Prompt/Terminal/Crash logs (if existing)

```bash
C:\Users\dropf\Dropbox\Downloads\FNF-JS-Engine>source/DiscordClient.hx:82: Discord Client initialized
source/InitState.hx:29: save status: BOUND(funkin,JordanSantiago/JSEngine)
source/TitleState.hx:95: checking for update
source/TitleState.hx:108: version online: 1.32.2, your version: 1.32.2
source/TitleState.hx:115: the versions match!
source/LoadingState.hx:162: Setting asset folder to shared
source/Paths.hx:84:
source/Paths.hx:88: noteskins/NOTE_assets
source/Paths.hx:708: oh no its returning null NOOOO (assets/songs/test/Voices-dad.ogg)
source/Conductor.hx:156: new BPM map BUDDY []
source/Paths.hx:708: oh no its returning null NOOOO (assets/songs/implicit-demand-for-proof/Voices-bf.ogg)
source/Paths.hx:708: oh no its returning null NOOOO (assets/songs/implicit-demand-for-proof/Voices.ogg)
source/Paths.hx:708: oh no its returning null NOOOO (assets/songs/implicit-demand-for-proof/Voices-dad.ogg)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nop

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/6b79a96e-f271-405e-a35c-846e2db005a1)
are you sure about that?

**Comment by nxvelveteen** [comment]
this is odd

**Comment by moxie-coder** [comment]
> ![image](https://private-user-images.githubusercontent.com/61796448/361974775-6b79a96e-f271-405e-a35c-846e2db005a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDQ3NzQsIm5iZiI6MTcyNDg0NDQ3NCwicGF0aCI6Ii82MTc5NjQ0OC8zNjE5NzQ3NzUtNmI3OWE5NmUtZjI3MS00MDVlLWEzNWMtODQ2ZTJkYjAwNWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDExMjc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3OGE4ZTk2ODE5NDViMmE3MGI4NThhMmIxYWE1YmQ0OTk1M2U2NjljN2QzNmI2NmU5MmQyNmZmMmU3OGU4YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rzZ8-gdmWn9g3BLqo27splpIkfqF2S_Wz2Gfk9a1jUw) are you sure about that?

I mean there's already a check for that, and you might've not saved the file because it could be getting that from the locally saved JSON

**Comment by nxvelveteen** [comment]
hm

**Comment by nxvelveteen** [comment]
why is it trying to load from assets?

**Comment by JordanSantiagoYT** [comment]
it's not loading the vocals file from 'assets'.

**Comment by DuskDragonNight75** [comment]
Having 2 seperate vocal files doesn't work for me either, it only plays BF's vocals

**Comment by JordanSantiagoYT** [comment]
@DuskDragonNight75 what is the vocal file postfix for the opponent's vocals?
