### ISSUE TITLE
Startup Screen Bug

### ISSUE THREAD

**Issue by andrekane** [JordanSantiagoYT/FNF-JS-Engine#522]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I open the game and the startup screen appears, when it's gone, it crashes (Used Andriod Version) 

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Null Object Reference
TitleState.update() [line 332]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 552]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
None
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
This is an Android-specific issue. Report it to https://github.com/MobilePorting/FNF-JS-Engine-Mobile/issues
