### ISSUE TITLE
Norton Fricking with Engine

### ISSUE THREAD

**Issue by PDL2CGamejolt** [JordanSantiagoYT/FNF-JS-Engine#525]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I have Norton installed and if I go on ANY song, Norton detects it as a "threat" and ends the process.

https://github.com/user-attachments/assets/fd6dd9a6-1a77-474f-81f4-99926dd5c4bd

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes but not really.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
Norton is ass, I stopped using that a long time ago because it sucked ass

**Comment by Elytra-pixel** [comment]
Norton hates FNF

**Comment by PDL2CGamejolt** [comment]
I decided to try and make Norton "trust" the .exe file. I hope it works.

**Comment by PDL2CGamejolt** [comment]
> Norton hates FNF

ur probably right since I've excluded the process from Norton and also "trusted" it, yet it still crashes and thinks it's "modifying something protected by Data Protector"

**Comment by PDL2CGamejolt** [comment]
Even with Data Protector turned off it still crashes 💀
