### ISSUE TITLE
Why are most of the noteskins and note splashes gone?

### ISSUE THREAD

**Issue by RedImpostorsSon** [JordanSantiagoYT/FNF-JS-Engine#527]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

In the new update (1.32.2) they removed most of the noteskins and notesplashes, but why did this happen?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
they were removed because they aren't compatible with the new note color system.

**Comment by moxie-coder** [comment]
they were not compatible with the new color system, and they were mostly stolen assets aswell

**Comment by JordanSantiagoYT** [comment]
> and they were mostly stolen assets aswell

this was also a reason for me removing most of them, if you want them back there's a few gamebanana mods that have 0.7.x versions of MOST of the note/splash skins, you can add them back into JSE the same way as in adding to a normal psych build

HOWEVER be sure to rename `noteSkins` to `noteskins`
