### ISSUE TITLE
idk what's this, help me

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-JS-Engine#528]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I didn't saw this error before, but when I going to absolutely random song, it's just giving me this error

### Command Prompt/Terminal/Crash logs (if existing)

```bash
flixel/animation/FlxAnimationController.hx (Line 739)
Paths.hx (Line 185)
Paths.hx (Line 167)
NoteSplash.hx (Line 111)
NoteSplash.hx (Line 68)
NoteSplash.hx (Line 44)
PlayState.hx (Line 1364)
flixel/FlxGame.hx (Line 639)
flixel/FlxGame.hx (Line 726)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
open the game
start random song
error
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
Engine tried to load a note splash that doesn't exist.

**Comment by PatoFlamejanteTV** [comment]
> just open the menu and if the engine can't find the option you already have in the list it'll automatically set it to the first entry in the list

#503
