### ISSUE TITLE
how much need RAM to a load floccinaucinihilipilificatiophobia (Unnerfed) without lags?

### ISSUE THREAD

**Issue by helpmesd** [JordanSantiagoYT/FNF-JS-Engine#529]
### What is your question?

how much need RAM to a load floccinaucinihilipilificatiophobia (Unnerfed) without lags?

**Comment by JordanSantiagoYT** [comment]
unable to answer that

**Comment by PatoFlamejanteTV** [comment]
idk how many notes and what is the max nps?

**Comment by PatoFlamejanteTV** [comment]
Oh, basically, you don't need a high RAM for JS Engine, you can use a slow computer (0.5 FPS), but that will still run the song.

Btw don't ask about these things here.

**Comment by null0346** [comment]
insane skull emoji moment
