### ISSUE TITLE
still crashing when loading modded song audio files 😭 

### ISSUE THREAD

**Issue by nxvelveteen** [JordanSantiagoYT/FNF-JS-Engine#530]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

the engine is looking in the assets folder for some odd reason even though I had the mod selected and turned on

### Command Prompt/Terminal/Crash logs (if existing)

```bash
C:\Users\dropf\Dropbox\Downloads\jsengine>source/DiscordClient.hx:82: Discord Client initialized
source/InitState.hx:29: save status: BOUND(funkin,JordanSantiago/JSEngine)
source/TitleState.hx:95: checking for update
source/TitleState.hx:108: version online: 1.32.2, your version: 1.32.2
source/TitleState.hx:115: the versions match!
source/LoadingState.hx:162: Setting asset folder to shared
source/Paths.hx:84:
source/Paths.hx:88: noteskins/NOTE_assets
source/Paths.hx:708: oh no its returning null NOOOO (assets/songs/test/Voices-dad.ogg)
source/Conductor.hx:156: new BPM map BUDDY []
source/Paths.hx:708: oh no its returning null NOOOO (assets/songs/implicit-demand-for-proof/Voices-bf.ogg)
source/Paths.hx:708: oh no its returning null NOOOO (assets/songs/implicit-demand-for-proof/Voices.ogg)
source/Paths.hx:708: oh no its returning null NOOOO (assets/songs/implicit-demand-for-proof/Voices-dad.ogg)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by nxvelveteen** [comment]
twenty one pilots did not die for this

**Comment by JordanSantiagoYT** [comment]
did you DOUBLE CHECK that in your song's json, you didn't turn on "Has voice track"??

**Comment by nxvelveteen** [comment]
my song doesn't have a json saved for it, I'm trying to load the audio so I can start charting it but I did uncheck "has voice track" in the chart editor before loading

**Comment by nxvelveteen** [comment]
idk if it helps but but the difficulties for the song are Vocals, Drums, and Piano

**Comment by moxie-coder** [comment]
> idk if it helps but but the difficulties for the song are Vocals, Drums, and Piano

![image](https://github.com/user-attachments/assets/f4009126-957a-4f65-92ce-a93de2a5f450)

did you modify the game in anyway to add those difficulties?

**Comment by nxvelveteen** [comment]
> > idk if it helps but but the difficulties for the song are Vocals, Drums, and Piano
> 
> ![image](https://private-user-images.githubusercontent.com/124418090/363490621-f4009126-957a-4f65-92ce-a93de2a5f450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzY0NTksIm5iZiI6MTcyNTIzNjE1OSwicGF0aCI6Ii8xMjQ0MTgwOTAvMzYzNDkwNjIxLWY0MDA5MTI2LTk1N2EtNGY2NS05MmNlLWE5M2RlMmE1ZjQ1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwMDE1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzRhYmFlYWJiZGNjM2ViMDMwMzY1ZDU2ZjA4NTQwMzU1YmU0YTdiZTNlZWE5MWJhMmI2Yjk1NDcxNDkwMDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pZQiKfhkxeGBABChxfZjGKBdxnHQjKhSKhrYJS0KLGU)
> 
> did you modify the game in anyway to add those difficulties?

I typed those difficulties into the week editor but idk if that counts

**Comment by nxvelveteen** [comment]
the same thing happens in psych engine too so idk

**Comment by PatoFlamejanteTV** [comment]
Send your mod to me and I will help (trying) to fix, probally it's just an goofy voice glitch

**Comment by PatoFlamejanteTV** [comment]
wait why is that loading two songs?
> assets/songs/test/Voices-dad.ogg
> assets/songs/implicit-demand-for-proof/Voices-bf.ogg

**Comment by PatoFlamejanteTV** [comment]
> the same thing happens in psych engine too so idk

Ok, probably is a problem with the audio's metadata, did you have the audio? Can you send a link for testing purposes?

**Comment by PatoFlamejanteTV** [comment]
Closed due to author's inactivity...

**Comment by nxvelveteen** [comment]
> Closed due to author's inactivity...

Sorry for not responding I didn't notice the reply
I'll send the files in a bit

**Comment by nxvelveteen** [comment]
Here just have the mod folder https://www.mediafire.com/folder/1neaak179efol/FNF+x+TOP

**Comment by moxie-coder** [comment]
> wait why is that loading two songs?
> 
> > assets/songs/test/Voices-dad.ogg
> > assets/songs/implicit-demand-for-proof/Voices-bf.ogg

opponent vocals & bf vocals

**Comment by nxvelveteen** [comment]
@PatoFlamejanteTV I sent a link to the mod folder

**Comment by nxvelveteen** [comment]
> > the same thing happens in psych engine too so idk
> 
> Ok, probably is a problem with the audio's metadata, did you have the audio? Can you send a link for testing purposes?
After some testing it did in fact turn out the a problem with the audio. I put the audio in FL Studio then exported it and know it works just fine! Tysm
