### ISSUE TITLE
Stuck in Botplay when disabled

### ISSUE THREAD

**Issue by Ashi-Blaber** [JordanSantiagoYT/FNF-JS-Engine#531]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

So I'm playing any song, and no matter what, bot-play is enabled. I disable it, and it's still on bot-play! Any idea on how to fix this?
![Screenshot 2024-09-01 123939](https://github.com/user-attachments/assets/ff33f24c-d3f8-425e-ac3c-5e4724612148)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
make sure showcase mode isn’t on

**Comment by Ashi-Blaber** [comment]
tyty

**Comment by moxie-coder** [comment]
> tyty

np
