### ISSUE TITLE
I tried playing soulless 1-6 mod but it keeps crashing when i load a song can someone know how to fix this?

### ISSUE THREAD

**Issue by FunkinFridayDude** [JordanSantiagoYT/FNF-JS-Engine#532]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

PlayState.hx (Line 7422)
PlayState.hx (Line 6245)
PlayState.hx (Line 5772)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
![Screenshot (32)](https://github.com/user-attachments/assets/fba9cebc-4ef7-462f-a801-93acf133d9e5)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Yes i have identified any steps to help the bug try to being fixed.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by FunkinFridayDude** [comment]
It said it was an unknown issue and i came here to report.

**Comment by JordanSantiagoYT** [comment]
what version of JS Engine is this?

**Comment by FunkinFridayDude** [comment]
Sorry that I inturrupted but now It seems like the issue has been fixed sorry if i wasted ur time.

**Comment by JordanSantiagoYT** [comment]
oof-

that's fine LOL

**Comment by FunkinFridayDude** [comment]
Alr have an good day
