### ISSUE TITLE
Bizarre bug that stretches the notes

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#533]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Hi, I was testing my new character in a song from my existing mod, when the notes began to "stretch" randomly, for some reason this only happens when I test using the "ESC mode." (When you press "7" and then "Esc.")

https://github.com/user-attachments/assets/871b92ee-7e59-40d5-b69a-ae02ad70a4cc

### Command Prompt/Terminal/Crash logs (if existing)

```bash
None.
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
7 > Esc.

Btw my .JSON chart download is on github: https://github.com/PatoFlamejanteTV/ImaturidadePlusPlus/blob/main/data/roblox/roblox.json
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
I've already detected and fixed this issue in a later commit.
