### ISSUE TITLE
JS Engine : what

### ISSUE THREAD

**Issue by SyncGit12** [JordanSantiagoYT/FNF-JS-Engine#534]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

source/backend/CoolUtil.hx:45: characters 19-23 : String has no field trim
source/backend/CoolUtil.hx:48: characters 26-30 : String has no field trim
source/backend/CoolUtil.hx:34: characters 54-58 : String has no field trim
source/backend/CoolUtil.hx:35: characters 12-22 : String has no field startsWith
source/backend/CoolUtil.hx:114: characters 20-27 : String has no field replace
source/backend/CoolUtil.hx:115: characters 14-22 : String has no field endsWith
source/backend/CoolUtil.hx:148: characters 31-35 : String has no field trim
source/backend/ClientPrefs.hx:81: characters 47-48 : Unexpected ;

### Command Prompt/Terminal/Crash logs (if existing)

```bash
source/backend/CoolUtil.hx:45: characters 19-23 : String has no field trim
source/backend/CoolUtil.hx:48: characters 26-30 : String has no field trim
source/backend/CoolUtil.hx:34: characters 54-58 : String has no field trim
source/backend/CoolUtil.hx:35: characters 12-22 : String has no field startsWith
source/backend/CoolUtil.hx:114: characters 20-27 : String has no field replace
source/backend/CoolUtil.hx:115: characters 14-22 : String has no field endsWith
source/backend/CoolUtil.hx:148: characters 31-35 : String has no field trim
source/backend/ClientPrefs.hx:81: characters 47-48 : Unexpected ;
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
haxe n'stuff
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

working on mod

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
you need to show what you changed, because I can’t see what you changed

**Comment by SyncGit12** [comment]
look on The-VS-Nothing-Crew/VsNothing

**Comment by moxie-coder** [comment]
> look on The-VS-Nothing-Crew/VsNothing

alright

**Comment by SyncGit12** [comment]
specially commit history

**Comment by JordanSantiagoYT** [comment]
from what i can see you literally just merged jse and pe 0.7

**Comment by SyncGit12** [comment]
wdym

**Comment by JordanSantiagoYT** [comment]
> wdym
> 
> im fucking dealing with the most stupidest shit ever

you put the 0.7 source inside a jse source

**Comment by SyncGit12** [comment]
![image](https://github.com/user-attachments/assets/139dc2d2-ef82-474d-ba2f-f4c6f29398ea)

yay

**Comment by Stefan2008Git** [comment]
> ![image](https://private-user-images.githubusercontent.com/144155299/364073202-139dc2d2-ef82-474d-ba2f-f4c6f29398ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NTcwNTMsIm5iZiI6MTcyNTc1Njc1MywicGF0aCI6Ii8xNDQxNTUyOTkvMzY0MDczMjAyLTEzOWRjMmQyLWVmODItNDc0ZC1iYTJmLWY0YzZmMjkzOThlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwMDUyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjViNDE5ZWIzMjlkYTIyOTdiZjcyMjBiYmM4NjE0ZGQ0MzVhNDhjMjE2MDNlZmExY2I1ZjQxNzdkMjgzNzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1b4GO-BQ0DTTgXa7UwuNf6CVcxJVWzHjRzM_Lnt2k58)
> 
> yay
> 
> moral of the 2 last issues:
> 
> never merge psych 0.7 with jse.
> 
> go to hell, shadowmario.

That's really rude buddy. You are just blaming the Shadow Mario for one thing that is easily to fix and plus you are probably happy how Psych 1.0 will be the latest Psych Engine version ever made since Shadow Mario is tired from FNF and he cannot handle it anymore, so that's sad for PE users. Probably is R.I.P Psych Engine very soon @moxie-coder @JordanSantiagoYT

**Comment by SyncGit12** [comment]
do you realize how unoptimized is psych than js engine

like i want to play fnf in a fucking bad pc

lags a fucking lot

js:

no lag

dude just use js not psych

**Comment by Stefan2008Git** [comment]
> do you realize how unoptimized is psych than js engine
> 
> like i want to play fnf in a fucking bad pc
> 
> lags a fucking lot
> 
> js:
> 
> no lag
> 
> dude just use js not psych

You just have a bad PC with old CPU and GPU and probably 4GB of RAM, so just switch to Linux

Psych isn't unoptimized, it was your your PC

**Comment by moxie-coder** [comment]
> do you realize how unoptimized is psych than js engine
> 
> like i want to play fnf in a fucking bad pc
> 
> lags a fucking lot
> 
> js:
> 
> no lag
> 
> dude just use js not psych

it ain't my fault that your pc can't run psych engine, this engine is basically psych but just more bloated, so I expect it to perform the same

**Comment by SyncGit12** [comment]
performs better than psych

**Comment by SyncGit12** [comment]
> > do you realize how unoptimized is psych than js engine
> > like i want to play fnf in a fucking bad pc
> > lags a fucking lot
> > js:
> > no lag
> > dude just use js not psych
> 
> You just have a bad PC with old CPU and GPU and probably 4GB of RAM, so just switch to Linux
> 
> Psych isn't unoptimized, it was your PC

16.0 GB (15.9 GB usable)
Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz   1.99 GHz

2017 pc

**Comment by PatoFlamejanteTV** [comment]
i3 in 2024 is crazy bro 💀

**Comment by SyncGit12** [comment]
seriously true im rocking a amd cpu now
