### ISSUE TITLE
how do you reset settings

### ISSUE THREAD

**Issue by Buateds2** [JordanSantiagoYT/FNF-JS-Engine#535]
### What is your question?

it literally says nothing and crashes omfg help

**Comment by JordanSantiagoYT** [comment]
you're supposed to press R

**Comment by Buateds2** [comment]
my js engine crashes no matter what. i checked EVERYTHING, didn't use custom characters, only bf & gf in the chart but IT KEEPS CRASHING and all of the files the icons, character .jsons, the instrumental spritesheet you name it IT KEEPS CRASHING NO MATTER WHAT. i've been trying to run a song for the last 2 days and it keeps crashing. try disabling Chars & BG? no. fuck it turn off show notes STILL NO please just help

**Comment by Buateds2** [comment]
i'm legit about to factory reset my pc to a whole different version of windows to solely just use this engine

**Comment by JordanSantiagoYT** [comment]
i actually don't know what to do, maybe reinstall JSE?

also don't literally reset your whole pc just to use i

**Comment by Buateds2** [comment]
yeaaaa guess what i did 4 times

**Comment by Buateds2** [comment]
tried this on multiple different versions of JSE and it crashes on those too. note: i reset my settings through the appdata folder every attempt

**Comment by JordanSantiagoYT** [comment]
does 1.30.0 or lower actually show a crash log??

**Comment by moxie-coder** [comment]
that would help if we could see why it's crashing

**Comment by Buateds2** [comment]
> does 1.30.0 or lower actually show a crash log??
i think so, let me try porting the mod to 1.30.0 and send the crashlog

**Comment by Buateds2** [comment]
even if 1.30.0 is slower i'm going to stick to this cuz i can't even run a song without crashing on 1.32 (also i failed to get any crash logs sry)

**Comment by Buateds2** [comment]
now i'm going to be trying on 1.33 and 1.31

**Comment by Buateds2** [comment]
yeah it keeps crashing also on 1.33 and that also leaves absolutely NO crash logs

**Comment by Buateds2** [comment]
![image](https://github.com/user-attachments/assets/c0b95132-7906-4f3c-a841-071f58885053)
I FINALLY GOT ONE

**Comment by JordanSantiagoYT** [comment]
try with https://github.com/JordanSantiagoYT/FNF-JS-Engine/actions/runs/10744863863

**Comment by Buateds2** [comment]
![image](https://github.com/user-attachments/assets/11457909-9b88-43f0-bf2a-98bacea1d759)

**Comment by JordanSantiagoYT** [comment]
Engine tried to initialize a note splash configuration file that doesn't exist.

**Comment by moxie-coder** [comment]
> soo what do i have to change?

make a config file in note splash editor

**Comment by Buateds2** [comment]
alright here we go note splash editor crashes without any error message too

**Comment by moxie-coder** [comment]
> alright here we go note splash editor crashes without any error message too

if you’re not using the latest version do that since I fixed the bug

**Comment by Buateds2** [comment]
alright

**Comment by Buateds2** [comment]
![image](https://github.com/user-attachments/assets/a01823e9-75bc-44d1-8fcc-9888cef8f0ca)
ok so the left key is 3,nan

**Comment by Buateds2** [comment]
OK NEVERMIND I DID IT IT WORKS

**Comment by moxie-coder** [comment]
> OK NEVERMIND I DID IT IT WORKS

glad I could help

**Comment by Buateds2** [comment]
ty, also one question how do you get the text in the middle like in jordan's uploads

**Comment by moxie-coder** [comment]
what text exactly?

**Comment by Buateds2** [comment]
https://www.youtube.com/watch?v=Ny42VFoBuI8&
the one that's like
0/0
NPS: 832/2923
Opp NPS: 824/2934

**Comment by Buateds2** [comment]
ok i managed to do it
