### ISSUE TITLE
How do I enable the "Perfect!!!" Rating thing?

### ISSUE THREAD

**Issue by RedImpostorsSon** [JordanSantiagoYT/FNF-JS-Engine#536]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

It just gives me Sick, Good, Bad, and Shit?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/4a647fb8-a954-471d-88df-436bf039f23d)
disable this option

**Comment by RedImpostorsSon** [comment]
It's disabled. but still doesn't work

**Comment by JordanSantiagoYT** [comment]
does the rating counter not show the perfect judgement??

**Comment by RedImpostorsSon** [comment]
it does but I never get the perfect judgement.

**Comment by JordanSantiagoYT** [comment]
can you show me your rating judgement windows

**Comment by moxie-coder** [comment]
I've not really had any problems with it from what I know

**Comment by PatoFlamejanteTV** [comment]
can you show an recording or something? its showing an small haxe logo(<img src="https://github.com/user-attachments/assets/857758ed-dfe3-46cb-b261-e9f330343995" width="20" />)?

**Comment by RedImpostorsSon** [comment]
Here is a video I made of a chart I made and you can see that there is no perfects https://www.youtube.com/watch?v=h5rBqevzZL4&t=282s
