### ISSUE TITLE
adding custom note splashes are so broken in game

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#540]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

https://github.com/user-attachments/assets/d35fc464-e8cf-4f7e-898e-8b21fb30caf1

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

fasdfasdfafgasAAAAAAASFSDGAWEGTSDFGGGGGGGGGGGGGG

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
btw you have to position the splashes correctly using the note splash editor

**Comment by moxie-coder** [comment]
> btw you have to position the splashes correctly using the note splash editor

oh yeah true

**Comment by daveandbambifan1234** [comment]
> btw you have to position the splashes correctly using the note splash editor

all right when I fix the offsets of the note splashes can you fix the note Splash bug itself(if you can)

**Comment by daveandbambifan1234** [comment]
> if it's made for an older version, it might have issues with offsets

also I put it in the right folder + I use 0.7.3 note splashes
