### ISSUE TITLE
i think i did a fucky wucky on the chart editor time

### ISSUE THREAD

**Issue by TommykairaXVI** [JordanSantiagoYT/FNF-JS-Engine#542]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

![image](https://github.com/user-attachments/assets/4d9e2b7e-4180-433e-8a43-466e7a17a254)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
i messed with the timebar and it fucks up like this lol
this is the wierdest bug i've discovered, minus two days!? did i break the matrix!?!!!





what the sigma
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

modcor :)

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
did you make sure you placed your audio files in the right place?

**Comment by TommykairaXVI** [comment]
> did you make sure you placed your audio files in the right place?

yea they are in the right place, i just messed with the timebar and ended up clitching like this, (it only happened once)

**Comment by StinkTheStinker** [comment]
going off topic, what the fuck is the name

**Comment by TommykairaXVI** [comment]
> going off topic, what the fuck is the name

_**yehs**_

**Comment by PatoFlamejanteTV** [comment]
I got a similar result when I tested Cheat Engine and some corrupt files.

**Comment by PatoFlamejanteTV** [comment]
I will close the issue because it is impossible to replicate it, because according to the author, it only happened once

>yea they are in the right place, i just messed with the timebar and ended up clitching like this, (it only happened once)
