### ISSUE TITLE
it doesn't save properly

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#543]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

![image](https://github.com/user-attachments/assets/de9d76ec-6243-4f7b-99a8-21a48f4d94b5)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
a
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
a
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

a

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
CAUSE OF PROBLEM HAS BEEN FOUND!!!

apparently i forgot to remove the redAnim save thing when i ported the note splashes to the new system, so any time you save it would add redAnim to the config file. however, because that doesn't exist anymore the game treats it like offsets and it breaks

**Comment by JordanSantiagoYT** [comment]
fixed in latest commit
