### ISSUE TITLE
What happen to "long ass health bar" 

### ISSUE THREAD

**Issue by The96rf** [JordanSantiagoYT/FNF-JS-Engine#547]
### What feature do you want to get added on the **base** engine?

I'm so used to the long bar that now I find the normal bar wierd
Can you add it back

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by moxie-coder** [comment]
1. wrong template
2. it was removed because it could be easily recreated in lua
3. No

**Comment by The96rf** [comment]
How?

**Comment by JordanSantiagoYT** [comment]
> How?

you could easily replicate it by putting 'longHealthBar.png' in your mods/images folder and renaming it to 'healthBar.png'
