### ISSUE TITLE
Note RGB stuff doesn't turn off for regular notes.

### ISSUE THREAD

**Issue by DuskDragonNight75** [JordanSantiagoYT/FNF-JS-Engine#548]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

So I tried turning off the note RGB in the visuals and ui settings, and then disabling note RGB in the chart, and it seems to work... but for everything except the actual notes.
![urgggnotesbad](https://github.com/user-attachments/assets/c619938f-e5e8-4d1e-8302-5167c3fc7d11)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
None
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Well, I've already kinda explained it.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
did you disable the note colors in visuals & ui options?

**Comment by KernelTech11** [comment]
try using [this](https://www.mediafire.com/file/y80h166qafjc68v/rgb+script.lua/file?dkey=fr0cvmtdj9n&r=1668)

**Comment by moxie-coder** [comment]
I've had someone else with the same problem, so I'm gonna assume you forgot to turn off an option

**Comment by DuskDragonNight75** [comment]
> Collaborator

yep, turned it off

**Comment by moxie-coder** [comment]
> > Collaborator
> 
> yep, turned it off

did it fix the problem?
