### ISSUE TITLE
Black frames in video and in rendered frames

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#551]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Hi! I was making an joke chart, and when i rendered, i noticed some black frames in the video, is this normal?

![image](https://github.com/user-attachments/assets/b8961954-5ab2-45de-b18c-232053f5df31)
![image](https://github.com/user-attachments/assets/e326a71a-85e0-40d1-8a4f-e99a4dda6c59)
 I removed the frames from the exported video using this command i found [here, on the Stack Exchange forums](https://video.stackexchange.com/questions/23589/replace-black-frames-with-previous-frames):

```
ffmpeg -i in.mp4 -vf blackframe=0,metadata=select:key=lavfi.blackframe.pblack:value=50:function=less -vsync cfr -c:a copy out.mp4
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Used classic rendering mode
120 FPS
JPG Quality = 50
> Selected song
> Waited
> Exported
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i an using the latest release from the official JS Engine Github repo.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by PatoFlamejanteTV** [comment]
Btw i cant upload the videos here because of the videos size (**195 MB**, **144 MB**).

**Comment by JordanSantiagoYT** [comment]
Black frames are unfixable as far as i can tell

**Comment by moxie-coder** [comment]
> Black frames are unfixable as far as i can tell

this could be an issue with how the screenshots are taken from what I see

**Comment by PatoFlamejanteTV** [comment]
Okay, I found that when my computer semi-"crashes" during rendering (screen turns white, but backs in half a second), it generates a "black frame".

Using a smaller framerate helps "generate less", but still, there is a chance of 1 in 100 of generating this "black frame"

**Comment by FuseIsHere813** [comment]
@PatoFlamejanteTV possible typo?
![image](https://github.com/user-attachments/assets/f787b84e-5a0a-4d7b-b124-c53967030306)

**Comment by PatoFlamejanteTV** [comment]
oh, sorry

> @PatoFlamejanteTV possible typo? ![image](https://private-user-images.githubusercontent.com/77396398/367525715-f787b84e-5a0a-4d7b-b124-c53967030306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjg0NjMsIm5iZiI6MTcyNjMyODE2MywicGF0aCI6Ii83NzM5NjM5OC8zNjc1MjU3MTUtZjc4N2I4NGUtNWEwYS00ZDdiLWIxMjQtYzUzOTY3MDMwMzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE1MzYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhM2IyMjA5YjE4NWIyNzNlMmQwODM4ZjUyNDFmYWZkMjJhZGFlYTMwYzE0YzliZDZlYjVlNzYyNjU5ODU4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DMXLe17QXHon-m1kS4jNM4xAM9s3fvw7wselZKeD6Bw)
> 
> edit: in "platform"
