### ISSUE TITLE
crash after loading a song

### ISSUE THREAD

**Issue by TommykairaXVI** [JordanSantiagoYT/FNF-JS-Engine#552]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

![2024-09-08_11-36-15](https://github.com/user-attachments/assets/dba96339-609c-4f7d-a5ad-dc5ee62df630)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
flixel/animation/FlxAnimationController.hx (Line 739)
Paths.hx (Line 185)
Paths.hx (Line 167)
NoteSplash.hx (Line 111)
NoteSplash.hx (Line 68)
NoteSplash.hx (Line 44)
PlayState.hx (Line 1387)
flixel/FlxGame.hx (Line 639)
flixel/FlxGame.hx (Line 726)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
i just clicked on a skibidi song and this ligma of a crash crashed the sigma engine
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

modcor

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
you’re missing a note splash config file

**Comment by TommykairaXVI** [comment]
nevermind i have 3 js engines with different versions, i modified my notes on the newer ones and saves it in the appdata folder. and when i load any song on older ones, the appdata folder of js engine doesnt detect the chosen noteskin so it crashes.
