### ISSUE TITLE
i hate this so much

### ISSUE THREAD

**Issue by Buateds2** [JordanSantiagoYT/FNF-JS-Engine#553]
### What is your question?

WHAT IS THAT TIME TAKEN THING
![image](https://github.com/user-attachments/assets/8020d763-e2c4-4383-bca5-378f4f1c1d8d)
KILL IT WITH FIRE

**Comment by moxie-coder** [comment]
That’s for rendering mode

**Comment by JordanSantiagoYT** [comment]
me when i cant set Info Shown: to "None":

**Comment by PatoFlamejanteTV** [comment]
https://github.com/user-attachments/assets/d6f56e44-83de-43bc-971e-4596625c41cd
