### ISSUE TITLE
I update JS Engine but it stopped on 83% 0B/s - 0-2147483648 : 0-2147483648 : 0-2147483648 reaming

### ISSUE THREAD

**Issue by helpmesd** [JordanSantiagoYT/FNF-JS-Engine#554]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

im not modding

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by helpmesd** [comment]
i found how it fix just reload game

**Comment by PatoFlamejanteTV** [comment]
I had the same issue, but that just disappeared (idk if was patched)
