### ISSUE TITLE
BUG ALERT!!!!🚨🚨🚨🚨

### ISSUE THREAD

**Issue by KernelTech11** [JordanSantiagoYT/FNF-JS-Engine#555]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

i tried to chart High (Beta version/Live vocal version) by DaThugWizard and when i tried to put a note in mommy mearest's side my game just decided to crash
![Captura de tela 2024-09-08 125156](https://github.com/user-attachments/assets/0c03f1e3-5497-4810-a3b3-8ddb77f86715)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Uncaught Error: Null Object Reference
Note.updateRGBColors() [line 536]
editors/ChartingState.addNote() [line 4036]
editors/ChartingState.update() [line 2551]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didnt edit anything

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
btw, don't use Char-Based note colors in the Chart Editor (unless you go into PlayState, then in the editor again) otherwise.. you'll crash

just wanted to say that because that's related to what line the game is referencing in the code

**Comment by PatoFlamejanteTV** [comment]
I know this is closed, but why is the title **BUG ALERT!!!!🚨🚨🚨🚨** instead of something like "glitch when chart"

**Comment by KernelTech11** [comment]
> I know this is closed, but why is the title **BUG ALERT!!!!🚨🚨🚨🚨** instead of something like "glitch when chart"

it's because it would be """"""""""""""""REALLY"""""""""""""""" flashy

**Comment by PatoFlamejanteTV** [comment]
> > I know this is closed, but why is the title **BUG ALERT!!!!🚨🚨🚨🚨** instead of something like "glitch when chart"
> 
> it's because it would be """"""""""""""""REALLY"""""""""""""""" flashy

... so put an "epilepsy warning" idk

**Comment by KernelTech11** [comment]
> > > I know this is closed, but why is the title **BUG ALERT!!!!🚨🚨🚨🚨** instead of something like "glitch when chart"
> > 
> > 
> > it's because it would be """"""""""""""""REALLY"""""""""""""""" flashy
> 
> ... so put an "epilepsy warning" idk

i didn't meant that, i meant like catchy
