### ISSUE TITLE
Teleporting notes when charting

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#557]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Hi, I was trying to chart a random song, but then the notes were “teleporting”.
It's hard to explain, I recorded the glitch btw.

https://github.com/user-attachments/assets/f077a135-d10d-4e86-b7ec-599e0d84f4f9

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
> Pressed "7" in the home screen
> Selected "Chart Editor"
> Used the Ez Spam module
> boom

> Unselected
> Dint changed nothing

> Selected again
> Dint changed nothing

> Panik.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I am using the latest release from JS.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by PatoFlamejanteTV** [comment]
**More recordings about this glitch:**
_(sorry if the recording is at a horrible resolution, i had also to speed up because of the 10MB limit)_

https://github.com/user-attachments/assets/9ba0b10c-76eb-47da-8e77-fcbb5dd7a364

**Comment by PatoFlamejanteTV** [comment]
**EDIT: i "fixed" this by _closing and opening again the JSE._**

https://github.com/user-attachments/assets/65c1bed6-e381-4d55-8774-3afd73faed28

**Comment by moxie-coder** [comment]
> **More recordings about this glitch:** _(sorry if the recording is at a horrible resolution, i had also to speed up because of the 10MB limit)_
> 
>  bandicam.2024-09-09.16-37-29-803.online-video-cutter.com.mp4

you could've uploaded it on google drive

**Comment by JordanSantiagoYT** [comment]
that's.. because you set the beat snap to 4th, you change it by pressing the left/right arrow keys
![image](https://github.com/user-attachments/assets/7b286875-894b-4d1d-9bae-a28f1aa25da4)

**Comment by moxie-coder** [comment]
> that's.. because you set the beat snap to 4th, you change it by pressing the left/right arrow keys ![image](https://private-user-images.githubusercontent.com/61796448/365818042-7b286875-894b-4d1d-9bae-a28f1aa25da4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTgwNzAsIm5iZiI6MTcyNTkxNzc3MCwicGF0aCI6Ii82MTc5NjQ0OC8zNjU4MTgwNDItN2IyODY4NzUtODk0Yi00ZDFkLTliYWUtYTI4ZjFhYTI1ZGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDIxMzYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMDU5OGE1NWI0NDZkZjE1YTFmM2RmM2NiMmFiMWY1MDUxNzYyYTg1NmZiN2U1MmQ3YTMzM2FhOTQzZjg1NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OFZQLqNMG_8Ya2pfRBzscwFTjK8acewN6dm092_ijTY)

I didn't even see that lol
