### ISSUE TITLE
idk whats the reason but i know that it is the notes

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#559]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

a

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Uncaught Error: Null Object Reference
Paths.initSplash() [line 128]
NoteSplash.loadAnims() [line 116]
NoteSplash.setupNoteSplash() [line 63]
NoteSplash.new() [line 44]
PlayState.create() [line 1205]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.update() [line 726]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
a
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

probably the noteskins and splashes is the cause

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by daveandbambifan1234** [comment]
fixed it, it used the older Js engine chart thingy

**Comment by moxie-coder** [comment]
missing note splash config file

**Comment by daveandbambifan1234** [comment]
> you're missing your note splash config file

i fixed it alr

**Comment by moxie-coder** [comment]
Ok

**Comment by JordanSantiagoYT** [comment]
does anyone think it emails this guy automatically whenever someone makes a duplicate of this issue? (when it's marked as one ofc)

**Comment by moxie-coder** [comment]
> does anyone think it emails this guy automatically whenever someone makes a duplicate of this issue? (when it's marked as one ofc)

it doesn’t

**Comment by JordanSantiagoYT** [comment]
To anyone who is checking this, the note splash config for your skin is mising. to fix your issue currently try changing the note splash to "Vanilla" or messing with the engine to make a config file for your splash skin

**Comment by JordanSantiagoYT** [comment]
this should help people find this issue, if they check for dupes

..please?
