### ISSUE TITLE
bugy hurtnote

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#561]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

when I haven't clicked any hurt notes at all it still makes me lose Health. please fix this

### Command Prompt/Terminal/Crash logs (if existing)

```bash
a
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
a
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no source code was modded. I only added characters, scripts, songs, noteskins

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
Can you be more specific?

**Comment by JordanSantiagoYT** [comment]
??

https://github.com/user-attachments/assets/e79aa8e7-5115-4b65-b98e-1e5cd7fc3d14

**Comment by daveandbambifan1234** [comment]
when I click normal notes and not the hurtnotes it still makes me lose health no matter what

Uploading 8mb.video-BBB-AKf13547.mp4…

**Comment by daveandbambifan1234** [comment]
https://github.com/user-attachments/assets/38efa3e0-0a98-4d71-aec0-07eaf9bf5075

**Comment by JordanSantiagoYT** [comment]
probably not the best example video to show.. you missed a normal note at the same time you missed the hurt note

**Comment by moxie-coder** [comment]
plus you skipped through the song too, and it had fast note speed too

**Comment by daveandbambifan1234** [comment]
> probably not the best example video to show.. you missed a normal note at the same time you missed the hurt note

can you fix me issue and remove this bug because it's a really weird bug

**Comment by JordanSantiagoYT** [comment]
https://github.com/user-attachments/assets/24eed02a-99df-4228-9cac-ae781a7f7e57

**Comment by moxie-coder** [comment]
I can’t help fix something that you provided a bad example of

**Comment by moxie-coder** [comment]
> 2024-09-10.20-15-28.mp4

yeah I’m just beginning to think this is just a skill issue

**Comment by JordanSantiagoYT** [comment]
oh
https://github.com/user-attachments/assets/aa5088a6-bc35-4823-8fe8-b33f0b04833a

**Comment by moxie-coder** [comment]
> oh
> 
>  2024-09-10.20-17-22.mp4

nvm what I said then

**Comment by daveandbambifan1234** [comment]
I used the scroll speed 3.5 BTW

**Comment by daveandbambifan1234** [comment]
I'm just going to remove the hurt notes from the chart and wait for the next update

**Comment by PatoFlamejanteTV** [comment]
Real vro, the notes are very bugy and crasy
