### ISSUE TITLE
about the v0.5 FNF update

### ISSUE THREAD

**Issue by FuseIsHere813** [JordanSantiagoYT/FNF-JS-Engine#565]
### What is your question?

are y'all planning to add the new pico mixes from the base FNF into the next js engine update? it's like how the erect songs were added in js engine.

btw official ugh erect dropped too

**Comment by moxie-coder** [comment]
probably, but honestly I was hoping that Psych 1.0 would have updated to either 0.3, 0.4, or better 0.5

**Comment by JordanSantiagoYT** [comment]
Cocoa, MILF and Ugh Erect will be added.

Pico Mixes will likely not be added.
