### ISSUE TITLE
Is a way to change the game's font?

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#567]
### What is your question?

I was modifying my computer using an application that modified the system font, until it gave me the idea of ​​changing the JS Engine font. Is there any way to modify this? Or, is there any way to modify this without hard-coding that in the engine?

**Comment by PatoFlamejanteTV** [comment]
Btw, I want to insert the **Inconsolata** font, a monospaced font.

**Comment by einbuis07** [comment]
did you check game folders and find fonts folders? (i'm not admin,.)

**Comment by JordanSantiagoYT** [comment]
to change the main font, you could try making a `fonts` folder inside assets or `mods` and placing your font in there as `vcr.ttf`.

**Comment by PatoFlamejanteTV** [comment]
> to change the main font, you could try making a `fonts` folder inside assets or `mods` and placing your font in there as `vcr.ttf`.

Thanks! That worked :D
