### ISSUE TITLE
Dumb Idea for chart editor

### ISSUE THREAD

**Issue by einbuis07** [JordanSantiagoYT/FNF-JS-Engine#569]
### What feature do you want to get added on the **base** engine?

i have a very dumb idea... or good?
Dumb idea/good idea: Add Button "Automatic spam chart" that generates spam chart automaticly

> IT'S VERY DUMB IDEA OH MY...

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by JordanSantiagoYT** [comment]
Failed the test, and also this is not something that can be implemented

**Comment by einbuis07** [comment]
> Failed the test, and also this is not something that can be implemented

Oh.. ok.. I think it was good idea but nothing bad. 😊

**Comment by moxie-coder** [comment]
> ### What feature do you want to get added on the **base** engine?
> i have a very dumb idea... or good? Dumb idea/good idea: Add Button "Automatic spam chart" that generates spam chart automaticly
> 
> > IT'S VERY DUMB IDEA OH MY...
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Proper credit that was forgotten

not doing this no

**Comment by FuseIsHere813** [comment]
> ### What feature do you want to get added on the **base** engine?
> i have a very dumb idea... or good? Dumb idea/good idea: Add Button "Automatic spam chart" that generates spam chart automaticly
> 
> > IT'S VERY DUMB IDEA OH MY...
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Proper credit that was forgotten

this is most likely an ai generated reference 💀

**Comment by moxie-coder** [comment]
I just realized how AI generated that feels like lmao
