### ISSUE TITLE
the hurtnote bug is even way worse then before

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#570]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

https://github.com/user-attachments/assets/f0cc300d-eb6e-4cad-9d3c-9277fb7c4642

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

none

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by daveandbambifan1234** [comment]
btw, I did not click the hurt notes at all in the video I just pressed the normal notes and I for some reason lost health

**Comment by daveandbambifan1234** [comment]
https://github.com/user-attachments/assets/7c00047f-f4de-45e1-8311-4269eab08704

💀

**Comment by daveandbambifan1234** [comment]
anyone going to respond to any moment now?

**Comment by daveandbambifan1234** [comment]
> anyone going to respond at any moment now?

**Comment by daveandbambifan1234** [comment]
anyone going to respond at any moment now? /:

**Comment by PatoFlamejanteTV** [comment]
what i cant play the video

![image](https://github.com/user-attachments/assets/5c6135f3-91b0-49fa-b581-8c631ac024f3)

**Comment by PatoFlamejanteTV** [comment]
I think it's something with the note's speed

**Comment by JordanSantiagoYT** [comment]
This has already been fixed.

https://github.com/user-attachments/assets/b0965af2-6ceb-4200-9110-0cd311808e4f

**Comment by daveandbambifan1234** [comment]
> This has already been fixed.
> 
>  2024-09-14.10-27-32.mp4

WHAT?
I probably just have a shitty computer

**Comment by daveandbambifan1234** [comment]
plus I'm using the most current version of the engine

**Comment by JordanSantiagoYT** [comment]
Hellooooooooooooooooo?? You're not using the most recent action build. https://github.com/JordanSantiagoYT/FNF-JS-Engine/actions/runs/10863966223/artifacts/1933389308

**Comment by Stefan2008Git** [comment]
"Kid who loves Dave and Bambi mod so much and still report same engine bugs when Jordan already fixed them" ahh situation

**Comment by PatoFlamejanteTV** [comment]
All daveandbambifan1234 posts are brainrot wth

**Comment by Stefan2008Git** [comment]
> All daveandbambifan1234 posts are brainrot wth

He is just a kid, that's all what you can tell and yeah, he is probably watching the brainrot LMAO

**Comment by PatoFlamejanteTV** [comment]
> > All daveandbambifan1234 posts are brainrot wth
> 
> He is just a kid, that's all what you can tell and yeah, he is probably watching the brainrot LMAO

Bro, EVERY POST HE DOES HAVE SOMETHING RANDOM, or the glitch is "i", or the issue title is "why did you have to do that", btw ik he is a child, I'm not attacking him any way, i just think hes funny.

**Comment by FuseIsHere813** [comment]
@PatoFlamejanteTV 
![image](https://github.com/user-attachments/assets/a1b8a6ae-0453-4523-a3d2-242170713298)

sorry, more typos

"probably", "8 year old"

**Comment by PatoFlamejanteTV** [comment]
> @PatoFlamejanteTV ![image](https://private-user-images.githubusercontent.com/77396398/367609649-a1b8a6ae-0453-4523-a3d2-242170713298.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTQyMTksIm5iZiI6MTcyNjU5MzkxOSwicGF0aCI6Ii83NzM5NjM5OC8zNjc2MDk2NDktYTFiOGE2YWUtMDQ1My00NTIzLWEzZDItMjQyMTcwNzEzMjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE3MjUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZDdmYTg4ZGFkOWVjNWU1ZmQ2YzAxNmZkMDc3NmJlZGZlZjRlMmIxNzQ1ZjRlYWZhMGRiM2UwNWI1Mzg3Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztLlijDqoTKQO4PfBtQpWbs3BZajAkpoVLrg7QbfSGg)
> 
> sorry, more typos
> 
> "probably", "8 year old"

Sorry for the typos, I made this label (brainrot) when I was on my phone and the keyboard don't work very well. Thanks :D

**Comment by Stefan2008Git** [comment]
> > > All daveandbambifan1234 posts are brainrot wth
> > 
> > 
> > He is just a kid, that's all what you can tell and yeah, he is probably watching the brainrot LMAO
> 
> Bro, EVERY POST HE DOES HAVE SOMETHING RANDOM, or the glitch is "i", or the issue title is "why did you have to do that", btw ik he is a child, I'm not attacking him any way, i just think hes funny.

You can tell that even when Jordan made best fork, i still hate it

**Comment by FuseIsHere813** [comment]
> > @PatoFlamejanteTV ![image](https://private-user-images.githubusercontent.com/77396398/367609649-a1b8a6ae-0453-4523-a3d2-242170713298.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTQyMTksIm5iZiI6MTcyNjU5MzkxOSwicGF0aCI6Ii83NzM5NjM5OC8zNjc2MDk2NDktYTFiOGE2YWUtMDQ1My00NTIzLWEzZDItMjQyMTcwNzEzMjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE3MjUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZDdmYTg4ZGFkOWVjNWU1ZmQ2YzAxNmZkMDc3NmJlZGZlZjRlMmIxNzQ1ZjRlYWZhMGRiM2UwNWI1Mzg3Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztLlijDqoTKQO4PfBtQpWbs3BZajAkpoVLrg7QbfSGg)
> > sorry, more typos
> > "probably", "8 year old"
> 
> Sorry for the typos, I made this label (brainrot) when I was on my phone and the keyboard don't work very well. Thanks :D

You're welcome, glad that I was able to help you along with the label :)

**Comment by JordanSantiagoYT** [comment]
> You can tell that even when Jordan made best fork, i still hate it

stefan you lashed out at me for reporting bugs with your engine, plus you're homophobic; you're not much better

![image](https://github.com/user-attachments/assets/38e20657-d968-47e5-ae2d-0e563ac7aed3)

**Comment by cyklusiguess** [comment]
THEY CLOSED THE ISSUE LMFAO

**Comment by JordanSantiagoYT** [comment]
this issues been closed actually

**Comment by cyklusiguess** [comment]
oh

**Comment by cyklusiguess** [comment]
![image](https://github.com/user-attachments/assets/22657b2a-c161-4e41-ad1d-e8ec3f05822e)

**Comment by JordanSantiagoYT** [comment]
he probably edited it out of his bio now LOL

**Comment by JordanSantiagoYT** [comment]
oh and additionally he deleted the issue i made reporting bugs i found within his 3.2.0(?) update

**Comment by FuseIsHere813** [comment]
> > You can tell that even when Jordan made best fork, i still hate it
> 
> stefan you lashed out at me for reporting bugs with your engine, plus you're homophobic; you're not much better
> 
> ![image](https://private-user-images.githubusercontent.com/61796448/368369012-38e20657-d968-47e5-ae2d-0e563ac7aed3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MTk2NjUsIm5iZiI6MTcyNjYxOTM2NSwicGF0aCI6Ii82MTc5NjQ0OC8zNjgzNjkwMTItMzhlMjA2NTctZDk2OC00N2U1LWFlMmQtMGU1NjNhYzdhZWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAwMjkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNjhiMzNjMGE2NjMzZmMzNjUyZDhhYWQzODZkYzM3MDY0YTg3NGNkZDE0MjlkYmM1ZWM4ZjQwNTE1YjEzZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DYKSo5Oerwfx-iaVXmvKVGXouPHr8v3k8JBq_dGHLvU)

yeah give him a bruh of the year award atp 😭

**Comment by moxie-coder** [comment]
This is honestly getting too off topic from the ops post, and no I didn't hide the comments either just to cover for him, I did it because this is just off topic from the matter & this isn't very productive either, whatever problems y'all have don't bring it here

**Comment by moxie-coder** [comment]
and plus I don't support the fact he is homophobic, I don't support anyone who has homophobic views, but Stefan was the only other person I didn't mind because he's nice to me, I just don't support his anti LGBTQ views, coming from an LGBTQ person myself
