### ISSUE TITLE
custom note skins refuse to load

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#571]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

![image](https://github.com/user-attachments/assets/985df04a-ad97-4180-a86e-ed45e2f98418)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by daveandbambifan1234** [comment]
![image](https://github.com/user-attachments/assets/2e2089e8-8b7e-4d93-a744-8468eafe7dfc)
I put the note skin in the right exact folder in the right exact way and for some reason it refuses to even load it

**Comment by daveandbambifan1234** [comment]
@JordanSantiagoYT this is a major problem along with the hurtnote glitch

**Comment by JordanSantiagoYT** [comment]
you're supposed to put 'noteskins/3D-note'

**Comment by PatoFlamejanteTV** [comment]
Bro why all your posts are cursed, this one you typed "I" as summary
