### ISSUE TITLE
Default Notes Color Bug

### ISSUE THREAD

**Issue by andrekane** [JordanSantiagoYT/FNF-JS-Engine#572]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I se to default and note splashes, and turned OFF note colors, the notes were just red color looking (Also I'm on andriod) 

### Command Prompt/Terminal/Crash logs (if existing)

```bash
...
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
....
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
Don't make android issues here & also update your version

**Comment by JordanSantiagoYT** [comment]
This is not an Android-specific issue, but it is also not a bug.

The way the notes are colored is through a shader. Turning off 'Enable Note Colors' turns off the shader, which results in that.
