### ISSUE TITLE
"(-nan(ind)%)" accuracy percentage

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#574]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Hi! I was playing a random song using botplay, when I noticed the accuracy was a little bit strange, he value was "(-nan(ind)%)".

![image](https://github.com/user-attachments/assets/29426bb6-1af1-41d0-809e-0e4569de104f)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
none, its just visual
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
> Choose song
> Enabled 'botplay'
> Boom
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
This is because one side has 0 notes. Dividing by 0 is impossible so it returns -nan(ind)%.
