### ISSUE TITLE
Important thing for people making issues

### ISSUE THREAD

**Issue by JordanSantiagoYT** [JordanSantiagoYT/FNF-JS-Engine#576]
When making an issue, please double check to make sure your issue hasn't been reported already!

Here's how you can check:

In the issues tab, type your issue here.
![image](https://github.com/user-attachments/assets/706c17c6-a79c-46b0-9877-17d0943fbf5f)

Any issues similar to what you typed will show up. This is useful and 99% of the time can help you find the solution you're looking for. If you're ABSOLUTELY sure that nothing pops up when you type your issue in the search bar, THEN you can make the issue.

**Comment by PatoFlamejanteTV** [comment]
I think this is something everyone should know, but unfortunately they don't. One question, is there any way to pin this to the "Issues" tab? I know the max is 3 posts.

**Comment by JordanSantiagoYT** [comment]
i'd have to unpin one of the already pinned issues in order to pin this one.

**Comment by woodii1234** [comment]
how do i make a issue [i joined github today and i like js engine]

**Comment by JordanSantiagoYT** [comment]
adding this back to pinned, because apparently people STILL don't check for duplicate issues even with this note being in the engine itself

<img width="924" height="314" alt="Image" src="https://github.com/user-attachments/assets/9e030e09-e5bd-47f9-b88a-b5efc1d8cab5" />
