### ISSUE TITLE
request to add js engine mobile as separated branch in this repo

### ISSUE THREAD

**Issue by mcagabe19** [JordanSantiagoYT/FNF-JS-Engine#578]
### What feature do you want to get added on the **base** engine?

(there's no way me to contact @JordanSantiagoYT so I had to make like that plus Jordan has to add me here as contributor if he agrees)

**Comment by PatoFlamejanteTV** [comment]
cool idea ngl

**Comment by mcagabe19** [comment]
merged to https://github.com/JordanSantiagoYT/FNF-JS-Engine/tree/mobile
