### ISSUE TITLE
Note Colors in Options Buttons Merged 

### ISSUE THREAD

**Issue by andrekane** [JordanSantiagoYT/FNF-JS-Engine#582]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

![Screenshot_20240915-200223](https://github.com/user-attachments/assets/0e0934ef-5b7a-43cd-966a-0dd61842df7c)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

None

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by PatoFlamejanteTV** [comment]
What? Can you provide more details, please?

**Comment by moxie-coder** [comment]
> What? Can you provide more details, please?

![IMG_3539](https://github.com/user-attachments/assets/17496002-ae44-4dd3-84b2-8e5f952cd98d)
Those buttons

**Comment by PatoFlamejanteTV** [comment]
Bro, I didn't want to stay this, but in this case you should have said "overlap" instead of "merged", This is because I had already seen your question before, but I didn't understand it and I was afraid of answering wrong.

**Comment by PatoFlamejanteTV** [comment]
Btw I think it has to do with the resolution of your phone

**Comment by mcagabe19** [comment]
happens on wsa with 720p
