### ISSUE TITLE
Is there any limit of notes that I can put in a single chart?

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#583]
### What is your question?

I was charting some things, until my PC crashed, and my JS closed as well.
But, would a limit of how many notes I can fit in a chart (.JSON) file?

One of the limits may be the max values of integers:
```
          width                     minimum                         maximum
signed    8 bit                        -128                            +127
signed   16 bit                     -32 768                         +32 767
signed   32 bit              -2 147 483 648                  +2 147 483 647
signed   64 bit  -9 223 372 036 854 775 808      +9 223 372 036 854 775 807
unsigned  8 bit                           0                            +255
unsigned 16 bit                           0                         +65 535
unsigned 32 bit                           0                  +4 294 967 295
unsigned 64 bit                           0     +18 446 744 073 709 551 615
```
> (source: https://stackoverflow.com/a/15005226/26411616)

Is there another factor that could limit the note's amount?

**Comment by moxie-coder** [comment]
other then hardware limits or limits with flixel or haxe, I don’t think so

**Comment by JordanSantiagoYT** [comment]
the limit to how many notes you can save in 1 chart (HaxeFlixel only) is somewhere between 16.78 and 16.79 million notes.

If you're saving it with something else, there's really no limit as long as you have enough RAM to load/save it

**Comment by PatoFlamejanteTV** [comment]
> the limit to how many notes you can save in 1 chart (HaxeFlixel only) is somewhere between 16.78 and 16.79 million notes.
> 
> If you're saving it with something else, there's really no limit as long as you have enough RAM to load/save it

Wait, is there any other way to save without using HaxeFlixel?

**Comment by mcagabe19** [comment]
> the limit to how many notes you can save in 1 chart (HaxeFlixel only) is somewhere between 16.78 and 16.79 million notes.
> 
> If you're saving it with something else, there's really no limit as long as you have enough RAM to load/save it

unless you have 32-bit OS, 32-bit's always limited to 4294967295

**Comment by JordanSantiagoYT** [comment]
> > the limit to how many notes you can save in 1 chart (HaxeFlixel only) is somewhere between 16.78 and 16.79 million notes.
> > If you're saving it with something else, there's really no limit as long as you have enough RAM to load/save it
> 
> Wait, is there any other way to save without using HaxeFlixel?

i mean, there's quite a few charts i've saved using SNIFF instead of Haxe, which can go over 16.78m notes.

there's also splitting charts and then merging it which technically bypasses the limit too
