### ISSUE TITLE
Android Eyesore

### ISSUE THREAD

**Issue by DendyGG** [JordanSantiagoYT/FNF-JS-Engine#590]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

When Rainbow Eyesore event on android build is activate, then the engine gives an error that cannot be closed, just restart the game 
![Screenshot_20240916-194403](https://github.com/user-attachments/assets/77b0fc11-eceb-42ce-b43e-46c2aaf3c836)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I add a lot of songs to engine

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by mcagabe19** [comment]
well that's kinda new

**Comment by DendyGG** [comment]
After the update the problem on Android persists
![Screenshot_20240921-004440](https://github.com/user-attachments/assets/90ae6b03-e61e-444a-8da9-844c005c737f)

**Comment by mcagabe19** [comment]
okay should be fixed on https://github.com/JordanSantiagoYT/FNF-JS-Engine/actions/runs/10973548372
