### ISSUE TITLE
Where is the JS Engine folder

### ISSUE THREAD

**Issue by EfeOzenModder** [JordanSantiagoYT/FNF-JS-Engine#591]
### What is your question?

I can't find the JS Engine Folder on Android can you help me

**Comment by moxie-coder** [comment]
did you even try running the game first? it should be in the data folder

**Comment by EfeOzenModder** [comment]
> did you even try running the game first? it should be in the data folder

Yeah

**Comment by moxie-coder** [comment]
> > did you even try running the game first? it should be in the data folder
> 
> Yeah

it should be .jsengine

**Comment by mcagabe19** [comment]
closing as resolved
