### ISSUE TITLE
this bug was found on the latest action build, please fix this bug

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#592]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

![image](https://github.com/user-attachments/assets/6ac38353-b396-475a-8a1c-7bfc18c49146)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
a
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
a
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

a

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
and yet you didn’t explain anything at all

**Comment by JordanSantiagoYT** [comment]
> and yet you didn’t explain anything at all

i think i know what's happening
if the Save Undos option is enabled, saving 1 undo will cause the game to infinitely pop up the unsaved changes prompt, when it should only pop up if you press BACKSPACE. will be fixing

**Comment by moxie-coder** [comment]
oh, that wasn’t very obvious
