### ISSUE TITLE
iOS Engine

### ISSUE THREAD

**Issue by AlonsoxD-hack** [JordanSantiagoYT/FNF-JS-Engine#593]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Hi Jordan Santiago I Have A Problem When Open The App Only have a Black Screen Pls For Update Greetings

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

iOS

**Comment by JordanSantiagoYT** [comment]
i don't develop the mobile version, sooo uh

**Comment by mcagabe19** [comment]
can you try this?
https://github.com/JordanSantiagoYT/FNF-JS-Engine/actions/runs/10941033233/artifacts/1953088074

**Comment by mcagabe19** [comment]
@JordanSantiagoYT @moxie-coder if this user doesn't respond for 1 week, close this issue as resolved

**Comment by moxie-coder** [comment]
got it babe

**Comment by StinkTheStinker** [comment]
this should be closed by now

**Comment by JordanSantiagoYT** [comment]
closing due to 1 week of inactivity
