### ISSUE TITLE
character select issue

### ISSUE THREAD

**Issue by newfuckingplayer** [JordanSantiagoYT/FNF-JS-Engine#594]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

tried to play a song with character switch but i got an error

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Uncaught Error: Null Object Reference
flixel/graphics/frames/FlxAtlasFrames.fromSparrow() [line 253]
Character.new() [line 191]
PlayState.addCharacterToList() [line 1904]
PlayState.eventPushedUnique() [line 3228]
PlayState.eventPushed() [line 3200]
PlayState.generateSong() [line 2943]
PlayState.create() [line 1213]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.update() [line 726]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
tried to play a song with character switch but i got an error
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by newfuckingplayer** [comment]
ok i fixed it

**Comment by newfuckingplayer** [comment]
i found another bug
Uncaught Error: Null Object Reference
shaders/RGBPalette.set_r() [line 15]
shaders/RGBPalette.new() [line 39]
shaders/RGBPalette.cloneOriginal() [line 108]
shaders/RGBPalette.set_r() [line 76]
Note.defaultRGB() [line 198]
Note.set_noteType() [line 206]
Note.setupNoteData() [line 584]
PlayState.update() [line 4083]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

**Comment by JordanSantiagoYT** [comment]
rare bug that i cant really replicate
