### ISSUE TITLE
Where can I go to find base game events?

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-JS-Engine#595]
### What is your question?

I'm trying to make a custom notetype that makes gf sing but gives the note a custom texture & I can't tell what id I'm supposed to use to make only gf sing, so I thought I'd just copy the code from the gf sings notetype already in the game

**Comment by JordanSantiagoYT** [comment]
you'd be looking for the "GF Sing" notetype.

**Comment by SMWpalkia** [comment]
> you'd be looking for the "GF Sing" notetype.

whenever i try to search for it nothing comes up 
![image](https://github.com/user-attachments/assets/b9829744-2c28-49c0-899b-40a4ff59c117)

**Comment by moxie-coder** [comment]
> > you'd be looking for the "GF Sing" notetype.
> 
> whenever i try to search for it nothing comes up ![image](https://private-user-images.githubusercontent.com/136278510/369540373-b9829744-2c28-49c0-899b-40a4ff59c117.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NjI5NTMsIm5iZiI6MTcyNjg2MjY1MywicGF0aCI6Ii8xMzYyNzg1MTAvMzY5NTQwMzczLWI5ODI5NzQ0LTJjMjgtNDljMC04OTliLTQwYTRmZjU5YzExNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQyMDA0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDgyYzFlMDMxYmQzODJkOTliZTY3N2FjMGVmNWY4NzYyZDIzYmE5MWFhYjdiN2NkMzYyOTEzNzI1ZWRhYzZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vSYLtx97AC7NZM1tEYEECXohDUxN-caqUNQ7_AmZi8E)

it’s hardcoded

**Comment by moxie-coder** [comment]
you simply find it in game

**Comment by SMWpalkia** [comment]
> you simply find it in game

is there somewhere in the source code i can find how its coded? or does hardcoded mean its baked into the engine itself?

**Comment by JordanSantiagoYT** [comment]
> is there somewhere in the source code i can find how its coded? or does hardcoded mean its baked into the engine itself?

you can look in the source code for it. the main code is in PlayState

**Comment by SMWpalkia** [comment]
> > is there somewhere in the source code i can find how its coded? or does hardcoded mean its baked into the engine itself?
> 
> you can look in the source code for it. the main code is in PlayState

Got it, thank you
