### ISSUE TITLE
the select feature from the OG engine

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#596]
### What feature do you want to get added on the **base** engine?

![image](https://github.com/user-attachments/assets/bbc2f9d0-8a94-47f3-9e3e-739647b7adf9)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by JordanSantiagoYT** [comment]
so fun fact: i actually considered adding something like this to the engine, however when i tried adding it the notes would all get quantized if i moved them at all

base game added them so i might be able to add it like that

**Comment by moxie-coder** [comment]
I don't get it

**Comment by JordanSantiagoYT** [comment]
the ability to select multiple notes at once instead of only 1

**Comment by moxie-coder** [comment]
oh, that's already in 1.0
