### ISSUE TITLE
Bizarre "big-number" glitch when updating

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#600]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I was updating the JS Engine normally, but that's when this happened: the download percentage varied from "100%" to "inf%" and the limit value became the 32-bit integer limit, and the speed rate was stuck at "0/9B/s"

I don't know how to explain it, just watch the video

https://github.com/user-attachments/assets/774ed0b3-8eea-4040-b0bf-1fd98110c170

Btw my Bandicam (app I used to record screen) hided my mouse, the windows were not closing randomly, that was just me opening and closing.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
> Opened JS Engine
> Update screen
> Stuck
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by mcagabe19** [comment]
oopsie dopsie I forgor change name on updater

**Comment by JordanSantiagoYT** [comment]
afaik it was because the zip file name for the windows releases of the update was changed to "FNF-JS-Engine-windows", while every windows zip before that was "FNF-JS-Engine".

the updater doesn't find the windows zip as a result, and gets softlocked

**Comment by mcagabe19** [comment]
true

**Comment by PatoFlamejanteTV** [comment]
EDIT: For some reason it started working again, I don't know what happened, I went into JS Engine and I pressed enter to start the update.

![IMG20240921091959](https://github.com/user-attachments/assets/0377f9ac-7ab1-4e6f-9e1f-ba9e2b91a63a)
![IMG20240921091950](https://github.com/user-attachments/assets/b083d323-b9c6-4b65-9aa2-13a6f21940ad)

**Comment by JordanSantiagoYT** [comment]
so basically what happened between the issue being created and now is i basically renamed the Windows zip to "FNF-JS-Engine.zip" instead of "FNF-JS-Engine-windows.zip"
