### ISSUE TITLE
No Unicode support?

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#604]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

JS Engine doesn't load the Vocals/Inst from my song ("𓂀"). Instead, it tries to load "assets/songs/∩┐╜∩┐╜" instead.

### Command Prompt/Terminal/Crash logs (if existing)

```bash
PS C:\Users\mcmco\Downloads\Compressed\FNF-JS-Engine> C:\Users\mcmco\Downloads\Compressed\FNF-JS-Engine\JSEngine.exe
PS C:\Users\mcmco\Downloads\Compressed\FNF-JS-Engine> Error opening Steam key
source/DiscordClient.hx:82: Discord Client initialized
source/InitState.hx:29: save status: BOUND(funkin,JordanSantiago/JSEngine)
Error opening Steam key
source/TitleState.hx:95: checking for update
source/TitleState.hx:108: version online: 1.34.0, your version: 1.34.0
source/TitleState.hx:116: the versions match!
source/DiscordClient.hx:60: (Discord) Connected to User (patoflamejantetv)
source/FreeplayState.hx:670: ≡ôéÇ
source/FreeplayState.hx:684: CURRENT WEEK: weekWHAT
source/LoadingState.hx:162: Setting asset folder to shared
source/PlayState.hx:1844: Anim speed: 1.01
source/Conductor.hx:156: new BPM map BUDDY []
source/Paths.hx:84:
source/Paths.hx:88: noteskins/NOTE_assets
source/FunkinLua.hx:2914: initializing haxe interp for: mods/Imaturidade++/scripts/animated icon.lua
source/FunkinLua.hx:114: lua file loaded succesfully:mods/Imaturidade++/scripts/animated icon.lua
source/FunkinLua.hx:114: lua file loaded succesfully:mods/Imaturidade++/scripts/countdownanimation.lua
source/FunkinLua.hx:114: lua file loaded succesfully:mods/Imaturidade++/scripts/debug.lua
source/FunkinLua.hx:114: lua file loaded succesfully:mods/Imaturidade++/scripts/gapple hud.lua
source/FunkinLua.hx:114: lua file loaded succesfully:mods/Imaturidade++/scripts/GetTheHellOutOfHereMiddleScroll.lua
source/FunkinLua.hx:114: lua file loaded succesfully:mods/Imaturidade++/scripts/healthicon bops.lua
source/FunkinLua.hx:114: lua file loaded succesfully:mods/Imaturidade++/scripts/MFC.lua
source/FunkinLua.hx:114: lua file loaded succesfully:mods/Imaturidade++/scripts/SIDE HUD but better.lua
source/FunkinLua.hx:114: lua file loaded succesfully:mods/Imaturidade++/scripts/smallNoteskin.lua
source/FunkinLua.hx:114: lua file loaded succesfully:mods/Imaturidade++/scripts/smoothcam.lua
source/PlayState.hx:1212: Loading chart...
source/Paths.hx:709: oh no its returning null NOOOO (assets/songs/∩┐╜∩┐╜/Voices-bf.ogg)
source/Paths.hx:709: oh no its returning null NOOOO (assets/songs/∩┐╜∩┐╜/Voices.ogg)
source/Paths.hx:709: oh no its returning null NOOOO (assets/songs/∩┐╜∩┐╜/Voices-dad.ogg)
source/Paths.hx:709: oh no its returning null NOOOO (assets/songs/∩┐╜∩┐╜/Inst.ogg)
Section 37 loaded! (88064 notes)source/PlayState.hx:3169:
Done!
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by PatoFlamejanteTV** [comment]
Btw the window title is glitched

![image](https://github.com/user-attachments/assets/0882ae7f-0c98-4dfa-acf7-c0ce28e025d5)

**Comment by PatoFlamejanteTV** [comment]
And the song name is invisible(?)

![image](https://github.com/user-attachments/assets/f11c81ce-8d59-4d38-973f-523690c6a1e1)

**Comment by PatoFlamejanteTV** [comment]
Btw, this is how Windows (and JS should) render:

![image](https://github.com/user-attachments/assets/b8c23219-6d03-4f86-8361-7b1874f76dd6)
_(that's kinda small, ik)_
![image](https://github.com/user-attachments/assets/06d737ae-68a8-4829-aa03-9e0cf7f87a3a)
![image](https://github.com/user-attachments/assets/e5c0db5a-4d53-46fb-9ab7-36ab840f14f5)

**Comment by JordanSantiagoYT** [comment]
im pretty sure this is an issue outside of my control, haxe games don't have unicode character compatibility

**Comment by moxie-coder** [comment]
> im pretty sure this is an issue outside of my control, haxe games don't have unicode character compatibility
> 
> well, they aren't capable of using characters like ﷽ or 𓂀

it’s mainly an issue from Lime/OpenFL’s backend, as they don’t really have Unicode support
