### ISSUE TITLE
Compatibility with .hx stages/scripts?

### ISSUE THREAD

**Issue by FinderFromMac** [JordanSantiagoYT/FNF-JS-Engine#609]
### What feature do you want to get added on the **base** engine?

Is it possible to add compatibility with .hx stages/scripts?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
it is possible, however it's not implemented currently

**Comment by mcagabe19** [comment]
side not: do NOT use SScript

**Comment by PatoFlamejanteTV** [comment]
You can run .hx scripts using 
``runHaxeCode([[]])
``
Example:
``runHaxeCode([[Application.current.window.alert('Hello!', 'name lol');]])
``

**Comment by mcagabe19** [comment]
it's not about `runHaxeCode`, they meant fully hscripting

**Comment by FinderFromMac** [comment]
Will it be implemented in 1.3x?

**Comment by JordanSantiagoYT** [comment]
scripting with hx files is not something i have a priority for.
