### ISSUE TITLE
Song skibidi crashes after pressing a sigma song with my gyatt

### ISSUE THREAD

**Issue by TommykairaXVI** [JordanSantiagoYT/FNF-JS-Engine#610]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

sory for sus titl i just want mor attention to isshoe

### Command Prompt/Terminal/Crash logs (if existing)

```bash
PlayState.hx (Line 1951)
flixel/FlxGame.hx (Line 639)
flixel/FlxGame.hx (Line 726)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

modcor

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
you're not on the most up to date version

**Comment by TommykairaXVI** [comment]
> you're not on the most up to date version

it's on purpose, my friend has a terrible pc and js 1.28 is somehwat the only version that doesnt break

**Comment by JordanSantiagoYT** [comment]
based on the version's source code, tried setting the volume of 'hitsound', which is a null object

**Comment by TommykairaXVI** [comment]
> ```shell
> PlayState.hx (Line 1951)
> flixel/FlxGame.hx (Line 639)
> flixel/FlxGame.hx (Line 726)
> flixel/FlxGame.hx (Line 679)
> flixel/FlxGame.hx (Line 558)
> openfl/events/EventDispatcher.hx (Line 426)
> openfl/display/DisplayObject.hx (Line 1398)
> 
> Uncaught Error: Null Object Reference
> Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag
> 
> > Crash Handler written by: sqirra-rng
> The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
> ```

what if you test the error by itself real quick, maybe it's something else

 https://drive.google.com/drive/folders/1YtdtqtYsEfWiyt2ula2c44I0VxCiOZ_Z?usp=sharing

**Comment by TommykairaXVI** [comment]
> based on the version's source code, tried setting the volume of 'hitsound', which is a null object

what if u test thee error by yourself, it's maybe smth else

https://drive.google.com/drive/folders/1YtdtqtYsEfWiyt2ula2c44I0VxCiOZ_Z?usp=sharing

**Comment by TommykairaXVI** [comment]
> based on the version's source code, tried setting the volume of 'hitsound', which is a null object

test the error by itself, it's maybe something else

https://drive.google.com/drive/folders/1YtdtqtYsEfWiyt2ula2c44I0VxCiOZ_Z?usp=sharing

**Comment by JordanSantiagoYT** [comment]
loads fine for me

**Comment by moxie-coder** [comment]
I hate that title

**Comment by Stefan2008Git** [comment]
> I hate that title

Worse title ever i saw
![RDT_20240917_0016553954326063893865381](https://github.com/user-attachments/assets/142d9b87-994f-4fa9-be52-4f6f09d3ee8b)
