### ISSUE TITLE
please support psych engine 0.7.3 for JS engine

### ISSUE THREAD

**Issue by DavesTheBone** [JordanSantiagoYT/FNF-JS-Engine#611]
### What feature do you want to get added on the **base** engine?

uhhhhhhhh can u support psych engine 0.7.3 for JS engine?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by moxie-coder** [comment]
soon maybe if Jordan wants

**Comment by mcagabe19** [comment]
we can make js classes as 0.7.3 and for backwards compability, old classes as typedef

**Comment by DavesTheBone** [comment]
ok thx bro

**Comment by DavesTheBone** [comment]
> we can make js classes as 0.7.3 and for backwards compability, old classes as typedef

how do that?

**Comment by moxie-coder** [comment]
> > we can make js classes as 0.7.3 and for backwards compability, old classes as typedef
> 
> how do that?

simply don't worry about it, because I doubt you're smart enough to know how to do that

**Comment by DavesTheBone** [comment]
uhhhhh ok

**Comment by DavesTheBone** [comment]
> > > we can make js classes as 0.7.3 and for backwards compability, old classes as typedef
> > 
> > 
> > how do that?
> 
> simply don't worry about it, because I doubt you're smart enough to know how to do that, and the D&B community is usually full of retarded little shits

uhhhhh okey

**Comment by PatoFlamejanteTV** [comment]
> > > we can make js classes as 0.7.3 and for backwards compability, old classes as typedef
> > 
> > 
> > how do that?
> 
> simply don't worry about it, because I doubt you're smart enough to know how to do that, and the D&B community is usually full of retarded little shits

**I know that (_usually_) people in the Dave and Bambi community are kids who are mostly stupid, but I found your comment kind of unnecessary.** Tbh, I know it's something complex that many won't understand, but it's still kind of disrespectful, especially considering that JS Engine has (at least a very large portion) of focus on mods with a lot of spam (aka DnB fan mods).
![image](https://github.com/user-attachments/assets/35038ee1-7782-4d46-9841-49ae5a1d7561)
![image](https://github.com/user-attachments/assets/efd0171d-c90f-4bae-914c-f6d83215777c)
![image](https://github.com/user-attachments/assets/cf2c90c5-85ef-47c0-845b-61e3f5bdba20)

**Comment by DavesTheBone** [comment]
wow
