### ISSUE TITLE
combo thing (that maybe acts like dave in bambi in files)

### ISSUE THREAD

**Issue by Peety07** [JordanSantiagoYT/FNF-JS-Engine#616]
### What is your question?

So theres this combo sprite in all of the rating sprite files, including a gold one in goldstuff. Is there any way to turn it on
![combo](https://github.com/user-attachments/assets/d15100c4-2758-441b-ae9b-ee558c12be3b)
![combo](https://github.com/user-attachments/assets/301784ba-04a1-4725-b856-fb1b75586921)

**Comment by JordanSantiagoYT** [comment]
they used to be available but the option was removed

**Comment by nate902011** [comment]
so that's why gold stuff setting was removed. i was wondering why for a while
