### ISSUE TITLE
almost all camera events doesn't work

### ISSUE THREAD

**Issue by TommykairaXVI** [JordanSantiagoYT/FNF-JS-Engine#617]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

The thing i realised using js engine is that the events that modify the camera (ex: camera bopping, zooming) doesn't even work, even if i insert the right command for the values. Some people say it's a only me problem and it makes the case even wierder, i tried downloading with my antivirus deactivated so it wont modify small things in the executor and still doesn't work.

i need help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Modcore

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
camera bopping doesn't work if camZooming isn't enabled

**Comment by JordanSantiagoYT** [comment]
accidental closing

**Comment by TommykairaXVI** [comment]
a ok

**Comment by TommykairaXVI** [comment]
> camera bopping doesn't work if camZooming isn't enabled

how do i enable camZooming? is it some sort of set property thingy?

**Comment by JordanSantiagoYT** [comment]
> > camera bopping doesn't work if camZooming isn't enabled
> 
> how do i enable camZooming? is it some sort of set property thingy?

setProperty('camZooming', true)
OR
Enable Camera Bop (event)
OR 
Turn on the "Camera Zooms" option

**Comment by TommykairaXVI** [comment]
> camZooming

okay s

> > > camera bopping doesn't work if camZooming isn't enabled
> > 
> > 
> > how do i enable camZooming? is it some sort of set property thingy?
> 
> setProperty('camZooming', true) OR Enable Camera Bop (event) OR Turn on the "Camera Zooms" option

ok i just discivered enable camera bop is working, BUT how will i make it bop more frequently, cuz it bops every section meanwhile i want to bop 4 times per section

**Comment by TommykairaXVI** [comment]
nevermind i found out how. thank you so much for the help jordan
