### ISSUE TITLE
I caught a bug in 0.19.1

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#618]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

a note Splash caused this

### Command Prompt/Terminal/Crash logs (if existing)

```bash
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/xml/Access.hx (Line 44)
flixel/graphics/frames/FlxAtlasFrames.hx (Line 263)
NoteSplash.hx (Line 110)
NoteSplash.hx (Line 25)
PlayState.hx (Line 1771)
flixel/FlxGame.hx (Line 639)
flixel/FlxGame.hx (Line 726)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

Uncaught Error: SubTexture is missing attribute width
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
e
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

5555555555555555555555555555555555

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
![image](https://github.com/user-attachments/assets/5a39de17-6d26-412d-bb82-6c3200c1acb3)

really dude...

I'm gonna get sick of you & your braindead issues

**Comment by daveandbambifan1234** [comment]
> ![image](https://private-user-images.githubusercontent.com/124418090/371328146-5a39de17-6d26-412d-bb82-6c3200c1acb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTMwNzAsIm5iZiI6MTcyNzQxMjc3MCwicGF0aCI6Ii8xMjQ0MTgwOTAvMzcxMzI4MTQ2LTVhMzlkZTE3LTZkMjYtNDEyZC1iYjgyLTZjMzIwMGMxYWNiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwNDUyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWFlM2VkZGNlMThmNDBkM2Y1Y2JjY2QzNDMwOTUxZWE3ZTFiMTQ5YjRlZjQxM2RmMjdjMTlkMTBiMTkwOTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bs_vk1FYYXvgyWnIwrM9z0J0t3DAamDEzeNGYwSNNpg)
> 
> really dude...
> 
> I'm gonna get sick of you & your braindead issues

it's not my fault that I'm stupid |:

**Comment by daveandbambifan1234** [comment]
> ![image](https://private-user-images.githubusercontent.com/124418090/371328146-5a39de17-6d26-412d-bb82-6c3200c1acb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTM0MzgsIm5iZiI6MTcyNzQxMzEzOCwicGF0aCI6Ii8xMjQ0MTgwOTAvMzcxMzI4MTQ2LTVhMzlkZTE3LTZkMjYtNDEyZC1iYjgyLTZjMzIwMGMxYWNiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwNDU4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGI3YjgyM2JmNjI5YzY3YzA1NTc2ZGRjODRmYmU1YzVlNjIxY2EyMjFhYjEwYTU4YjRkNmNjYzQwZTg0M2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sqyAVZWnJmNaXx-gaQwtt-hd_8fgsqGBYAEAIuGjR6k)
> 
> really dude...
> 
> I'm gonna get sick of you & your braindead issues



> ![image](https://private-user-images.githubusercontent.com/124418090/371328146-5a39de17-6d26-412d-bb82-6c3200c1acb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTM0MzgsIm5iZiI6MTcyNzQxMzEzOCwicGF0aCI6Ii8xMjQ0MTgwOTAvMzcxMzI4MTQ2LTVhMzlkZTE3LTZkMjYtNDEyZC1iYjgyLTZjMzIwMGMxYWNiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwNDU4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGI3YjgyM2JmNjI5YzY3YzA1NTc2ZGRjODRmYmU1YzVlNjIxY2EyMjFhYjEwYTU4YjRkNmNjYzQwZTg0M2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sqyAVZWnJmNaXx-gaQwtt-hd_8fgsqGBYAEAIuGjR6k)
> 
> really dude...
> 
> I'm gonna get sick of you & your braindead issues

say that again and I will never use this engine ever again.

**Comment by Stefan2008Git** [comment]
> > ![image](https://private-user-images.githubusercontent.com/124418090/371328146-5a39de17-6d26-412d-bb82-6c3200c1acb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTMwNzAsIm5iZiI6MTcyNzQxMjc3MCwicGF0aCI6Ii8xMjQ0MTgwOTAvMzcxMzI4MTQ2LTVhMzlkZTE3LTZkMjYtNDEyZC1iYjgyLTZjMzIwMGMxYWNiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwNDUyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWFlM2VkZGNlMThmNDBkM2Y1Y2JjY2QzNDMwOTUxZWE3ZTFiMTQ5YjRlZjQxM2RmMjdjMTlkMTBiMTkwOTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bs_vk1FYYXvgyWnIwrM9z0J0t3DAamDEzeNGYwSNNpg)
> > really dude...
> > I'm gonna get sick of you & your braindead issues
> 
> it's not my fault that I'm stupid |:

"It's not my fault". Ig we can say that your brain is stupid because you are just a kid who doesn't go outside or something

**Comment by KernelTech11** [comment]
youre in a extremely outdated version please update to 1.34.0+

**Comment by moxie-coder** [comment]
> youre in a extremely outdated version of JS Engine , please update to 1.34.0+

that’s pretty obvious

**Comment by moxie-coder** [comment]
and it’s stupid that an issue for a version like this, would be **made in the first place**

**Comment by moxie-coder** [comment]
https://github.com/user-attachments/assets/276d448c-f006-4daf-a9b9-4f8eeb11d2cb

I probably should’ve used this in the first place instead of being petty (cuz I wasn’t in the mood)

**Comment by Stefan2008Git** [comment]
> attachment.mp4 
> I probably should’ve used this in the first place instead of being petty (cuz I wasn’t in the mood)

Take a break mate then. It seems like you have probably a bad idea

**Comment by moxie-coder** [comment]
> > attachment.mp4
> > I probably should’ve used this in the first place instead of being petty (cuz I wasn’t in the mood)
> 
> Take a break mate then. It seems like you have probably a bad day

I kinda wasn’t, I was rather sick of the annoying issues, but I did take a moment to think about what I said here

**Comment by Stefan2008Git** [comment]
> > > attachment.mp4
> > > I probably should’ve used this in the first place instead of being petty (cuz I wasn’t in the mood)
> > 
> > 
> > Take a break mate then. It seems like you have probably a bad day
> 
> I kinda was, I was rather sick of the annoying issues, but I did take a moment to think about what I said here

Just lock a conversation or remove the entire issue

**Comment by moxie-coder** [comment]
> > > > attachment.mp4
> > > > I probably should’ve used this in the first place instead of being petty (cuz I wasn’t in the mood)
> > > 
> > > 
> > > Take a break mate then. It seems like you have probably a bad day
> > 
> > 
> > I kinda was, I was rather sick of the annoying issues, but I did take a moment to think about what I said here
> 
> Just lock a conversation or remove the entire issue

I can't delete issues, but I can lock them
