### ISSUE TITLE
Remade the no more cusswords ratings

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-JS-Engine#625]
### What feature do you want to get added on the **base** engine?

![bad](https://github.com/user-attachments/assets/16803d26-f4d3-48b0-ade8-923c85bc1353)
![combo](https://github.com/user-attachments/assets/22d4aa12-f77d-449a-b4d1-3110f96ebadc)
![good](https://github.com/user-attachments/assets/f44897ea-ae91-4261-81a0-99359f992c09)
![miss](https://github.com/user-attachments/assets/58d17d85-73da-4e84-a31e-309843939a10)
![miss-pixel](https://github.com/user-attachments/assets/c804bdca-c0d0-411e-a6e1-a0ae7085bee4)
![num0](https://github.com/user-attachments/assets/e39b1227-0888-4896-9050-f458869e9e72)
![num1](https://github.com/user-attachments/assets/c813ca60-58aa-4ba0-a131-0631c310330c)
![num2](https://github.com/user-attachments/assets/d6163554-3368-42a2-95eb-59988a6d59ca)
![num3](https://github.com/user-attachments/assets/41e36e21-06a0-4634-b299-a2f3a3190b8d)
![num4](https://github.com/user-attachments/assets/0955b0cc-2a5f-47f7-a2fb-e6aa23f8adf0)
![num5](https://github.com/user-attachments/assets/4e70550a-c02b-4941-b2a0-c6dcd3c413ef)
![num6](https://github.com/user-attachments/assets/34aa923d-2647-4ac6-a869-3a5a6bebc241)
![num7](https://github.com/user-attachments/assets/a9a084c7-c58a-456b-8f4f-6c03dbfeec11)
![num8](https://github.com/user-attachments/assets/c9fc5aa8-3aa0-422b-aafc-359d5de69ea8)
![num9](https://github.com/user-attachments/assets/c7612aa3-bf5e-4660-b4ff-2cd5e8a11ab9)
![numneg](https://github.com/user-attachments/assets/44970a01-a322-434c-b147-20adb7dd5983)
![perfect](https://github.com/user-attachments/assets/16f22a9c-5ec8-44fd-9dc6-95325a10a628)
![shit](https://github.com/user-attachments/assets/fa49b135-8ffa-4ac2-a9b0-e8d5eca9b7da)
![sick](https://github.com/user-attachments/assets/f85282fd-137e-49a2-bc86-8e6a8600e59b)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by StinkTheStinker** [comment]
is this forgotten

**Comment by SantiagoCalebe** [comment]
diy

**Comment by moxie-coder** [comment]
this probably could’ve been a pr instead

**Comment by StinkTheStinker** [comment]
its just replacing images, i dont see a pr

**Comment by moxie-coder** [comment]
> its just replacing images, i dont see a pr

I’m saying you, could’ve done that

**Comment by StinkTheStinker** [comment]
oh

**Comment by StinkTheStinker** [comment]
> oh

cant do any pr's anyway, my browser shits when making one for some reason
