### ISSUE TITLE
bug with chart editor

### ISSUE THREAD

**Issue by arandomdude7** [JordanSantiagoYT/FNF-JS-Engine#626]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

this error is one i didnt know it existed, but heres how it happens if you undo something but you are not in the same section of the notes it crashes the game

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Uncaught Error: Null Object Reference
editors/ChartingState.update() [line 3026]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
step 1 go to any song in the chart editor
step 2 place some notes
step 3 go to the next section
step 4 try ctrl + z
it should crash the game its a little random
if it doesnt try some more times it happened to me again on the second try
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
what version is this?

**Comment by arandomdude7** [comment]
the lastest release, also im using vortex editor

**Comment by JordanSantiagoYT** [comment]
apparently tried modifying bpmTxt's text while it's null

**Comment by arandomdude7** [comment]
the only way for me to avoid this is not to use undo and remove the notes manually
