### ISSUE TITLE
how do i add it to psych engine

### ISSUE THREAD

**Issue by macaroniandburritos** [JordanSantiagoYT/FNF-JS-Engine#627]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

im new to modding, so im not sure what to do and what to add to the psych engine mods folder

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by StinkTheStinker** [comment]
just sprites and shit?

**Comment by macaroniandburritos** [comment]
> just sprites and shit?

nah, like just adding the mod to psych engine, like the js engine itself

**Comment by moxie-coder** [comment]
> > just sprites and shit?
> 
> nah, like just adding the mod to psych engine, like the js engine itself

the same way you do it like psych, because this basically is psych
