### ISSUE TITLE
Popup score crash

### ISSUE THREAD

**Issue by arandomdude7** [JordanSantiagoYT/FNF-JS-Engine#628]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

so i was playing a song until i decided to turn on show ratings and combos immediatly after it touched the note the game crashed

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Uncaught Error: Null Object Reference
PlayState.popUpScore() [line 5432]
PlayState.goodNoteHit() [line 5980]
PlayState.updateNote() [line 5843]
PlayState.update() [line 4107]
flixel/group/FlxGroup.forEach() [line 770]
PlayState.update() [line 4105]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
turn on show ratings and combos this in theory should cause the crash
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by arandomdude7** [comment]
[Uploading JordanSantiago.zip…]()
heres my config

**Comment by arandomdude7** [comment]
[JordanSantiago.zip](https://github.com/user-attachments/files/17186281/JordanSantiago.zip)

**Comment by arandomdude7** [comment]
nvm i found the issue apparently the show ratings crashes the game also another issue i have show combo numbers but they dont appear at my screen

**Comment by arandomdude7** [comment]
i think something is wrong with the positioning of the combo numbers so thats why they dont show up

**Comment by JordanSantiagoYT** [comment]
> nvm i found the issue apparently the show ratings crashes the game also another issue i have show combo numbers but they dont appear at my screen

did you turn off "Even LESS Botplay Lag"?

**Comment by JordanSantiagoYT** [comment]
> nvm i found the issue apparently the show ratings crashes the game also another issue i have show combo numbers but they dont appear at my screen

also, this has been fixed in a recent commit

**Comment by arandomdude7** [comment]
yes i disabled even less botplay lag and i will wait for next update

**Comment by JordanSantiagoYT** [comment]
> yes i disabled even less botplay lag and i will wait for next update

so then you positioned the offsets of the combo numbers in such a way that they're offscreen

**Comment by arandomdude7** [comment]
![image](https://github.com/user-attachments/assets/defb5795-2e0d-4490-a567-9525485999c8)

**Comment by arandomdude7** [comment]
the one that does work is the ms popup one

**Comment by arandomdude7** [comment]
i checked the playstate code for it and i cannot undestand how it works but maybe its not loading the image

**Comment by arandomdude7** [comment]
maybe the image exists but when loaded is invisible?
