### ISSUE TITLE
Html Support?

### ISSUE THREAD

**Issue by Memelord111** [JordanSantiagoYT/FNF-JS-Engine#629]
### What feature do you want to get added on the **base** engine?

Yknow if you can re-add html support if it isn't available if it is then just close this request

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by Memelord111** [comment]
yea but then again you can disable mods and do source code stuff in the project file

**Comment by moxie-coder** [comment]
HTML5 support seems unlikely since this engine is not made for low end devices, and I don’t know how it would perform on a browser

**Comment by PatoFlamejanteTV** [comment]
You can use HTML content in your songs using Lua's `os.execute()`.

E.g.:
``` lua
function onEndSong()
	os.execute('cd mods && cd Imaturidade++ && cd non-fnf && cd TurboWarp && cd escape && start escape.html')
	end
```
(Ik the code is kinda unorganized, but it works)

**Comment by moxie-coder** [comment]
> You can use HTML content in your songs using Lua's `os.execute()`.
> 
> E.g.:
> 
> ```lua
> function onEndSong()
> 	os.execute('cd mods && cd Imaturidade++ && cd non-fnf && cd TurboWarp && cd escape && start escape.html')
> 	end
> ```
> 
> (Ik the code is kinda unorganized, but it works)

lua doesn’t *work* with html5

**Comment by PatoFlamejanteTV** [comment]
> > You can use HTML content in your songs using Lua's `os.execute()`.
> > E.g.:
> > ```lua
> > function onEndSong()
> > 	os.execute('cd mods && cd Imaturidade++ && cd non-fnf && cd TurboWarp && cd escape && start escape.html')
> > 	end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (Ik the code is kinda unorganized, but it works)
> 
> lua doesn’t _work_ with html5

I know, but you can manipulate/open an .HTML file using Lua (e.g. when the song ends/when you die)

**Comment by PatoFlamejanteTV** [comment]
> lua doesn’t _work_ with html5

Btw [you can use Lua in JS using Wasmoon](https://github.com/ceifa/wasmoon), but (i think) not using os-related functions.

```
This package aims to provide a way to:
    Embed Lua to any Node.js, Deno or Web Application.
    Run lua code in any operational system
    Interop Lua and JS without memory leaks (including the DOM)
```
