### ISSUE TITLE
What languages ​​are supported by JS Engine?

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#630]
### What is your question?

I mean both softmodding (without touching the engine's code base) and hardmodding (modifying the engine's code base).

I know it's possible to use:
- Lua (**soft**)
- Haxe (**hard**, [but can be used with some tricks using soft](https://github.com/JordanSantiagoYT/FNF-JS-Engine/wiki/LUA-%E2%80%90-os.execute-function)
- BatchFile (.bat/.cmd/`os.execute()`) (specific to operating system (Windows)), **soft**).
- C++ (C++ natively since desktop builds are usually compiled to C++. [Font](https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/630#issuecomment-2384010064). Specific to operating system (Windows), **hard(?)**)
- JavaScript ((maybe) when run on HTML5, **hard**)

Are there any others that can be used?

**Comment by PatoFlamejanteTV** [comment]
Btw this kind of also applies to Psych Engine (and its other forks too)

**Comment by moxie-coder** [comment]
> ### What is your question?
> I mean both softmodding (without touching the engine's code base) and hardmodding (modifying the engine's code base).
> 
> I know it's possible to use:
> 
> * Lua (**soft**)
> * Haxe (**hard**, _[but can be used with some tricks using soft](https://github.com/JordanSantiagoYT/FNF-JS-Engine/wiki/LUA:-os.execute-function)_)
> * BatchFile (.bat/.cmd/`os.execute()`) (specific to operating system (Windows), **soft**).
> * C++ (**?**)
> * JavaScript ((maybe) when run on HTML5, **hard**)
> 
> Are there any others that can be used?

C++ natively since desktop builds are usually compiled to C++

**Comment by JordanSantiagoYT** [comment]
aside from those, there arent really any other languages that you can use

**Comment by PatoFlamejanteTV** [comment]
> aside from those, there arent really any other languages that you can use

By the way, can I ask a question? How was Lua modding implemented in Engine? I know you can embed Lua on C, but how could Lua be embedded in Haxe?

**Comment by JordanSantiagoYT** [comment]
> > aside from those, there arent really any other languages that you can use
> 
> By the way, can I ask a question? How was Lua modding implemented in Engine? I know you can embed Lua on C, but how could Lua be embedded in Haxe?

idk, ask shadowmario since he was the one that originally did it

**Comment by Stefan2008Git** [comment]
> > aside from those, there arent really any other languages that you can use
> 
> By the way, can I ask a question? How was Lua modding implemented in Engine? I know you can embed Lua on C, but how could Lua be embedded in Haxe?

There is extra packages from llua for that and it uses `linc_luajit` for llua handler
