### ISSUE TITLE
Health bar not showing while playing a song.

### ISSUE THREAD

**Issue by nate902011** [JordanSantiagoYT/FNF-JS-Engine#632]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Whenever I go into a song the health bar doesn't show up.
![Screenshot 2024-10-01 160054](https://github.com/user-attachments/assets/3d019228-d256-457b-9e1e-f442f5769f2a)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by nate902011** [comment]
and no i did not edit anything that has to do with the hud or health bar

**Comment by JordanSantiagoYT** [comment]
do you have a lua script that runs

```
setProperty('healthBarBG.visible', false)
setProperty('healthBar.visible', false)
```
or use a health bar option that isn't in the list of currently existing options

**Comment by nate902011** [comment]
no i do not

**Comment by JordanSantiagoYT** [comment]
so then idk

**Comment by nate902011** [comment]
ok

**Comment by moxie-coder** [comment]
> so then idk

there’s a setting for that

**Comment by nate902011** [comment]
where is the setting?

**Comment by JordanSantiagoYT** [comment]
OH WAIT

**Comment by JordanSantiagoYT** [comment]
the Health Bar Style option in the visuals & UI menu has a "hide" option

double check that it isn't set to that

**Comment by nate902011** [comment]
nope it was set to vanilla and i checked and there was no "hide" option available

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/5ca79d8c-5004-4930-ae90-43fe6a846756)
??

**Comment by nate902011** [comment]
The only options that are on the screenshot are "Vanilla" and "Dave Engine" plus one not on there "Doki Doki+" 
there is no "hide" option in the health bar style settings

**Comment by JordanSantiagoYT** [comment]
ok apparently im stupid

github search results mixed that option with another one

idk then

**Comment by nate902011** [comment]
ok

**Comment by StinkTheStinker** [comment]
performance issue maybe? not sure

**Comment by nate902011** [comment]
GUYS I FIXED THE ISSUE
![image_2024-10-03_210146593](https://github.com/user-attachments/assets/78eef290-165a-4fea-944b-dff549405f44)

**Comment by nate902011** [comment]
that health bar transparency setting really be wack

**Comment by nate902011** [comment]
the setting was set to 0% so i tried setting it to 100% in it worked

**Comment by nate902011** [comment]
i was just stupid the whole time

**Comment by moxie-coder** [comment]
bruh

**Comment by nate902011** [comment]
because of my dumbass, you added something to clear up confusion.
