### ISSUE TITLE
Question about Port

### ISSUE THREAD

**Issue by BambiGaming2022** [JordanSantiagoYT/FNF-JS-Engine#633]
### What is your question?

when 0.7.1h or 0.7.3 port if Jordan wants it

**Comment by moxie-coder** [comment]
> ### What is your question?
> when 0.7.1h or 0.7.3 port if Jordan wants it

idk when that'll be, that's up to him when he wants to do it

**Comment by JordanSantiagoYT** [comment]
honestly i still don't want to port to the newer versions because theres just too much stuff to port over
