### ISSUE TITLE
Crash while playing

### ISSUE THREAD

**Issue by radishYT** [JordanSantiagoYT/FNF-JS-Engine#634]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I was playing on an easy song, and then suddenly the game crashed for no reason at all. There is no closing window event.

### Command Prompt/Terminal/Crash logs (if existing)

```bash
No Crash log
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Freeplay > [Song] > Playing for 1 Minute > Crash
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
unable to replicate your issue.

can you try this with a command prompt open?

1. Open a command prompt
2. run "cd (JSEngine.exe's directory)"
3. run "JSEngine.exe"

try replicating your issue and seeing if the command prompt shows anything after the crash. if not, then idk

**Comment by radishYT** [comment]
Now there's a second problem. I can't use the engine if the command prompt is open.

1. Crash log: Uncaught Error: [file_contents,assets/images/titleEnter.xml]
C:\hostedtoolcache\windows\haxe\4.3.4\x64\std/cpp/_std/sys/io/File.getContent() [line 30]
TitleState.startIntro() [line 248]
TitleState.create() [line 165]
flixel/util/FlxTimer.onLoopFinished() [line 205]
flixel/util/FlxTimer.update() [line 295]
flixel/FlxGame.update() [line 747]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]

2. Crash log: Uncaught Error: VLC caught an error!
vlc/MP4Handler.onVLCError() [line 81]
vlc/bitmap/VlcBitmap.statusOnError() [line 480]
vlc/bitmap/VlcBitmap.checkFlags() [line 246]
vlc/bitmap/VlcBitmap.vLoop() [line 331]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]

**Comment by moxie-coder** [comment]
> Now there's a second problem. I can't use the engine if the command prompt is open.
> 
> 1. Crash log: Uncaught Error: [file_contents,assets/images/titleEnter.xml]
>    C:\hostedtoolcache\windows\haxe\4.3.4\x64\std/cpp/_std/sys/io/File.getContent() [line 30]
>    TitleState.startIntro() [line 248]
>    TitleState.create() [line 165]
>    flixel/util/FlxTimer.onLoopFinished() [line 205]
>    flixel/util/FlxTimer.update() [line 295]
>    flixel/FlxGame.update() [line 747]
>    flixel/FlxGame.step() [line 679]
>    flixel/FlxGame.onEnterFrame() [line 558]
>    openfl/events/EventDispatcher.__dispatchEvent() [line 426]
>    openfl/display/DisplayObject.__dispatch() [line 1398]
> 2. Crash log: Uncaught Error: VLC caught an error!
>    vlc/MP4Handler.onVLCError() [line 81]
>    vlc/bitmap/VlcBitmap.statusOnError() [line 480]
>    vlc/bitmap/VlcBitmap.checkFlags() [line 246]
>    vlc/bitmap/VlcBitmap.vLoop() [line 331]
>    openfl/events/EventDispatcher.__dispatchEvent() [line 426]
>    openfl/display/DisplayObject.__dispatch() [line 1398]

are you using the latest version?

**Comment by JordanSantiagoYT** [comment]
this issue is caused because you just drag and dropped the js engine exe into the command prompt, then pressed enter instead of running "cd (JSE Directory)" and running "JSEngine.exe"

the problem with doing that is that due to an issue that is beyond my fixing, the engine will not find the required files and crash as a result.

**Comment by moxie-coder** [comment]
> this issue is caused because you just drag and dropped the js engine exe into the command prompt, then pressed enter instead of running "cd (JSE Directory)" and running "JSEngine.exe"
> 
> the problem with doing that is that due to an issue that is beyond my fixing, the engine will not find the required files and crash as a result.

bruh 💀

**Comment by StinkTheStinker** [comment]
aint no way-

**Comment by radishYT** [comment]
> > Now there's a second problem. I can't use the engine if the command prompt is open.
> > 
> > 1. Crash log: Uncaught Error: [file_contents,assets/images/titleEnter.xml]
> >    C:\hostedtoolcache\windows\haxe\4.3.4\x64\std/cpp/_std/sys/io/File.getContent() [line 30]
> >    TitleState.startIntro() [line 248]
> >    TitleState.create() [line 165]
> >    flixel/util/FlxTimer.onLoopFinished() [line 205]
> >    flixel/util/FlxTimer.update() [line 295]
> >    flixel/FlxGame.update() [line 747]
> >    flixel/FlxGame.step() [line 679]
> >    flixel/FlxGame.onEnterFrame() [line 558]
> >    openfl/events/EventDispatcher.__dispatchEvent() [line 426]
> >    openfl/display/DisplayObject.__dispatch() [line 1398]
> > 2. Crash log: Uncaught Error: VLC caught an error!
> >    vlc/MP4Handler.onVLCError() [line 81]
> >    vlc/bitmap/VlcBitmap.statusOnError() [line 480]
> >    vlc/bitmap/VlcBitmap.checkFlags() [line 246]
> >    vlc/bitmap/VlcBitmap.vLoop() [line 331]
> >    openfl/events/EventDispatcher.__dispatchEvent() [line 426]
> >    openfl/display/DisplayObject.__dispatch() [line 1398]
> 
> are you using the latest version?

yes

**Comment by StinkTheStinker** [comment]
is this on the start menu where you press enter to start

**Comment by StinkTheStinker** [comment]
if it is happening on the start menu

**Comment by radishYT** [comment]
It happened on TitleState or on the splash screen

**Comment by StinkTheStinker** [comment]
go to the options menu and do this if possible
Visual and UI > Show Debug Info (turn this on)
at least extract the JS Engine zip again to see if there was missing files during extraction

**Comment by JordanSantiagoYT** [comment]
> go to the options menu and do this if possible Visual and UI > Show Debug Info (turn this on) at least extract the JS Engine zip again to see if there was missing files during extraction

that's not what is happening

i literally explained what happened in another reply :sob:

**Comment by StinkTheStinker** [comment]
its because i didnt understand that reply

**Comment by Mm1like** [comment]
Trying to play the game for like the 150th time 

![Image](https://github.com/user-attachments/assets/717e4499-f69e-49ba-8751-952659659102)
![Image](https://github.com/user-attachments/assets/b3fc7ecb-9aec-4f0c-9f24-cd1567d42ff5)

**Comment by Mm1like** [comment]
i cant chart anything anymore vrooooo💔

**Comment by moxie-coder** [comment]
> Trying to play the game for like the 150th time
> 
> ![Image](https://github.com/user-attachments/assets/717e4499-f69e-49ba-8751-952659659102) ![Image](https://github.com/user-attachments/assets/b3fc7ecb-9aec-4f0c-9f24-cd1567d42ff5)

see #559
