### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by SyncGit12** [JordanSantiagoYT/FNF-JS-Engine#640]
### What is your question?

# Building the game in other platforms

How do i like, export the engine into different platforms like

`HTML5`, `Mac`, and `Linux` like you do?

**Comment by JordanSantiagoYT** [comment]
run `lime build (Platform)` while running a device on that platform

**Comment by SyncGit12** [comment]
hmmmmmmmmmmMMMMMMMMMMMMMMMMMMMmmmmmmmmmmmmmmmmmm

html5:
C:/haxelib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while targeting js (for cpp.RawPointer)
C:/haxelib/linc_luajit/git/llua/Lua.hx:4: characters 8-18 : ... referenced here
C:\Users\(me)\Desktop\VsCoolRepository\source\import.hx:14: characters 8-16 : ... referenced here
C:\Users\(me)\Desktop\VsCoolRepository\source\import.hx:2: characters 8-13 : ... referenced here
export/release/html5/haxe/ApplicationMain.hx:321: characters 48-52 : ... referenced here

mac:
C:/haxelib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while targeting neko (for cpp.RawPointer)
C:/haxelib/linc_luajit/git/llua/Lua.hx:4: characters 8-18 : ... referenced here
C:\Users\(me)\Desktop\VsCoolRepository\source\import.hx:14: characters 8-16 : ... referenced here
C:\Users\(me)\Desktop\VsCoolRepository\source\import.hx:2: characters 8-13 : ... referenced here
export/release/neko/haxe/ApplicationMain.hx:321: characters 48-52 : ... referenced here

linux:

C:/haxelib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while targeting neko (for cpp.RawPointer)
C:/haxelib/linc_luajit/git/llua/Lua.hx:4: characters 8-18 : ... referenced here
C:\Users\(me)\Desktop\VsCoolRepository\source\import.hx:14: characters 8-16 : ... referenced here
C:\Users\(me)\Desktop\VsCoolRepository\source\import.hx:2: characters 8-13 : ... referenced here
export/release/neko/haxe/ApplicationMain.hx:321: characters 48-52 : ... referenced here

uuuuuuuuuuuuuhhhhhhhhhhhhhhhhhhhhh

**Comment by JordanSantiagoYT** [comment]
okay

you're supposed to be running on the same device as the platform you're compiling

example: mac builds can ONLY be compiled on macOS

**Comment by SyncGit12** [comment]
you should understand this

me = poor cuz = economy of my country (AKA argentina)

**Comment by moxie-coder** [comment]
you can't cross build to other platforms on Windows, they use Neko to compile otherwise
