### ISSUE TITLE
What does it mean when I get this popup?

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-JS-Engine#643]
### What is your question?

![IMG_6352](https://github.com/user-attachments/assets/58beaed6-db6f-49aa-b9f9-1fd1d4305567)
I've gotten this popup multiple times when I switch between zooms in the chart editor a lot where it closes the game (doesn't give a crash log), turns my screen black, and turns nightlight mode off on my computer itself

**Comment by moxie-coder** [comment]
your pc ran out of memory, which I can’t really do much about

**Comment by SMWpalkia** [comment]
do you know what part of the process if causing me to run out of memory?

**Comment by NAEL2XD** [comment]
> do you know what part of the process if causing me to run out of memory?

technically some process can take a shit ton of mem, you can view in task manager by using these shortcut: CTRL + SHIFT + DEL

and to fix OoM (Out of Memory) you need more memory/ram

**Comment by StinkTheStinker** [comment]
> do you know what part of the process if causing me to run out of memory?

chro-
