### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Luis-P-del** [JordanSantiagoYT/FNF-JS-Engine#645]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Hi, in the JS engine I was configuring the keys to my liking and disabling the shaders so that I don't get lag, but while I want to play I get an error:

 PlayState.hx (Line 7422)
PlayState.hx (Line 6245)
PlayState.hx (Line 5772)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Error not detected: Null Object Reference
Please report this error on the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log in the crash folder. If you are making an issue on GitHub, can you please submit it!

¿Can you help me please?

Translated with DeepL.com (free version)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

n

**Comment by JordanSantiagoYT** [comment]
what version is this?

**Comment by Luis-P-del** [comment]
in the new

**Comment by JordanSantiagoYT** [comment]
that's not the newest version. the newer version has a newer style for reporting the crash lines

the log you provided seems to reference the older format which was used in older versions

**Comment by Luis-P-del** [comment]
sorry here is the new one: 

Uncaught Error: Null Object Reference
PlayState.update() [line 3945].
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558] flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error on the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a bug log inside the bugs folder, if you are making an issue on GitHub you might want to submit it.

**Comment by JordanSantiagoYT** [comment]
seems the game paused while the vocals and/or opponent vocals were null

**Comment by Luis-P-del** [comment]
how to solve it

**Comment by JordanSantiagoYT** [comment]
use latest action build, im about to push out a commit that fixes this

**Comment by JordanSantiagoYT** [comment]
fixed by latest commit
