### ISSUE TITLE
Hello, I was trying to make a graph but when I go to the graph editor and put the name "Marathevenge.1" as well as the data and songs folder, I get this error, I don't know why it appears but I put the name correctly, eliminating the voice has and only with the audio "Inst.ogg". Does anyone know how to fix it? I need answers quickly please

### ISSUE THREAD

**Issue by CG1396** [JordanSantiagoYT/FNF-JS-Engine#646]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![Captura](https://github.com/user-attachments/assets/5800d6fb-7444-4789-a368-2ff4da38568b)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
it's possible that you probably just changed a mp3's file extension to an OGG.

if not that, your ogg is probably corrupted

**Comment by CG1396** [comment]
thankss you!!!

**Comment by JordanSantiagoYT** [comment]
OH I FORGOT TOO

if your song name has a ".", you'll need to replace that with a "-" too

**Comment by StinkTheStinker** [comment]
if possible, use fl studio (or whatever music making software you use or have on your computer) to convert mp3's to ogg's, or any file type.

**Comment by moxie-coder** [comment]
btw please don't put your whole question in the title

**Comment by Stefan2008Git** [comment]
> if possible, use fl studio (or whatever music making software you use or have on your computer) to convert mp3's to ogg's, or any file type.

Me when converter exits:
