### ISSUE TITLE
no video renders

### ISSUE THREAD

**Issue by expungeddotdat** [JordanSantiagoYT/FNF-JS-Engine#649]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

when i render a song (not classic mode) and it finishes it says bla bla bla song rendered and you can find it in assets/GameRenders but when i check the folder theres no any new videos or folders, just renderlol.bat and readme.txt. 

### Command Prompt/Terminal/Crash logs (if existing)

no

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

i tried to render second time but nothing worked

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

Yes

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
you likely forgot to put `ffmpeg.exe` in the same location as `JSEngine.exe`!

**Comment by expungeddotdat** [comment]
> you likely forgot to put `ffmpeg.exe` in the same location as `JSEngine.exe`!

okay, i put it in folder, mp4 appeared but when i try to open it it gives me a 0xC00D36C4 error. how to fix?

**Comment by JordanSantiagoYT** [comment]
> > you likely forgot to put `ffmpeg.exe` in the same location as `JSEngine.exe`!
> 
> okay, i put it in folder, mp4 appeared but when i try to open it it gives me a 0xC00D36C4 error. how to fix?

you can't open it using Media Player. you have to open it with a video editor.

**Comment by expungeddotdat** [comment]
nvm i tried using vlc video player and it opened

**Comment by nxvelveteen** [comment]
@moxie-coder i'm having the same issue but ffmpeg is in the same folder as jse

**Comment by moxie-coder** [comment]
> [@moxie-coder](https://github.com/moxie-coder) i'm having the same issue but ffmpeg is in the same folder as jse

and you commented on an year old post just to tell me that? if you're looking through them that might help then
