### ISSUE TITLE
why is it crashing exactly? everything it's fine but it keep crasing for no reason!

### ISSUE THREAD

**Issue by EnergyFNF** [JordanSantiagoYT/FNF-JS-Engine#652]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

basically, i was testing one of my songs with the engine becuase i change PE (Psych Engine) for JS engine and when i added a script that makes a loading screen, the song just crashes? idk how that's happening, it's just, if a put out the script the song works, but if i put it in again it crashes... (also i was testing fuming from null_y34r)
![Captura de pantalla 2024-10-14 131454](https://github.com/user-attachments/assets/44b171b5-836d-4191-8fa3-261ee57ddf4d)
can someone help me with it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
the loading screen appears to have a note rendered onscreen.

Each note does an updateNote function, which calls followStrum so that it follows a strum.

However, because of the loading screen that strum does not exist.

**Comment by EnergyFNF** [comment]
> the loading screen appears to have a note rendered onscreen.
> 
> Each note does an updateNote function, which calls followStrum so that it follows a strum.
> 
> However, because of the loading screen that strum does not exist.

really? wow... well guess i will try using source code then, becuase at least with the source code the songs will be fine :/ also thanks for tell me the problem :)

**Comment by JordanSantiagoYT** [comment]
just realized

this is issue 652
and it was closed at exactly 6:52 pm
