### ISSUE TITLE
ffmpeg closing itself and game freezing on rendering mode

### ISSUE THREAD

**Issue by AlienCat65** [JordanSantiagoYT/FNF-JS-Engine#653]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I tried to render eons, a chart from nusm, but the problem is, ffmpeg closes itself after the first note
for the second issue, the game freezes after a certain period of time

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Turn on Rendering Mode
Force GC Off while rendering
Play a song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
This issue does not occur for me.

![image](https://github.com/user-attachments/assets/e0abe5db-619f-40ff-87f0-2f0178a3ee2e)

**Comment by AlienCat65** [comment]
maybe its because im rendering it on a different engine version, i will try nusm tho

**Comment by AlienCat65** [comment]
or is it because i play on full screen?

**Comment by StinkTheStinker** [comment]
open cmd
copy and paste in the path that the exe is in (dont include quotation marks and the .exe), and put cd at the start of the path
- should be something like this:  cd C:\Users\Your User\Exe Path
![image](https://github.com/user-attachments/assets/e5e24f6c-4a0b-457c-b0a2-ec12f410ed72) - the wrong way
![image](https://github.com/user-attachments/assets/c1d3e4fc-3a0f-4708-b76c-931e5113456e) - the right way

**Comment by StinkTheStinker** [comment]
screenshots are examples

**Comment by StinkTheStinker** [comment]
tell me what it says when it crashes

**Comment by StinkTheStinker** [comment]
oh, and look at the cmd while doing the render

**Comment by StinkTheStinker** [comment]
someone close as not planned

**Comment by AlienCat65** [comment]
ffmpeg closes AFTER it renders the first note

i saw it in task manager

**Comment by JordanSantiagoYT** [comment]
this does not occur to me, so i am not able to assist with this.
