### ISSUE TITLE
Add Hjson support

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#655]
### What feature do you want to get added on the **base** engine?

I think adding Hjson support would be nice, especially for documenting things like "what does value X mean" in chart/week .JSON files.

Also it supports comments:

``` Hjson
{
  # hash style comments
  # (because it's just one character)

  // line style comments
  // (because it's like C/JavaScript/...)

  /* block style comments because
     it allows you to comment out a block */

  # Everything you do in comments,
  # stays in comments ;-}
}
```

https://hjson.github.io/

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
i don't think Hjson is needed

there just doesn't seem to be any real place where i'd consider using it, or it would break json support
