### ISSUE TITLE
Crash when pressing (copy next to [set number])

### ISSUE THREAD

**Issue by TofpFL** [JordanSantiagoYT/FNF-JS-Engine#656]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I am charting, and there is a pattern that goes on for a couple of times, so I decide to use a nice feature. But it crashes my engine. 

### Command Prompt/Terminal/Crash logs (if existing)

[JSEngine_2024-10-16_17'34'31.log](https://github.com/user-attachments/files/17404531/JSEngine_2024-10-16_17.34.31.log)

Uncaught Error: Null Object Reference
editors/ChartingState.addSectionUI() [line 1335]
flixel/ui/FlxButton.onUpHandler() [line 521]
flixel/ui/FlxButton.onUpEventListener() [line 507]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Go into chart editor, make a pattern, and then press the button that does the feature. 

https://github.com/user-attachments/assets/3457c40b-fbeb-44b8-b85e-3a8ed3785a4d

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit any of the chart editor stuff

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
special thanks to my really great coding skills

**Comment by JordanSantiagoYT** [comment]
Closed by recent commit.

**Comment by TofpFL** [comment]
So the best way to temporarily fix it would be to go through the sections 1 by 1 and then saving it as a JSON, then pressing the button?
