### ISSUE TITLE
Change Opponent Color Notes

### ISSUE THREAD

**Issue by TofpFL** [JordanSantiagoYT/FNF-JS-Engine#657]
### What feature do you want to get added on the **base** engine?

Instead of only choosing the same color for each character, you could customize the color of the opponent's note color. 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by TofpFL** [comment]
this just randomly came out of my ass when I was in the shower so #showerthoughts

**Comment by JordanSantiagoYT** [comment]
this was a yoshi engine thing, but i don't want to consider this yet as i don't even have an idea for a menu for something like this!

**Comment by PatoFlamejanteTV** [comment]
I guess you can recreate this using custom notes idk
