### ISSUE TITLE
i cant die

### ISSUE THREAD

**Issue by stripes10122** [JordanSantiagoYT/FNF-JS-Engine#658]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

it adds heath when i die, i want a chalnge, i cnat die so it borning

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
that's mod specific. either that or you set the health loss multiplier to a negative amount

**Comment by StinkTheStinker** [comment]
or make a lua script like this:
```
function onStepHit()
     setProperty'health', 1)
end
```

**Comment by moxie-coder** [comment]
that's either a mod thing or like he said, set the health loss mult to a negative value

**Comment by stripes10122** [comment]
it doesnt work, i cant die on any song in the funny  songs mods

**Comment by stripes10122** [comment]
i fixed it
