### ISSUE TITLE
how do i enable botplay

### ISSUE THREAD

**Issue by Thomi12345** [JordanSantiagoYT/FNF-JS-Engine#660]
### What is your question?

how do i enable botplay?

**Comment by JordanSantiagoYT** [comment]
go to freeplay, then press CTRL, then turn on the "Botplay" gameplay changer

**Comment by StinkTheStinker** [comment]
Or
Pause>Gameplay Modifier>Select BotPlay
Score will not count if its toggled on

**Comment by moxie-coder** [comment]
go to freeplay or story mode, press CTRL, then turn on botplay from there

**Comment by StinkTheStinker** [comment]
> go to freeplay or story mode, press CTRL, then turn on botplay from there

kind of been said already
