### ISSUE TITLE
Custom notes offset strangely

### ISSUE THREAD

**Issue by Niko-The-Fluffy** [JordanSantiagoYT/FNF-JS-Engine#662]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

The custom notetypes are offset slightly, to the left and up a bit. this also causes strange hitbox bugs, rendering some of our songs impossible without botplay, and is just generally annoying.
![image](https://github.com/user-attachments/assets/143233cf-7daf-4a1d-a93e-e742432ed806)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

The bug happens naturally, as seen in the attached image.
![image](https://github.com/user-attachments/assets/e9341ae9-ba62-4374-abe9-97af7a2669d9)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Creating an entire FNF mod, the only thing broken is the note offsets.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by Niko-The-Fluffy** [comment]
I didn't mean to put the image twice-

**Comment by PatoFlamejanteTV** [comment]
It is a modified arrow (custom skin/note) or it's a normal arrow?

**Comment by Niko-The-Fluffy** [comment]
> that could just be from the effects, or from your notes xml offsets

nope, it worked perfectly fine before we ported the mod over to JS engine

**Comment by Niko-The-Fluffy** [comment]
> It is a modified arrow (custom skin/note) or it's a normal arrow?

custom_notetype used for this, happens with other custom notetypes as well.

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/c5d07bdf-e39e-45d0-9a3a-ef957a9e5a0b)
it could be because of this snippet of code

**Comment by PatoFlamejanteTV** [comment]
> > It is a modified arrow (custom skin/note) or it's a normal arrow?
> 
> custom_notetype used for this, happens with other custom notetypes as well.

Can you send a random code from any custom_notes arrow? It may be a problem with the (softcoded) code.

**Comment by JordanSantiagoYT** [comment]
> > > It is a modified arrow (custom skin/note) or it's a normal arrow?
> > 
> > 
> > custom_notetype used for this, happens with other custom notetypes as well.
> 
> Can you send a random code from any custom_notes arrow? It may be a problem with the (softcoded) code.

well actually, this seems to also happen with the Phone Note notetype when i use it. so it could be because of a snippet of code

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/a4f388f7-36d6-444f-92fa-bebb49598f51)
well it fixed normal notes, not so sure about the Sustain Notes though

**Comment by Niko-The-Fluffy** [comment]
eh, i don't really plan on using sustain custom notes for the mod, i was mainly worried about the actual notes themselves
