### ISSUE TITLE
Update estimated time is 0-2147483648:0-2147483648:0-2147483648?

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#664]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

![image](https://github.com/user-attachments/assets/6e5ac4e7-430c-40e1-869c-6a59beaafd0a)

**Bizarre fact:** "2,147,483,647" is the 32 bit integer limit (huge math number), somehow it estimated that it will take something between 0-2147483648 hours, 0-2147483648 minutes and 0-2147483648 seconds, (the "-" represents that it's a range) so it COULD be 0, 1,2, 3, 4, 45, 8263, 6546, etc.

IF it updated in 2147483648 hours, it will take `8.9478E+7 (89478485)` days to update.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Uhh, i updated the game and boom.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by PatoFlamejanteTV** [comment]
Btw, yes the update was successful, but it just showed that big numbers around 2 seconds before the game restarted. So yeah, it's just a visual glitch.

**Comment by CoolDudeT** [comment]
Yeah, it happens to me too. It's just a visual glitch, nothing crazy.

**Comment by TofpFL** [comment]
It happened to me but not when the game was done updating. It just randomly went there. Probably because I clicked out of it a couple of times and etc.
