### ISSUE TITLE
D&B Definitive edition freeplay text

### ISSUE THREAD

**Issue by Memelord111** [JordanSantiagoYT/FNF-JS-Engine#665]
### What feature do you want to get added on the **base** engine?

Can you add a option for the free play text to be in different shapes like the disc like shape in definitive edition,in the source code for definitive you can find the free play shapes in alphabet.hx

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by NAEL2XD** [comment]
> ### What feature do you want to get added on the **base** engine?
> Can you add a option for the free play text to be in different shapes like the disc like shape in definitive edition,in the source code for definitive you can find the free play shapes in alphabet.hx
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor and 6K+ support.

can you send an image, your text is confusing

**Comment by Memelord111** [comment]
> > ### What feature do you want to get added on the **base** engine?
> 
> > Can you add a option for the free play text to be in different shapes like the disc like shape in definitive edition,in the source code for definitive you can find the free play shapes in alphabet.hx
> 
> > 
> 
> > ### To test your sight, and reliability, please select the option of what should NOT be requested.
> 
> > Stage Editor and 6K+ support.
> 
> 
> 
> can you send an image, your text is confusing
 
![image](https://github.com/user-attachments/assets/ecf8a5b9-0257-4dbc-aeaa-5ef7ec934e4f)

**Comment by JordanSantiagoYT** [comment]
No

this wouldn't really be useful, and isn't something that id use

**Comment by CoolDudeT** [comment]
you forgot to close it
