### ISSUE TITLE
Vs. Imposter double note trail as an option in settings

### ISSUE THREAD

**Issue by CoolDudeT** [JordanSantiagoYT/FNF-JS-Engine#666]
### What feature do you want to get added on the **base** engine?

So you know how when you hit a double note in Vs. Imposter, your character will create a ghost trail? So basically, just add that in as a optional setting in Gameplay. Thanks in advance! (BTW, if you need the link to the Impostor V4 source code, here you go: [amogus](https://github.com/Clowfoe/IMPOSTOR-UPDATE/tree/main))
![amogus](https://github.com/user-attachments/assets/ac1c20ac-cea4-4789-a0f0-2562516979e6)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by CoolDudeT** [comment]
nvm this is a removed js engine feature lol

**Comment by JordanSantiagoYT** [comment]
This is a removed JS Engine feature, it wasn't needed
