### ISSUE TITLE
Does JS Engine support extrakey as of right now?

### ISSUE THREAD

**Issue by ArinStitch** [JordanSantiagoYT/FNF-JS-Engine#669]
Sorry if you've been getting this one a lot. If it doesn't NATIVELY support extrakey, does it at least support that one lua script that adds it? (Yes there's a script for extrakey in lua, it's really cool actually.)

**Comment by JordanSantiagoYT** [comment]
1. it does not natively support extrakey
2. because of the chart loading system used in this engine, no

**Comment by moxie-coder** [comment]
There is this that uses 0.7 https://github.com/FunkinExtraKeys/FNF-PsychEngine-EK

**Comment by TofpFL** [comment]
@JordanSantiagoYT could someone adopt your chart loading system to handle more than 4k and then put a LUA file in the code to make 6K charts?

**Comment by StinkTheStinker** [comment]
> ...could someone adopt your chart loading system to handle more than 4k and then put a LUA file in the code to make 6K charts?

am i seeing this right???
"adopt"????

**Comment by CoolDudeT** [comment]
No, and Jordan said it never will.

**Comment by imavie** [comment]
this didn't age well

**Comment by moxie-coder** [comment]
might add native ek support somehow
