### ISSUE TITLE
Crash when Ctrl Z

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [JordanSantiagoYT/FNF-JS-Engine#670]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

My game crashed when i used Control + Z, btw please ignore that video in the image.

### Command Prompt/Terminal/Crash logs (if existing)

```
Uncaught Error: Null Object Reference
editors/ChartingState.update() [line 3042]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```
### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

![image](https://github.com/user-attachments/assets/96cdbc5a-fff6-4b17-9399-26fa4d96e6c6)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

noooooooooooooooooodyftgwdjhfgwesdrhjfgjfhnewavfhjemgfwhayjegjek

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
this is yet another bpmTxt crash.
