### ISSUE TITLE
custom ratings help

### ISSUE THREAD

**Issue by PleaseEnterUsernameHere** [JordanSantiagoYT/FNF-JS-Engine#671]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

i want to add like custom rating text
but whenever i add it, it works fine at 100% acc
but as soon as it drops below 100% it reverts to the default quotes

**why do it do dis**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

aside from normal modding stuffs, no

**Comment by PatoFlamejanteTV** [comment]
Can you share a video/screenshot?

**Comment by PleaseEnterUsernameHere** [comment]
![image](https://github.com/user-attachments/assets/01b6fc3b-1f6c-4ae2-badd-8381c8041d30)
this is it at 100%

![image](https://github.com/user-attachments/assets/75cd5c8e-1207-4b78-8650-4035a08ab84f)
this it at literally anything else

idk what to do to fix it
(yes it has custom lines and everythin)

**Comment by PatoFlamejanteTV** [comment]
Did you make a Lua script for changing the quotes? If yes, it maybe is glitching/it's (maybe) not precise at all.

**Comment by PleaseEnterUsernameHere** [comment]
it doesnt need an lua script.. at least i dont think so

**Comment by PleaseEnterUsernameHere** [comment]
> Did you make a Lua script for changing the quotes? If yes, it maybe is glitching/it's (maybe) not precise at all.

and to answer this properly, im not using an lua script

**Comment by JordanSantiagoYT** [comment]
did you follow all these steps correctly? https://github.com/JordanSantiagoYT/FNF-JS-Engine/wiki/Adding-Rating-Quotes

**Comment by PleaseEnterUsernameHere** [comment]
i skipped like the whole making ratingQuotes file and tried to do it directly in `assets/data/ratingQuotes` cuz i thought it would mess with the mod

and after a quick restart and fixin the error i made it all work fine
