### ISSUE TITLE
God the "fire in the hole" keeps popping up way too much

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#678]
### What feature do you want to get added on the **base** engine?

please make an option that can get rid of this or lower the rate of getting this because it was funny at first added but it's not funny anymore now

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by moxie-coder** [comment]
I already added an option to disable that, a long time ago
