### ISSUE TITLE
how do I stop it from doing that

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#679]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

![image](https://github.com/user-attachments/assets/72c8c23d-4c3e-4994-a618-c3e3f556f5ed)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

put a script in the scripts folder that has to do with the UI

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

a

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
sir..

that's a script.

that's an issue with the script, and not the engine itself.

**Comment by daveandbambifan1234** [comment]
> sir..
> 
> that's a script.
> 
> that's an issue with the script, and not the engine itself.

ok

**Comment by daveandbambifan1234** [comment]
change it to conversation(General)
how do I fix the script tho

**Comment by JordanSantiagoYT** [comment]
check that the text's camera isn't set to "camGame"

**Comment by felipe881** [comment]
I want the script pls

**Comment by PatoFlamejanteTV** [comment]
> change it to conversation(General) how do I fix the script tho

ok?

**Comment by PatoFlamejanteTV** [comment]
> change it to conversation(General)

But why exactly you want that?
