### ISSUE TITLE
unused lil bf sprites?

### ISSUE THREAD

**Issue by PleaseEnterUsernameHere** [JordanSantiagoYT/FNF-JS-Engine#680]
### What is your question?

im just curious about something
![image](https://github.com/user-attachments/assets/6fde3e3a-8837-40a4-a11c-0d4bd4f7e8b6)
how exactly are these miss and hey! sprites used for lil bf in the chart editor?

**Comment by JordanSantiagoYT** [comment]
they're unused lol

i can't really remove them from the xml because that would break it

**Comment by PleaseEnterUsernameHere** [comment]
ohhh ok yea that makes sense-

**Comment by PleaseEnterUsernameHere** [comment]
_im reopening this just to ask another question_

how was the unused sprites meant to be used?
liek was the lil bf sprite meant to be a playable thing in the chart editor (yk like when you playtest the chart in the chart editor with `esc`) or was it smth else?

**Comment by felipe881** [comment]
who knows

**Comment by moxie-coder** [comment]
> _im reopening this just to ask another question_
> 
> how were the unused sprites meant to be used? liek was the lil bf sprite meant to be a playable thing in the chart editor (yk like when you playtest the chart in the chart editor with `esc`) or was it smth else?

go ask rozebud cuz idk
