### ISSUE TITLE
I can't color characters using lua scripts

### ISSUE THREAD

**Issue by nate902011** [JordanSantiagoYT/FNF-JS-Engine#681]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Whenever I tried to color boyfriend, girlfriend, an dad characters using either getProperty or doColorTween, it doesn't work.
Here's my code:
```
function onCreate()	
	makeLuaSprite('Farm Farm Bg Asset', 'Farm Farm Bg Asset', 300, 0);
	setLuaSpriteScrollFactor('Farm Farm Bg Asset', 0.85, 0.85);
	scaleObject('Farm Farm Bg Asset', 0.6, 0.6);

	makeLuaSprite('sky_sunset', 'sky_sunset', -500, 0);
	setLuaSpriteScrollFactor('sky_sunset', 0.9, 0.9);
	scaleObject('sky_sunset', 1, 1);

	makeLuaSprite('Farm Ground Asset', 'Farm Ground Asset', -550, 500);
	setLuaSpriteScrollFactor('Farm Ground Asset', 1, 1);
	scaleObject('Farm Ground Asset', 0.75, 0.75);

	makeLuaSprite('Farm Sign Asset', 'Farm Sign Asset', -150, 400);
	setLuaSpriteScrollFactor('Farm Sign Asset', 1, 1);
	scaleObject('Farm Sign Asset', 0.4, 0.4);

	makeLuaSprite('Farm Corn Fence Left Asset', 'Farm Corn Fence Left Asset', -500, 100);
	setLuaSpriteScrollFactor('Farm Corn Fence Left Asset', 1, 1);
	scaleObject('Farm Corn Fence Left Asset', 0.3, 0.3);

	makeLuaSprite('Farm Corn Bag Asset', 'Farm Corn Bag Asset', 1225, 400);
	setLuaSpriteScrollFactor('Farm Corn Bag Asset', 1, 1);
	scaleObject('Farm Corn Bag Asset', 0.3, 0.3);

	makeLuaSprite('Farm Corn Fence Right Asset', 'Farm Corn Fence Right Asset', 1100, 280);
	setLuaSpriteScrollFactor('Farm Corn Fence Right Asset', 1, 1);
	scaleObject('Farm Corn Fence Right Asset', 0.3, 0.3);

	makeLuaSprite('Farm Hill Bg Asset', 'Farm Hill Bg Asset', -500, 75);
	setLuaSpriteScrollFactor('Farm Hill Bg Asset', 0.8, 0.8);
	scaleObject('Farm Hill Bg Asset', 1, 1);

	makeLuaSprite('Farm gm_grassland Bg Asset', 'Farm gm_grassland Bg Asset', 0, 25);
	setLuaSpriteScrollFactor('Farm gm_grassland Bg Asset', 0.75, 0.75);
	scaleObject('Farm gm_grassland Bg Asset', 0.3, 0.3);

	-- sprites that only load if Low Quality is turned off
	if not lowQuality then
	
	end
	
	setProperty('boyfriend.color', getColorFromHex('ffff8fb2'))
	setProperty('dad.color', getColorFromHex('ffff8fb2'))
	setProperty('gf.color', getColorFromHex('ffff8fb2'))
	
    doTweenColor('exampleColorTween', 'Farm gm_grassland Bg Asset', '0xffff8fb2', 0.01, 'quadInOut')
    doTweenColor('exampleColorTween2', 'Farm Hill Bg Asset', '0xffff8fb2', 0.01, 'quadInOut')
    doTweenColor('exampleColorTween3', 'Farm Farm Bg Asset', '0xffff8fb2', 0.01, 'quadInOut')
    doTweenColor('exampleColorTween4', 'Farm Ground Asset', '0xffff8fb2', 0.01, 'quadInOut')
    doTweenColor('exampleColorTween5', 'Farm Corn Fence Left Asset', '0xffff8fb2', 0.01, 'quadInOut')
    doTweenColor('exampleColorTween6', 'Farm Corn Fence Right Asset', '0xffff8fb2', 0.01, 'quadInOut')
    doTweenColor('exampleColorTween7', 'Farm Sign Asset', '0xffff8fb2', 0.01, 'quadInOut')
    doTweenColor('exampleColorTween8', 'Farm Corn Bag Asset', '0xffff8fb2', 0.01, 'quadInOut')
	
	addLuaSprite('sky_sunset', false);
	addLuaSprite('Farm gm_grassland Bg Asset', false);
	addLuaSprite('Farm Hill Bg Asset', false);
	addLuaSprite('Farm Farm Bg Asset', false);
	addLuaSprite('Farm Ground Asset', false);
	addLuaSprite('Farm Corn Fence Left Asset', false);
	addLuaSprite('Farm Corn Fence Right Asset', false);
	addLuaSprite('Farm Sign Asset', false);
	addLuaSprite('Farm Corn Bag Asset', false);
	
	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end
```
I know it only says setProperty, but with either getProperty or doColorTween, it doesn't work regardless.
![NOT COLORED LIKE WTF IS GOING ON](https://github.com/user-attachments/assets/bf78bf7a-dbd6-4ef1-8a21-b08e9ccd07a8)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
getColorFromHex is supposed to be a 6-digit value, not an 8-digit value

**Comment by NAEL2XD** [comment]
> getColorFromHex is supposed to be a 6-digit value, not an 8-digit value

Even if it's a 6-digit value it still gors thru black and red if I used doTweenColor

**Comment by nate902011** [comment]
yeah, so i have no idea what i'm doing wrong cuz still nothing's happening. even when i put it as a 6-digit value, the characters are still the same and unchanged.
![image_2024-10-23_114430962](https://github.com/user-attachments/assets/0c144399-65c2-442c-b947-0b88fa86e5d9)

**Comment by nate902011** [comment]
doTweenColor works for the bg assets but everything else i've tried (from gamebanana or here) still doesn't work for the characters.

**Comment by JordanSantiagoYT** [comment]
well, i did this to change the bfs color in the bambiBGNight stage i did, and it works:

`doTweenColor('boyfriendColorTween', 'boyfriend', '0xff878787', 0.01, 'quadInOut')`

for using the setProperty thing, it's this
`setProperty('boyfriend.color', 000000)`
which sets BF's color to black

`setProperty('boyfriend.color', getColorFromHex('ffffff'))`
sets bf's color back to normal

**Comment by nate902011** [comment]
idk what's up but my code just doesn't wanna work. when i use the doTweenColor code you used and save, nothing happens.

**Comment by JordanSantiagoYT** [comment]
do you possibly have another script that could be changing bf's color?

**Comment by nate902011** [comment]
no, that's the only one.

**Comment by nate902011** [comment]
does this `doTweenColor('boyfriendColorTween', 'boyfriend', '0xffff8fb2', 0.01, 'quadInOut')` work for you?

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/1340ee29-a438-43c1-a6d7-c28a8c8a0875)
yep

**Comment by nate902011** [comment]
well, i doesn't work when i try it for some reason.

**Comment by nate902011** [comment]
let me try reinstalling js.

**Comment by nate902011** [comment]
still doesn't work

**Comment by nate902011** [comment]
it also doesn't work in psych 0.7.3 (1.0 rn is not great). idk what's happening.
![Screenshot 2024-10-23 161529](https://github.com/user-attachments/assets/d55ff18a-35d8-4fe9-b2cb-af5f242f96b7)

**Comment by JordanSantiagoYT** [comment]
wait

try adding `luaDebugMode = true` in onCreate or onCreatePost and see if any error pops up

or change the onCreate function in lua to onCreatePost, since that triggers after everything's loaded

**Comment by nate902011** [comment]
it works now. i changed the onCreate to onCreatePost.
![image_2024-10-23_163635342](https://github.com/user-attachments/assets/8eb0a092-fb29-446d-b957-63f2b3acea04)
