### ISSUE TITLE
Unable to enter "Mods" section of the main menu

### ISSUE THREAD

**Issue by Loopedrage** [JordanSantiagoYT/FNF-JS-Engine#682]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Title says it all-- the game would simply just crash if I ever tried touching it, and I've had this issue ever since I started modding here but only until now did it ever start giving me a message upon closure so I had no real way of relaying this information to find a fix

### Command Prompt/Terminal/Crash logs (if existing)

A "crash" folder literally does not exist on my build for whatever reason but I can finally get some semblance of a crash log

<img width="554" alt="Screenshot 2024-10-23 at 2 48 29 PM" src="https://github.com/user-attachments/assets/5b9aff1e-2e1a-4eac-b6e4-c1675ec1dc34">

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Step 1: open the game
Step 2: go to "Mods" in the main menu
Step 3: game dead yippee !

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
from what i can see, there's a problem with opening the modsList txt

i'm not sure what causes it since i don't use macOS, so

**Comment by Loopedrage** [comment]
ok so I just found out that modsList.txt is another thing that's just flat out missing from my game, just like the crash folder

I tried just adding it manually but it leads to the same error

**Comment by felipe881** [comment]
well I didn't get this error but I got a secret message saying no mods installed press b to install a mod bi**h

**Comment by PatoFlamejanteTV** [comment]
Is your `modList.txt` file valid? Can you send the file contents here?

**Comment by PatoFlamejanteTV** [comment]
> "yes rico kaboom" got me

what languages do you speak? Você fala português?

**Comment by Loopedrage** [comment]
> Is your `modList.txt` file valid? Can you send the file contents here?

It just straight up doesn't exist for me lmao, I assume just me adding it in myself doesn't make it a valid one so I'm not quite sure how to go about it

**Comment by PatoFlamejanteTV** [comment]
> > Is your `modList.txt` file valid? Can you send the file contents here?
> 
> It just straight up doesn't exist for me lmao, I assume just me adding it in myself doesn't make it a valid file so I'm not quite sure how to go about it

I think its on the `assets\preload` folder or something else.

**Comment by JordanSantiagoYT** [comment]
modsList is located at the same folder, where JSE is in.

**Comment by Loopedrage** [comment]
Great news! `assets/preload` is also an apparently nonexistent directory for me. There is an assets folder, but no preload

I swear on my life I haven't modified anything with this build other than my own stuff in the mods folder

**Comment by NAEL2XD** [comment]
> Great news! `assets/preload` is also an apparently nonexistent directory for me. There is an assets folder, but no preload
> 
> I swear on my life I haven't modified anything with this build other than my own stuff in the mods folder
> 
> I have vanilla 0.7 which has been my only way so far that any of this stuff is supposed to be there, but trying to put them in manually doesn't seem to do anything probably because I am not using source

`assets/preload` is only for source code

**Comment by StinkTheStinker** [comment]
yeah. thats only source code

**Comment by Loopedrage** [comment]
Is there anything I can possibly do the get around this, then? It doesn't make very much sense to me that bits and pieces of the engine are just missing here but they aren't anything more than a little-more-than-mild inconveniences

**Comment by StinkTheStinker** [comment]
"cd [the path where the exe is]"
put that into cmd and do "JSEngine.exe"
see what pops up right before the crash

**Comment by StinkTheStinker** [comment]
tell me what it says

**Comment by StinkTheStinker** [comment]
ill check tommorow, at my timezone at least

**Comment by Loopedrage** [comment]
So... the engine will apparently just decide to not crash when I boot it up via cmd

First check met me with that "no mods installed" thing (I do have mods installed, the engine is lying to me)

Second check onward shows me the mods I have, and acts as if everything is completely normal, but it will still crash with the same error message when I try to enter the mods section when opening up the engine without cmd

Do I just have to open the engine from cmd as if I'm running source then??

**Comment by StinkTheStinker** [comment]
> Do I just have to open the engine from cmd as if I'm running source then??
no, performance issue maybe. also, can you send me a screenshot of the mods folder (literally the mods folder)

**Comment by StinkTheStinker** [comment]
> > Do I just have to open the engine from cmd as if I'm running source then??
> 
> no, performance issue maybe. also, can you send me a screenshot of the mods folder (literally the mods folder)

scratch that, didnt read the 3rd sentence.

can you send the the mod folder of it? let me figure it out myself, ill update when i figure it out.

**Comment by Loopedrage** [comment]
[alright here you go i guess](https://drive.google.com/file/d/1U4K9oUoQpTufs6ivC0fvchnHmH59rsae/view?usp=sharing)

its just two separate folders in there but they should still function as "installed" mods or whatever

**Comment by StinkTheStinker** [comment]
ok, i think the reason is that one of the pack.json files are in the incorrect coding.
the pack.json for test-mod is ment to be:
```
{
	"name": "test",
	"description": "this is a test",
	"restart":false,
	"color": [170, 0, 255]
}

```

**Comment by Loopedrage** [comment]
This doesn't seem to be it, same error and everything but vanilla psych engine has no problem taking said mod files as they are

**Comment by StinkTheStinker** [comment]
js engine is not fully suitable with mac i think, which will take a while for it to be fully suitable

**Comment by Loopedrage** [comment]
Oh well. Knowing responses I've had with previous issues, I doubt it will ever happen but I'm honestly just glad the engine is even accessible to mac at all

Thanks for trying though
