### ISSUE TITLE
a bug i accidentally found (idk what device was)

### ISSUE THREAD

**Issue by felipe881** [JordanSantiagoYT/FNF-JS-Engine#683]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

when the song finishes I pressed enter the fade goes away and when I restarted the song the opponent was now bf instead of angey bambi and the inst now was the default song from main menu
fun fact: I wanted to chart it
### Command Prompt/Terminal/Crash logs (if existing)

game didnt crash

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

step 1: press enter on the end of the song 
end: done
### Are you modding a build from source or with Lua?

Lua

### What is your build target?

I don't rembember

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by felipe881** [comment]
I hope Jordan Santiago sees this

**Comment by felipe881** [comment]
ITS BEEN 49 MINS AND HE STILLS NOT SEES THIS

**Comment by Loopedrage** [comment]
Chill bruh he's just one dude, he'll see it when he does

**Comment by felipe881** [comment]
ok

**Comment by moxie-coder** [comment]
dude how do you not remember what you used for this

**Comment by felipe881** [comment]
uhh

**Comment by felipe881** [comment]
idk

**Comment by felipe881** [comment]
I added a fun fact
