### ISSUE TITLE
i cant render in pc 

### ISSUE THREAD

**Issue by felipe881** [JordanSantiagoYT/FNF-JS-Engine#684]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

whenever I open renderlol.bat at the end it says that ffmpeg it's not a file or batch or idk

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

same as the previous issue nope

**Comment by felipe881** [comment]
I hope he helps me

**Comment by felipe881** [comment]
on that ofc

**Comment by felipe881** [comment]
I rendered on multiliosis

**Comment by JordanSantiagoYT** [comment]
You're not using Classic Rendering Mode.

**Comment by felipe881** [comment]
it didn't work

**Comment by felipe881** [comment]
I putted ffmpeg on the js engine folder

**Comment by JordanSantiagoYT** [comment]
> I putted ffmpeg on the js engine folder

classic rendering mode puts images in a folder. you're likely using NEW rendering mode, which makes a video file out of the song you're rendering. check if that existx

**Comment by felipe881** [comment]
I saw a typo but yes I checked (maybe)

**Comment by JordanSantiagoYT** [comment]
you MAYBE checked??

alr, send me a screenshot of your gameRenders folder

**Comment by felipe881** [comment]
sorry to send a photo I need to log in pc

**Comment by felipe881** [comment]
and I can't log in PC:(

**Comment by felipe881** [comment]
but I checked the files only (without photo)

**Comment by felipe881** [comment]
but I can write it

**Comment by felipe881** [comment]
on here lol

**Comment by felipe881** [comment]
files: multiliosis readme.txt render lol.bat

**Comment by JordanSantiagoYT** [comment]
multiliosis is a folder..

**Comment by felipe881** [comment]
yea

**Comment by felipe881** [comment]
I love this wonderful engine

**Comment by NAEL2XD** [comment]
how come you don't know how to send screenshot?? it's just pressing print screen and pasting by pressing ctrl + v

**Comment by felipe881** [comment]
bro I CAN'T LOG IN PC

**Comment by felipe881** [comment]
if you say that again I'll close this

**Comment by moxie-coder** [comment]
![image](https://github.com/user-attachments/assets/5b490428-ac8a-40af-b724-d03daead8cc5)

something tells me you can't be on github

**Comment by moxie-coder** [comment]
or the internet at all

**Comment by moxie-coder** [comment]
@JordanSantiagoYT btw block them, so they can't keep coming here
