### ISSUE TITLE
how do i make no lag in freeplay

### ISSUE THREAD

**Issue by felipe881** [JordanSantiagoYT/FNF-JS-Engine#685]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

when I have too much songs in free play it starts lagging the baddest I got: 22 fps when I move: 20

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

same as the previous issue (its been 2 issues lmao)nope

**Comment by felipe881** [comment]
I'm not gonna close this maybe

**Comment by JordanSantiagoYT** [comment]
simply remove some freeplay weeks

**Comment by moxie-coder** [comment]
you basically answered your own question
