### ISSUE TITLE
THIS BUG HAPPENS ME EVERYTIME

### ISSUE THREAD

**Issue by felipe881** [JordanSantiagoYT/FNF-JS-Engine#686]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

when I'm on chart editor when it's about to go in a section it skips it idk

### Command Prompt/Terminal/Crash logs (if existing)

*No Response*

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Step 1: go to chart editor
End: you did it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
that's becausd when you reach sectionEndTime for a section, it goes to the next one

that's what it's supposed to do..

**Comment by moxie-coder** [comment]
intentional game design
