### ISSUE TITLE
why is the song audio not even loading or starting 

### ISSUE THREAD

**Issue by kyleinvoice** [JordanSantiagoYT/FNF-JS-Engine#687]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

when i cilck it it did not work? yes i check the name and copy and pested it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by moxie-coder** [comment]
can you atleast be more specific and provide more details

**Comment by StinkTheStinker** [comment]
are the file names even right

**Comment by kyleinvoice** [comment]
yes

**Comment by kyleinvoice** [comment]
i am in the latess verson

**Comment by kyleinvoice** [comment]
here 

Uploading Screen Recording 2024-10-24 212943.mp4…

**Comment by kyleinvoice** [comment]
Uploading Screen Recording 2024-10-24 213312.mp4…

**Comment by kyleinvoice** [comment]
https://github.com/user-attachments/assets/df334854-6e21-46a0-8170-36800884c8b0

**Comment by kyleinvoice** [comment]
> can you atleast be more specific and provide more details


Uploading Screen Recording 2024-10-24 213312.mp4…

**Comment by kyleinvoice** [comment]
> can you atleast be more specific and provide more details

here

**Comment by JordanSantiagoYT** [comment]
> Screen.Recording.2024-10-24.213312.mp4

it's possible that the folder for the song name exists in (mods/(YourMod)/songs/) exists, but Inst.ogg doesn't.
either that or you imported an MP3 instead of an ogg

**Comment by kyleinvoice** [comment]
it say type :ogg

**Comment by kyleinvoice** [comment]
> > Screen.Recording.2024-10-24.213312.mp4
> 
> it's possible that the folder for the song name exists in (mods/(YourMod)/songs/) exists, but Inst.ogg doesn't. either that or you imported an MP3 instead of an ogg

it say type :ogg

**Comment by JordanSantiagoYT** [comment]
it could also be possible that the song files are in (mods/YourMod), but the mod directory you chose before entering the editor wasn't "YourMod"

**Comment by kyleinvoice** [comment]
i will try

> it could also be possible that the song files are in (mods/YourMod/songs), but the mod directory you chose before entering the editor wasn't "YourMod"

i will try

**Comment by kyleinvoice** [comment]
> it could also be possible that the song files are in (mods/YourMod/songs), but the mod directory you chose before entering the editor wasn't "YourMod"

i guess i will go for da old verson 1.31.0
