### ISSUE TITLE
Ratings don't work at all.

### ISSUE THREAD

**Issue by nate902011** [JordanSantiagoYT/FNF-JS-Engine#690]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

(I've had this ever since I updated JS Engine) The rating images don't show up when I hit notes (drive video below for demonstration), the miss rating still works thought. And no, I had no mods enabled.
https://drive.google.com/file/d/1NRKRHcs_tLxGXgKE6tF-6jlOojQ6ZE6f/view?usp=sharing
![Screenshot 2024-10-24 201945](https://github.com/user-attachments/assets/41f964a7-ff5d-4e46-a82b-80984367495c)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Updating JS from _V1.35.0_ to _V1.36.0_ directly in-game, not through Github.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
it's possible that you turned on "Even LESS Botplay Lag".

**Comment by nate902011** [comment]
yeah that fixed it
