### ISSUE TITLE
JS Engine : Memory leaks after 2 songs

### ISSUE THREAD

**Issue by SyncGit12** [JordanSantiagoYT/FNF-JS-Engine#693]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I was just debugging my mod and randomly it started leaking memory, Same on latest versions of the Engine

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

# tutorial for da thing!!111!1!!!1111

steoep oen 

loadsa a song

stwesrp twoe

sloasd antoeher song

boomhgo

mermeoy lekasks11!!11

## Understandable version

Step 1,

Load a song

Step 2,

Load another song

boom

memory leaks

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

working on mod

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment]
what is your current amount of ram

**Comment by StinkTheStinker** [comment]
if you dont know how much ram you have, so ctrl+shift+esc, that will open task manager, then click on performance. it should show you the specs you have

**Comment by moxie-coder** [comment]
this engine has memory leaks unlike psych tbh

**Comment by SyncGit12** [comment]
that gave me an idea

spoiler alert:






























nothin' engine will not have mem leaks

**Comment by SyncGit12** [comment]
also my current amount of ram is 16 gb

**Comment by KernelTech11** [comment]
**### **_2PWN3J3OIUHHYGFTR, SYERHGHIOWIUY3_****

**Comment by PatoFlamejanteTV** [comment]
bizarre

**Comment by SyncGit12** [comment]
very bizzare for a 2017 computer that supports windows 11 restarts itself with force

**Comment by StinkTheStinker** [comment]
> very bizzare for a 2017 computer that supports windows 11 restarts itself with force

well, that might be why

**Comment by SyncGit12** [comment]
fool learn about computers and how they work, fucking idiot

**Comment by StinkTheStinker** [comment]
> fool learn about computers and how they work, fucking idiot

how about you learn on how to not be a fucking bitch for 1 minute straight

fool
