### ISSUE TITLE
what does this mean

### ISSUE THREAD

**Issue by zandereal1** [JordanSantiagoYT/FNF-JS-Engine#697]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

trying to make a fnf mod and was trying to get my character in but got this error

"Uncaught Error: Null Object Reference
editors/CharacterEditorState.loadChar() [line 1072]
editors/CharacterEditorState.addSettingsUI() [line 384]
FlxUIDropDownMenuCustom.onClickItem() [line 512]
FlxUIDropDownMenuCustom.makeListButton() [line 361]
flixel/ui/FlxButton.onUpHandler() [line 521]
flixel/addons/ui/FlxUITypedButton.onUpHandler() [line 1182]
flixel/addons/ui/FlxUIButton.onUpHandler() [line 362]
flixel/ui/FlxButton.onUpEventListener() [line 507]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
" I need help figuring out what to do.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
does your character json have any animations??

**Comment by zandereal1** [comment]
it should, I exported the json using a program to make a spritesheet so it should work but it just doesn't

**Comment by nxvelveteen** [comment]
What program did you use?

**Comment by zandereal1** [comment]
i went online and used codeandweb.com

**Comment by moxie-coder** [comment]
> i went online and used codeandweb.com

that’s not what you use here, there’s a character editor for a reason

**Comment by zandereal1** [comment]
I tried using the character editor, I saw my character on the list and pressed it and then I got the error

**Comment by Loopedrage** [comment]
You can't make your character .json from the dropdown list, you're supposed to type in the character spritesheet directory and the character editor will help you make the proper .json file from there
