### ISSUE TITLE
Dumb Idea For Engine

### ISSUE THREAD

**Issue by einbuis07** [JordanSantiagoYT/FNF-JS-Engine#699]
### What feature do you want to get added on the **base** engine?

Very Dumb Idea add On options category "Chart Editor" and you can disable features enable change or something like
Super Duper Extreme Dumb Idea :| i just get Super Mega duper dumb ideas :|||

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by JordanSantiagoYT** [comment]
1. you failed the test
2. No
