### ISSUE TITLE
bugs that I caught

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#704]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

https://github.com/user-attachments/assets/3abc3d19-03b4-4534-82d2-2d96240450bb

https://github.com/user-attachments/assets/9c4fca01-6b80-48cf-8f15-31d958555d71

https://github.com/user-attachments/assets/e5c46045-6cb0-4d5f-8932-910d55c845df

### Command Prompt/Terminal/Crash logs (if existing)

a

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

1. press f2 at the right frame at the end of a song
2.  while the chart is moving press the must-hit section
3. idk how to explain that one

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

a

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by daveandbambifan1234** [comment]
the song continued in the character editor screen

**Comment by daveandbambifan1234** [comment]
my chart is completely ruined because the screenshot bug is also a soft lock

**Comment by JordanSantiagoYT** [comment]
Videos 1 and 3 have already been fixed in newer updates.
I will not be fixing 2.
