### ISSUE TITLE
1 fps after copying section to the next 1 time

### ISSUE THREAD

**Issue by trademarkman** [JordanSantiagoYT/FNF-JS-Engine#706]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I created a spam song and i am trying to chart it with a 512x spam multiplier. However, when I'm about 90% finished 3 minutes into the song and press 'Copy to Next Section' once, the FPS drops to 1 and stays there.

### Command Prompt/Terminal/Crash logs (if existing)

no crash logs.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

no

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by trademarkman** [comment]
this happened multiple times with other spam songs

**Comment by JordanSantiagoYT** [comment]
that's more because of ram usage and something i cannot control
