### ISSUE TITLE
Character Editor crash

### ISSUE THREAD

**Issue by Piggymaster1222** [JordanSantiagoYT/FNF-JS-Engine#711]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I was trying to edit some characters in my mod like changing their icons but...this happened.

### Command Prompt/Terminal/Crash logs (if existing)

[JSEngine_2024-11-01_13'08'52.log](https://github.com/user-attachments/files/17602409/JSEngine_2024-11-01_13.08.52.log)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

not sure if there is any way around it but I have no clue what is happening.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed the BF icons as well as adding more variants of the icon.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
closing as duplicate due to the newly created issue from that discussion that was made before
