### ISSUE TITLE
Opening Character Editor crashes JS Engine 1.37.0

### ISSUE THREAD

**Issue by CoolDudeT** [JordanSantiagoYT/FNF-JS-Engine#714]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I don't know why, but when you try to open the character editor, THE GAME FUCKING CRASHES EVERY TIME! I don't even have any scripts installed!

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: Error #2007: Parameter text must be non-null.
openfl/text/TextField.set_text() [line 3099]
flixel/text/FlxText.set_text() [line 633]
flixel/addons/ui/FlxInputText.set_text() [line 496]
editors/CharacterEditorState.reloadCharacterOptions() [line 1119]
editors/CharacterEditorState.create() [line 208]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.update() [line 726]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

1. Open JS Engine 1.37.0
2. Press 7 on the menu
3. Go to character editor
4. game should crash!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
sigh.

this was already fixed in a recent commit
