### ISSUE TITLE
JS Engine : why are her icons like that

### ISSUE THREAD

**Issue by SyncGit12** [JordanSantiagoYT/FNF-JS-Engine#715]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

why are her icons like that

### Command Prompt/Terminal/Crash logs (if existing)

None.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

https://github.com/user-attachments/assets/5109697d-38ef-4f78-a50b-70a2330382fd

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

just trying a old mod

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment]
is the icon file the right res?

**Comment by SyncGit12** [comment]
yes?

**Comment by SyncGit12** [comment]
bf and star's icon should be the same res

**Comment by JordanSantiagoYT** [comment]
is star's icon 450x150?

if so, make sure there's 3 icons MAX.

**Comment by SyncGit12** [comment]
theres 3 icons

**Comment by SyncGit12** [comment]
![icon-star](https://github.com/user-attachments/assets/daac552d-2081-4ce0-95fc-5515a17bdc5d)

**Comment by JordanSantiagoYT** [comment]
problem found

the width for your png is 451x150
for it to work properly, you need to reduce the width by 1 pixel

**Comment by SyncGit12** [comment]
i tried. it didnt work

**Comment by StinkTheStinker** [comment]
> i tried. it didnt work

did you save it correctly

**Comment by StinkTheStinker** [comment]
make sure if it's the exact file name and file type

**Comment by SyncGit12** [comment]
yes, and yes

**Comment by StinkTheStinker** [comment]
> yes, and yes

is it in the right directory

**Comment by StinkTheStinker** [comment]
wait
did you change the icon with the game open
if so, re-open it

**Comment by SyncGit12** [comment]
no.

**Comment by JordanSantiagoYT** [comment]
> i tried. it didnt work

![387360871-daac552d-2081-4ce0-95fc-5515a17bdc5d](https://github.com/user-attachments/assets/75929734-c868-49b0-ad8b-1519bcaef674)
try this

**Comment by SyncGit12** [comment]
it works, but there's another one
![icon-cap](https://github.com/user-attachments/assets/9cb9ebe3-fccd-4396-9e47-826fc249d0f6)

**Comment by StinkTheStinker** [comment]
just copy and paste the image onto the one jordan sent

**Comment by JordanSantiagoYT** [comment]
![387417897-9cb9ebe3-fccd-4396-9e47-826fc249d0f6](https://github.com/user-attachments/assets/da6c0581-e2b2-4ded-93f9-18a33d5c29c7)

**Comment by SyncGit12** [comment]
thanks, also i did it.

3d on fnf.
![native 3d](https://github.com/user-attachments/assets/cad45d5c-6cba-4dd7-8996-23e6629223da)
