### ISSUE TITLE
Looking for Andriod Build

### ISSUE THREAD

**Issue by AndreKaneVDole** [JordanSantiagoYT/FNF-JS-Engine#716]
### What is your question?

Wheres the Andriod Build 1.37.1

**Comment by JordanSantiagoYT** [comment]
android port currently has an issue that makes the ios version unable to compile. until this is fixed mobile builds for 1.37.1 won't be available

**Comment by moxie-coder** [comment]
> ios port currently has an issue that makes it unable to compile. until this is fixed mobile builds for 1.37.1 won't be available

you could just compile android, separate from iOS

**Comment by JordanSantiagoYT** [comment]
> you could just compile android, separate from iOS, instead of removing both

there's 2 problems with that

1. even if i compiled the release builds, both of them have to complete or the Release build task won't be done
2. even if i just got the android build from the workflow, trying to upload it throws a "We're sorry, but we couldn't process that file."

**Comment by JordanSantiagoYT** [comment]
closing because android 1.37.1 build is published

small note is that it's still 1.37.0, but this will be fixed shortly after the updated 1.37.1 build compiles

**Comment by moxie-coder** [comment]
> > you could just compile android, separate from iOS, instead of removing both
> 
> there's 2 problems with that
> 
> 1. even if i compiled the release builds, both of them have to complete or the Release build task won't be done
> 2. even if i just got the android build from the workflow, trying to upload it throws a "We're sorry, but we couldn't process that file."

you could just do `continue-on-error: true` for the workflow

**Comment by JordanSantiagoYT** [comment]
build has been added, closing issue
