### ISSUE TITLE
JS Engine Update Issue in the 1.37 series

### ISSUE THREAD

**Issue by VentekOFFICIAL** [JordanSantiagoYT/FNF-JS-Engine#718]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Every time I update JS Engine to 1.37.1, it does the update, but when it reaches 100%, the game freezes and crashes, but also opens a new JS Engine tab, but it doesn't install the update at all whatsoever.

### Command Prompt/Terminal/Crash logs (if existing)

![Screenshot 2024-11-02 140856](https://github.com/user-attachments/assets/5a431651-e54c-4473-a535-d2ac85e75c11)
I tried screenshotting the tab that was updating JS Engine but it wouldn't let me, this was the 2nd time I updated 1.37.0 to 1.37.1

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
It's possible that because of your device, the game doesn't close quickly enough for CMD to detect that JSE is closed, and the EXE isn't replaced as a result.

**Comment by JordanSantiagoYT** [comment]
The only fix for this would be to download the update off GitHub and install it manually.

**Comment by Lenancha** [comment]
> The only fix for this would be to download the update off GitHub and install it manually.

I did try to install the engine manually a few times but it seems like you do also have to delete some of the old saves from older versions of the engine just to make sure it does not crash and interfear with the newer versions as far as I am aware.
