### ISSUE TITLE
animated creditpopup

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-JS-Engine#720]
### What feature do you want to get added on the **base** engine?

is it possible to make animated credit bar's work on the creditpopup

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by JordanSantiagoYT** [comment]
it already does

simply use a custom heading, but this time the heading must have an XML file.
The animation in the XML must be named "idle"
