### ISSUE TITLE
An error when i try to play my song.

### ISSUE THREAD

**Issue by DuckkFnF** [JordanSantiagoYT/FNF-JS-Engine#721]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I delete all lua scripts in this song but it didn't work. 

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: Null Object Reference
stages/Limo.update() [line 92]
flixel/group/FlxGroup.forEach() [line 770]
stages/Limo.update() [line 91]
MusicBeatState.update() [line 110]
MusicBeatState.stagesFunc() [line 221]
MusicBeatState.update() [line 109]
PlayState.update() [line 4136]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment]
are the stage json's files right

**Comment by JordanSantiagoYT** [comment]
this will be fixed in a commit i'm about to push.

**Comment by JordanSantiagoYT** [comment]
that commit was supposed to close this issue
