### ISSUE TITLE
When reloading json in chart editor it crashes

### ISSUE THREAD

**Issue by AlienCat65** [JordanSantiagoYT/FNF-JS-Engine#725]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

So i was trying to chart a song and i wanted to save progress so i saved and when i came back to keep charting the song it crashed

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: Null Object Reference
flixel/sound/FlxSound.updateTransform() [line 595]
flixel/sound/FlxSound.set_group() [line 721]
flixel/sound/FlxSoundGroup.remove() [line 52]
flixel/system/frontEnds/SoundFrontEnd.destroySound() [line 327]
flixel/system/frontEnds/SoundFrontEnd.destroy() [line 319]
flixel/FlxGame.switchState() [line 613]
flixel/FlxGame.update() [line 726]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Reloading JSON in chart editor.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
this occurs at random, and therefore i cannot fix it

**Comment by StinkTheStinker** [comment]
json got corrupted probably
