### ISSUE TITLE
JSE freezes when going through the file explorer to save charts

### ISSUE THREAD

**Issue by null0346** [JordanSantiagoYT/FNF-JS-Engine#726]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

whenever i try to save a chart, this happens
![jsebug](https://github.com/user-attachments/assets/4d712f49-6e06-48d6-9cec-5d7bc9814167)

### Command Prompt/Terminal/Crash logs (if existing)

it doesnt create a crash log

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

all i gotta do is just save a chart, even the test song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
that's def not supposed to happen. the only possible cause i could point out is not possible, since that was patched out long ago

**Comment by null0346** [comment]
dang

**Comment by StinkTheStinker** [comment]
the file explorer is not responding, which is maybe a performance issue

never saw that happen to me

**Comment by StinkTheStinker** [comment]
can someone close this as not planned when its been a week (7 or 5 days)

**Comment by null0346** [comment]
sure

**Comment by null0346** [comment]
ok so turns out it was probably pause on focus lost or whatever the option name is being disabled

**Comment by StinkTheStinker** [comment]
> ok so turns out it was probably pause on focus lost or whatever the option name is being disabled

no, doesnt happen to me
