### ISSUE TITLE
add a backup save system in case the engine stops responding

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#728]
### What feature do you want to get added on the **base** engine?

I decided to request this feature because I don't want to lose my chart data

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by PatoFlamejanteTV** [comment]
Pretty cool ngl, but it could lag with 1 MB< charts

**Comment by moxie-coder** [comment]
there's already an autosave feature in the chart editor, but I could improve it
