### ISSUE TITLE
infinite Miss sound bug

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#729]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

when you turn on Miss sound and Miss at the right time, it will repeat infinitely
(warning this wasn't on a spammy song)

### Command Prompt/Terminal/Crash logs (if existing)

simply turning on Miss sound and missing notes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

its a mod, not a code edit

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
this isn't something i can fix, because the way the miss sound is played is stupid.

this also applies to denpa lol

**Comment by moxie-coder** [comment]
I've not been able to reproduce myself

**Comment by StinkTheStinker** [comment]
just turn off the miss sound in the options menu
if it does not work, i have no clue how to fix it
