### ISSUE TITLE
cuando inicio el js engine sale esto...

### ISSUE THREAD

**Issue by bambbbb** [JordanSantiagoYT/FNF-JS-Engine#731]
esque cuando abro la aplicacion primero empieza con el fondo negro, y cuando le doy enter de ahi aparece la portada del fnf y le doy otra vez enter y aparece esto. es otra version por se acaso pero no creo q deba ser un problema

![Captura](https://github.com/user-attachments/assets/0feae750-c302-4177-aad9-23e2fc5e4e97)

**Comment by moxie-coder** [comment]
parece que su instalación podría haberse dañado, intente reinstalarla, pero también sería útil si proporcionara más información además de eso si la modifica

**Comment by StinkTheStinker** [comment]
compruebe si el json del escenario es incorrecto, incluido el carácter jsons (eso está en la canción)

**Comment by JordanSantiagoYT** [comment]
Además, ¿por qué estás usando 1.20.1? (puedo ver la versión en el ss jajaja)

**Comment by moxie-coder** [comment]
Oh, acabo de darme cuenta, jajaja

**Comment by StinkTheStinker** [comment]
what the sig-

**Comment by bambbbb** [comment]
donde se encuentra el json del escenario...

**Comment by bambbbb** [comment]
no entiendo, como q esta en la cancion del json del escenario y caracters

**Comment by StinkTheStinker** [comment]
Me refiero literalmente al escenario y al personaje json.

mods>etapas>etapa.json
mods>personajes>chaar.json

**Comment by bambbbb** [comment]
> Además, ¿por qué estás usando 1.20.1? (puedo ver la versión en el ss jajaja)

psss por algo... (no es por ser divergencer) pero solo para ver en el chart editor de la s49 de como hizo el gw_ola para multiples caracterers y en los archivos..

**Comment by StinkTheStinker** [comment]
qué

**Comment by moxie-coder** [comment]
> > Además, ¿por qué estás usando 1.20.1? (puedo ver la versión en el ss jajaja)
> 
> psss por algo... (no es por ser divergencer) pero solo para ver en el chart editor de la s49 de como hizo el gw_ola para multiples caracterers y en los archivos..

bueno, nada de esto tiene sentido, así que lo bloquearé ahora. te sugiero que actualices porque no puedo brindar soporte para esta versión
