### ISSUE TITLE
Freeplay song error

### ISSUE THREAD

**Issue by RedBl0bYT** [JordanSantiagoYT/FNF-JS-Engine#736]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

After I was done making a character for my mod I went to freeplay and tried to go into one of the songs but then there was an error

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

![image_2024-11-09_205945621](https://github.com/user-attachments/assets/948fa3b3-15d6-4f04-ba23-86a49bfbe296)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only made the character and that's it

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
1. outdated version of jse
2. in the context of the error, you have a note splash image but the xml is either incorrect or doesn't exist

**Comment by JordanSantiagoYT** [comment]
JUST REALIZED

WHY DO YOU HAVE SO MANY TABS OPEN???????
![image](https://github.com/user-attachments/assets/3b7c89d7-d115-4dd1-9537-8b0c7fd244de)

**Comment by StinkTheStinker** [comment]
i noticed first

**Comment by null0346** [comment]
> JUST REALIZED
> 
> WHY DO YOU HAVE SO MANY TABS OPEN??????? ![image](https://private-user-images.githubusercontent.com/61796448/384748528-3b7c89d7-d115-4dd1-9537-8b0c7fd244de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0Mjc2NzUsIm5iZiI6MTczMTQyNzM3NSwicGF0aCI6Ii82MTc5NjQ0OC8zODQ3NDg1MjgtM2I3Yzg5ZDctZDExNS00ZGQxLTk1MzctOGIwYzdmZDI0NGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE2MDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMGZjYmQxZjgwNDA1MTMyMTA4ZjU4YjRjYjg4NzdjMDIyZjA4M2NjOGNlNDE2ZGE3ODYyMmZkNWJjNjMwZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h2Rej3wPOjdDCvVMdn5OHN992uMh2eApGKY4p7Hz5_w)

WHAT 😭

**Comment by NAEL2XD** [comment]
close this? It looks so inactive and it's almost a month in without any comments
