### ISSUE TITLE
the nefarious character editor text field zoom bug is in this one

### ISSUE THREAD

**Issue by peashooterman3** [JordanSantiagoYT/FNF-JS-Engine#737]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

zooming in or out in the character editor moves the hitboxes of all text fields on screen, offsetting them from their visual positions. it's annoying and i don't want to have to press r to fix it manually.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

change the camera zoom and try to click on the text fields. that's it. (video example)

https://github.com/user-attachments/assets/4b984cb3-2f38-4215-ab9c-105fb37a12a9

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, this is vanilla js engine

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment]
its been like this since 2022 or 2023, theres no way of fixing this, you just gotta stick with this for now and just use the default zoom thats in the char editor (which is just pressing r to reset the zoom)

**Comment by peashooterman3** [comment]
oh ok

**Comment by StinkTheStinker** [comment]
if you want to. you can zoom out to preview some things, but do need to press 'R' if you are going to change something
