### ISSUE TITLE
How do I add custom shared noteskins to newer versions of js?

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-JS-Engine#739]
### What is your question?

pretty much the only reason i haven't updated past 1.28 is because i want to use the agoti noteskin which isnt in option in later versions. i found a temperary solution but i know it will be reverted if i update again https://drive.google.com/file/d/1CMOH9_qJ4Z99BLYGUVLg0ps54yfCm4Ry/view?usp=drive_link (holy shit why does obs make my recordings look so bad)

**Comment by StinkTheStinker** [comment]
dude

**Comment by StinkTheStinker** [comment]
the noteskin needs to be in mods
and copy the txt file having only the custom noteskins

mods>images>noteskins

**Comment by SMWpalkia** [comment]
> the noteskin needs to be in mods and copy the txt file having only the custom noteskins
> 
> mods>images>noteskins

my fault

**Comment by SMWpalkia** [comment]
> the noteskin needs to be in mods and copy the txt file having only the custom noteskins
> 
> mods>images>noteskins

i did that and its doing the same thing
![image](https://github.com/user-attachments/assets/c440fb9c-5e7e-4ff0-b4a3-3e8c1bba5bca)
![image](https://github.com/user-attachments/assets/2386cbbc-74e8-455b-985e-7674b6f292c1)

**Comment by JordanSantiagoYT** [comment]
why is there a "_" where the "-" should be

**Comment by SMWpalkia** [comment]
oh i didnt knkw that made a difference. thank you

**Comment by SMWpalkia** [comment]
bruh 
![image](https://github.com/user-attachments/assets/5ad62214-8250-45c0-a1a4-09c621f6d1a0)

**Comment by StinkTheStinker** [comment]
gta6 type storage
