### ISSUE TITLE
JS engine freezing based on how long you paused when you unpause

### ISSUE THREAD

**Issue by jparkx429** [JordanSantiagoYT/FNF-JS-Engine#741]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

https://github.com/user-attachments/assets/a8f3ad4c-a159-4518-8340-3cbe21c590db

i also turned off pause if lost focus

### Command Prompt/Terminal/Crash logs (if existing)

nope

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

nope

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added mods

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

Yes

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
pretty sure that’s an optimization issue with hxcpp, but I’m not entirely sure which could pinpoint to it

**Comment by jparkx429** [comment]
alright because i hate it. like it deloads the  song or somthing

**Comment by jparkx429** [comment]
do you possibly know a setting i can turn on/off on optimization?

**Comment by moxie-coder** [comment]
> alright because i hate it. like it deloads the song or somthing

that probably is an OpenFL feature then

**Comment by moxie-coder** [comment]
> do you possibly know a setting i can turn on/off on optimization that can fix this issue?

not really, other than disabling gc in the options I don’t think so, it has a built in gc, so does hxcpp

**Comment by jparkx429** [comment]
alright ill try. thanks for the help
