### ISSUE TITLE
simply just saving a character is now impossible

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#742]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

if I click more than 3 to 5 times then the window will start to crash along with the game

### Command Prompt/Terminal/Crash logs (if existing)

p

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

simply saving a character and clicking random folders 5 times

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by daveandbambifan1234** [comment]
this also happens when I press only 1 folder too

**Comment by daveandbambifan1234** [comment]
I know the reason now
the game doesn't respond while you're saving something so the game thinks the folder is a part of the game so that stops responding

**Comment by StinkTheStinker** [comment]
close it as complete

**Comment by StinkTheStinker** [comment]
ok
this is happening to me as well now, open it back with a new label on this issue
![image](https://github.com/user-attachments/assets/bb7a6136-8508-420c-a3fa-d91ee82f4c41)

**Comment by StinkTheStinker** [comment]
i think this started happening since the noteskin crash was fixed

**Comment by StinkTheStinker** [comment]
@moxie-coder
