### ISSUE TITLE
Fast note spawning removing notes

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-JS-Engine#744]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

i made a test build to see if the new update fixed some issues i was having with previous versions (it did) but now notes are randomly disappearing during gameplay. it fixed itself when i turned off fast note spawning. i know its hard to see through the lag but you gotta believe me 🙏

https://github.com/user-attachments/assets/8e675f3d-2216-4afc-8631-8fd35e5be230

also i noticed random lag spikes throughout the engine

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
I have already found this issue, and it will be fixed shortly.

**Comment by SMWpalkia** [comment]
> I have already found this issue, and it will be fixed shortly.

mb
