### ISSUE TITLE
Old Hold Sustain option doesn't do anything.

### ISSUE THREAD

**Issue by CoolDudeT** [JordanSantiagoYT/FNF-JS-Engine#745]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Not sure if it's related to having note colors off or not, but turning on the Old Hold Sustain option doesn't do shit.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

1. Go to Options
2. Go to Visuals and UI
3. Turn on Old Hold Sustain (or whatever it's called.)
4. Go out of options and play any song with a hold note.
5. Hold splashes should still be there.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No. (Unless turning off Note Colors counts.)

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment]
let me look into the source code real quick

**Comment by StinkTheStinker** [comment]
![image](https://github.com/user-attachments/assets/5cdd0217-b897-4c5d-8c40-ed4e80f57354)

is this the option you are talking about

**Comment by moxie-coder** [comment]
I don’t get what you mean honestly

**Comment by StinkTheStinker** [comment]
yeah same
just guessing at this point

**Comment by CoolDudeT** [comment]
> ![image](https://private-user-images.githubusercontent.com/145304742/386866021-5cdd0217-b897-4c5d-8c40-ed4e80f57354.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MDE2MzMsIm5iZiI6MTczMTgwMTMzMywicGF0aCI6Ii8xNDUzMDQ3NDIvMzg2ODY2MDIxLTVjZGQwMjE3LWI4OTctNGM1ZC04YzQwLWVkNGU4MGY1NzM1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQyMzU1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmJkOTcxZjJkYmZiNWU4MzNmNmM4MjZjNTNmMGRhODA2NTk1ZjRlOGI5NjEzOTNiYTI2ODgyNDE5ZDgxMzM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wXiquKZtxN3vzhc2rIO3rIDKz7WDAyDgenEIbyo68HU)
> 
> is this the option you are talking about

yeah that (sorry for taking so long to respond my bad)

**Comment by JordanSantiagoYT** [comment]
so um..........

turning that on only makes it so characters play an anim on sustain notes, it doesn't disable the hold splashes

**Comment by moxie-coder** [comment]
> so um..........
> 
> turning that on only makes it so characters play an anim on sustain notes, it doesn't disable the hold splashes

because there isn't an option for it rn
