### ISSUE TITLE
Hold Splashes should have a Note Color disabled version.

### ISSUE THREAD

**Issue by CoolDudeT** [JordanSantiagoYT/FNF-JS-Engine#746]
### What feature do you want to get added on the **base** engine?

Basically, when the player has note colors off, just use a different version of the hold splash image that actually has the original colors.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by StinkTheStinker** [comment]
i dont even understand the issue

**Comment by JordanSantiagoYT** [comment]
> i dont even understand the issue

hold note splashes in base game are separated into 4 different png files

normal hold splashes are combined into 1 png
