### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by JuanpivrouwuIsASigma** [JordanSantiagoYT/FNF-JS-Engine#748]
### What is your question?

Why do you use a old version of PE instead of a new version of it?

**Comment by StinkTheStinker** [comment]
it would take a while to add the new shit, and it would break alot of code
thats my guess

**Comment by JordanSantiagoYT** [comment]
i don't update this to the newer psych engines because this simply has too much stuff to port over to newer updates. plus some code would break

**Comment by StinkTheStinker** [comment]
> i don't update this to the newer psych engines because this simply has too much stuff to port over to newer updates. plus some code would break

i guessed right

**Comment by moxie-coder** [comment]
but, I have been porting newer code from 0.7 over (including lua but that's broken rn, I haven't fixed it yet)
