### ISSUE TITLE
Twist Event

### ISSUE THREAD

**Issue by ISamwise4** [JordanSantiagoYT/FNF-JS-Engine#750]
### What is your question?

I need to get some built-events that are in JS Engine into psyche but I cannot find them. Does anyone have the source code or know how to get them?

**Comment by JordanSantiagoYT** [comment]
ok

the events' code are in PlayState, look in the triggerEvent function (i think that's what its called)

**Comment by moxie-coder** [comment]
plus, this repo *is* the source code 🤦🏻‍♂️

**Comment by NAEL2XD** [comment]
https://github.com/JordanSantiagoYT/FNF-JS-Engine/blob/main/source/PlayState.hx#L4328
if you're looking for it ^^

**Comment by ISamwise4** [comment]
I don't think it works in psyche (or i'm just a dummy), thank you!

**Comment by StinkTheStinker** [comment]
you need to put it in source code, not the lua event file

**Comment by moxie-coder** [comment]
> I don't think it works in psyche (or i'm just a dummy), thank you!

this *is* psych
