### ISSUE TITLE
being idle causes problems

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#751]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

staying idle on the game for too long causes it to lag a lot and crash
and if you eventually stay off screen for long enough the game will start acting weirder

### Command Prompt/Terminal/Crash logs (if existing)

a

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

e

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

o

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by daveandbambifan1234** [comment]
Uncaught Error: Null Object Reference
flixel/animation/FlxAnimationController.findByPrefix() [line 739]
Paths.addAnimAndCheck() [line 155]
Paths.initSplash() [line 137]
NoteSplash.loadAnims() [line 116]
NoteSplash.setupNoteSplash() [line 63]
NoteSplash.new() [line 44]
PlayState.create() [line 1176]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.update() [line 726]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
and this appeared out of nowhere, this just happened when I was off screen idle on the game and this error popped up

**Comment by daveandbambifan1234** [comment]
and also lag spikes happen way too frequently

**Comment by StinkTheStinker** [comment]
1. its probably just to save your pc performance, causing it to have lower fps off-tab
2. your notesplash is incorrect
3. the lag spikes are not fixable, your computer probably sucks
