### ISSUE TITLE
note spamming multiply notes on screen

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#752]
### What feature do you want to get added on the **base** engine?

make a extra option where you can multiply the notes on screen by anything
if you say no I expect that cuz it may be too hard to implement that

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by StinkTheStinker** [comment]
technically already a thing

Gameplay modifiers>Jacks amount> what ever amount

**Comment by JordanSantiagoYT** [comment]
gameplay modifiers-> jacks amount

**Comment by StinkTheStinker** [comment]
i just said tha-

**Comment by daveandbambifan1234** [comment]
that is not what I'm saying, I'm saying that all of the notes on the screen will get multiplied using the button

it's very easy to misunderstand that, so here is more detail of what I'm wanting you to add

> gameplay modifiers-> jacks amount

**Comment by StinkTheStinker** [comment]
this makes no sense

**Comment by moxie-coder** [comment]
> that is not what I'm saying, I'm saying that all of the notes on the screen will get multiplied using the button
> 
> it's very easy to misunderstand that, so here is more detail of what I'm wanting you to add
> 
> > gameplay modifiers-> jacks amount

wow, the amount of stupidity from you

**Comment by JordanSantiagoYT** [comment]
> that is not what I'm saying, I'm saying that all of the notes on the screen will get multiplied using the button
> 
> it's very easy to misunderstand that, so here is more detail of what I'm wanting you to add
> 
> > gameplay modifiers-> jacks amount

![image](https://github.com/user-attachments/assets/49622c3f-b5f6-460b-a5a3-b49a0c921d15)
???
