### ISSUE TITLE
Help me!!!

### ISSUE THREAD

**Issue by DuckkFnF** [JordanSantiagoYT/FNF-JS-Engine#761]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

What is this problem???
Every time i load my song with modchart this error disappears.
If i delete modchart the it works.

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: The property "y" is not numeric.
flixel/tweens/misc/VarTween.setStartValues() [line 103]
flixel/tweens/misc/VarTween.update() [line 55]
flixel/tweens/FlxTween.update() [line 1263]
flixel/FlxGame.update() [line 747]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by NAEL2XD** [comment]
are you using like this:
```lua
doTweenY('smth', 'sprite.y', smth, smth, 'smth')
                        ^^
                  remove that
```

**Comment by StinkTheStinker** [comment]
thats a stage json issue
show me the json stage real quick

**Comment by StinkTheStinker** [comment]
dont worry, i had this issue before

**Comment by StinkTheStinker** [comment]
i think at least

**Comment by StinkTheStinker** [comment]
hello??

**Comment by DuckkFnF** [comment]
This is not a stage problem

**Comment by DuckkFnF** [comment]
function onUpdate(elapsed)
  if curStep >= 0 then
    songPos = getSongPosition()
    local currentBeat = (songPos/1000)*(bpm/200)
    doTweenY(dadTweenY, 'dad', 290-130*math.sin((currentBeat*0.25)*math.pi),0.001)
  end
end

local angleshit = 2;
local anglevar = 2;
function onBeatHit()
  if curBeat < 300 then
    if curBeat % 2 == 0 then
    noteTweenX("x1",0,25,1,"quadinOut");
    noteTweenX("x2",1,25,1,"quadinOut");
    noteTweenX("x3",2,25,1,"quadinOut");
    noteTweenX("x4",3,25,1,"quadinOut");
    noteTweenX("x5",4,25,1,"quadinOut");
    noteTweenX("x6",5,25,1,"quadinOut");
    noteTweenX("x7",6,25,1,"quadinOut");
    noteTweenX("x8",7,25,1,"quadinOut");
      angleshit = anglevar;
    else
      angleshit = -anglevar;
    noteTweenX("x1",0,25,1,"quadinOut");
    noteTweenX("x2",1,25,1,"quadinOut");
    noteTweenX("x3",2,25,1,"quadinOut");
    noteTweenX("x4",3,25,1,"quadinOut");
    noteTweenX("x5",4,25,1,"quadinOut");
    noteTweenX("x6",5,25,1,"quadinOut");
    noteTweenX("x7",6,25,1,"quadinOut");
    noteTweenX("x8",7,25,1,"quadinOut");
    end
      if curBeat %5 == 0 then
            noteTweenX("x1",0,100,1,"quadinOut");
             noteTweenX("x2",1,250,1,"quadinOut");
             noteTweenX("x3",2,350,1,"quadinOut");
             noteTweenX("x4",3,450,1,"quadinOut");
             noteTweenX("x5",4,1600,1,"quadinOut");
             noteTweenX("x6",5,1750,1,"quadinOut");
             noteTweenX("x7",6,1850,1,"quadinOut");
             noteTweenX("x8",7,1950,1,"quadinOut");
             noteTweenX("x1",0,25,1,"quadinOut");
                 end   

    setProperty('camHUD.angle',angleshit*3)
    doTweenAngle('turn', 'camHUD', angleshit, stepCrochet*0.002, 'quadinOut')
    doTweenX('tuin', 'camHUD', -angleshit*8, crochet*0.001, 'quadinOut')
  end
end
