### ISSUE TITLE
js engine crashing

### ISSUE THREAD

**Issue by macaroniandburritos** [JordanSantiagoYT/FNF-JS-Engine#762]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

basically, i was trying to play a 6k song that i ported over. when it loaded, it crashed. i know, theres no 6k support, but is there any way that i can either make 6k support or add a script to make it work?

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: Null Object Reference
PlayState.updateNote() [line 5632]
PlayState.update() [line 3951]
flixel/group/FlxGroup.forEach() [line 770]
PlayState.update() [line 3949]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

ported a mod over from psych engine

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
what version are you on exactly?

**Comment by StinkTheStinker** [comment]
well
i dont think js engine supports 6k charting

**Comment by StinkTheStinker** [comment]
also
when you ported from psych, was it 1.0 psych?

**Comment by macaroniandburritos** [comment]
> also when you ported from psych, was it 1.0 psych?

im not sure what version it was but i think it was 1.6 or somethiing

**Comment by macaroniandburritos** [comment]
> what version are you on exactly?

the most recent version of js engine, 1.38.1

**Comment by StinkTheStinker** [comment]
> im not sure what version it was but i think it was 1.6 or somethiing

i ment the latest version of psych engine (1.0)

but, im guessing the version is 0.1.6

**Comment by macaroniandburritos** [comment]
> > im not sure what version it was but i think it was 1.6 or somethiing
> 
> i ment the latest version of psych engine (1.0)
> 
> but, im guessing the version is 0.1.6

psych engine version was 1.6.3 i think and js engine version was 1.38.1

**Comment by StinkTheStinker** [comment]
yeah
I don't think psych 1.x is fully supported on js engine yet

**Comment by macaroniandburritos** [comment]
> yeah I don't think psych 1.x is fully supported on js engine yet

alright, thanks!
