### ISSUE TITLE
A bug when i build js engine.

### ISSUE THREAD

**Issue by DuckkFnF** [JordanSantiagoYT/FNF-JS-Engine#764]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

When i build js engine then this error shows up.

### Command Prompt/Terminal/Crash logs (if existing)

source/FunkinLua.hx:486: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:504: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:510: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:560: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:566: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:606: lines 606-610 : Int should be Bool
source/FunkinLua.hx:606: lines 606-610 : ... For function argument 'f'
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent class with different or incomplete type
C:/HaxeToolkit/haxe/lib/flixel/5,8,0/flixel/graphics/frames/FlxAtlasFrames.hx:472: characters 18-24 : ... Base field is defined here
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
source/Paths.hx:930: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes i edit Project.xml

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
install and run hmm

**Comment by DuckkFnF** [comment]
> install and run hmm

How do you run it?
