### ISSUE TITLE
Freeplay categories

### ISSUE THREAD

**Issue by DuckkFnF** [JordanSantiagoYT/FNF-JS-Engine#766]
### What is your question?

How do you add freeplay categories with SOURCE CODE?

**Comment by moxie-coder** [comment]
Here’s one engine I work on with that feature (that’s currently buggy rn) https://github.com/miksel1/FNF-ScrewedEngine

**Comment by moxie-coder** [comment]
> I just need source code please!

https://github.com/miksel1/FNF-ScrewedEngine/blob/main/source/FreeplayState.hx here
