### ISSUE TITLE
screwed note skins

### ISSUE THREAD

**Issue by macaroniandburritos** [JordanSantiagoYT/FNF-JS-Engine#767]
### What is your question?

how do i add the screwed note skin, or just any note skin? i've already installed it i just dont know where to put it.. am i on the right track?
![Screenshot 2024-11-25 114139](https://github.com/user-attachments/assets/44edb12b-34dc-4111-ba95-79413e42ccf7)

**Comment by NAEL2XD** [comment]
You place the custom noteskin on
`mods > (mod name) > custom_notetypes > file_name.lua`
placing inside a "modTemplate" will not recognize it

**Comment by macaroniandburritos** [comment]
> You place the custom noteskin on `mods > (mod name) > custom_notetypes > file_name.lua` placing inside a "modTemplate" will not recognize it

how do i get the .lua file

**Comment by StinkTheStinker** [comment]
no, i dont think its like that
![image](https://github.com/user-attachments/assets/e6db4adc-499d-4c03-944a-576728c88166)

**Comment by StinkTheStinker** [comment]
@macaroniandburritos this is how its ment to be
the list.txt file needs to be the exact name, im not sure about excluding the others, so keep that in there, just in case

heres the list.txt file

```
Future
Chip
Classic
Screwed
```
