### ISSUE TITLE
video crashing when i press space and chart editor and character editor crashing when saving,

### ISSUE THREAD

**Issue by mdk-pie** [JordanSantiagoYT/FNF-JS-Engine#768]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

the script is just these few lines:
local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and not seenCutscene then --Block the first countdown
		startVideo('Cutscene2');
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

idk why but when i press space it just crashes the engine

and for the saving issues on the newest engine version it crashes for some reason when i try to save a chart or a character json, it doesnt even give me a error code or anything it just freezes

### Command Prompt/Terminal/Crash logs (if existing)

![Screenshot 2024-11-25 170722](https://github.com/user-attachments/assets/b2c93fe6-5237-4489-9deb-9a41908601a7)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

press space or any key

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i just used the newest

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by StinkTheStinker** [comment]
its not happening to me
its the video path like this?
`videos/Cutscene2.mp4`
