### ISSUE TITLE
renders are slower for like x2

### ISSUE THREAD

**Issue by expungeddotdat** [JordanSantiagoYT/FNF-JS-Engine#769]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

im using classic render mode and after i turn the pngs into mp4s the mp4 is just x2 slower. also i was trying to do something with speed in video editor but nothing worked

### Command Prompt/Terminal/Crash logs (if existing)

no

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

classic render mode
100 fps
lossless format

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment]
dude
it's meant to do that

**Comment by StinkTheStinker** [comment]
for classic rendering
if it's slow on the final, speeding up

**Comment by StinkTheStinker** [comment]
well
that's something I can't answer

**Comment by StinkTheStinker** [comment]
close for inactivity
