### ISSUE TITLE
Chart Editor playtest crash

### ISSUE THREAD

**Issue by zeeblox09** [JordanSantiagoYT/FNF-JS-Engine#771]
### What is your question?

I'm recharting Blammed, but each time i try to test the chart, I get this error:

`Uncaught Error: Null Object Reference
PlayState.startCharacterPos() [line 1930]
PlayState.addCharacterToList() [line 1773]
PlayState.eventPushedUnique() [line 3063]
PlayState.eventPushed() [line 3035]
PlayState.generateSong() [line 2788]
PlayState.create() [line 1191]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.update() [line 726]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]`

Does anyone know what this means? Any help would be appreciated! This is also my first time modding.

![Screen Shot 2024-11-26 at 7 32 24 PM](https://github.com/user-attachments/assets/f5fe7cba-f1a9-4f1d-a41e-839c472d0330)
[JSEngine_2024-11-26_19'19'34.log](https://github.com/user-attachments/files/17928481/JSEngine_2024-11-26_19.19.34.log)

**Comment by JordanSantiagoYT** [comment]
added a character but their positionarray is null
