### ISSUE TITLE
Can you fix this? It happens on my phone

### ISSUE THREAD

**Issue by Adit25MCPE** [JordanSantiagoYT/FNF-JS-Engine#772]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

plz fix this

### Command Prompt/Terminal/Crash logs (if existing)

Invalid escape sequence \C at position 93
/opt/hostedtoolcache/haxe/4.3.6/x64/std/haxe/format/JsonParser.parseString() [line 223]
/opt/hostedtoolcache/haxe/4.3.6/x64/std/haxe/format/JsonParser.parseRec() [line 143]
/opt/hostedtoolcache/haxe/4.3.6/x64/std/haxe/format/JsonParser.parseRec() [line 90]
/opt/hostedtoolcache/haxe/4.3.6/x64/std/haxe/format/JsonParser.doParse() [line 57]
ModsMenuState.new() [line 735]
ModsMenuState.create() [line 327]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.update() [line 726]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

idk what to say but plz fix this
it happens on my phone everytime i opened the mod after i put all my psych mod files in the external data file

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I DIDNT EDITING ANYTHING I SWEAR

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by Adit25MCPE** [comment]
> json is invalid, fix it or give me it

which json?

**Comment by moxie-coder** [comment]
> > json is invalid, fix it or give me it
> 
> which json?

the one that’s broken

**Comment by StinkTheStinker** [comment]
the mod json

**Comment by Adit25MCPE** [comment]
i think i already fixed it

**Comment by Adit25MCPE** [comment]
> i think i already fixed it

kinda
