### ISSUE TITLE
JS Engine : video fucking dies💀

### ISSUE THREAD

**Issue by SyncGit12** [JordanSantiagoYT/FNF-JS-Engine#775]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

![image](https://github.com/user-attachments/assets/6320168b-aa9f-4c70-a3a2-a388c57cda5d)

### Command Prompt/Terminal/Crash logs (if existing)

![image](https://github.com/user-attachments/assets/3cd41fb1-32bd-422a-a3d4-2c8f941d5900)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

play a video

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by SyncGit12** [comment]
try this hxCodec version:

https://github.com/SyncGit12/hxCodec

**Comment by StinkTheStinker** [comment]
bro answered himself

**Comment by moxie-coder** [comment]
I think we need to update hxCodec @JordanSantiagoYT

**Comment by SyncGit12** [comment]
> bro answered himself

lmao, btw i think it fixes it................................

nothin' engine is based of js engine 1.32.2, so it should work

**Comment by SyncGit12** [comment]
time to run update.bat!

**Comment by samikhuska57** [comment]
bro the title of null "i already have a girlfriend"
