### ISSUE TITLE
1.39.0 no android version 

### ISSUE THREAD

**Issue by xdczmods** [JordanSantiagoYT/FNF-JS-Engine#776]
No android version 

Xd​

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

SHUCKS!!!!!!!

**Comment by StinkTheStinker** [comment]
what

**Comment by JordanSantiagoYT** [comment]
..can you not? it'll be out when it's out.

**Comment by mcagabe19** [comment]
what a brainrot
