### ISSUE TITLE
Updating insanity

### ISSUE THREAD

**Issue by VAPORIZEDbutREALLLLLLLL** [JordanSantiagoYT/FNF-JS-Engine#778]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

so i open JS engine (v1.37.0) and i get the update v1.39, i download the update and when it finishes, another JS engine tab shows up, and when i press enter the same update v1.39 shows again, i try downloading and when it finishes the same thing happens, IM IN INSANITY I CANT UPDATE MY JS ENGINE-

I recorded this for proof 

https://github.com/user-attachments/assets/426b907e-18c0-41a1-8921-5d97197b56cd

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

i just open the engine. it shows me an update, when i press enter the whole loop begins
(REMINDER: im in V1.37)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i dont recall doing anything to the main engine. it just did this whole update-loop crap out of nowhere

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by VAPORIZEDbutREALLLLLLLL** [comment]
excuse my language.

**Comment by StinkTheStinker** [comment]
is there two js engine exe's?
if so, delete the (old) JSEngine.exe

**Comment by JordanSantiagoYT** [comment]
again..

download the newer update manually. This bug was patched out in 1.38.0

**Comment by moxie-coder** [comment]
Duplicate

**Comment by VAPORIZEDbutREALLLLLLLL** [comment]
thank you.
