### ISSUE TITLE
0.001% chance botplay troll

### ISSUE THREAD

**Issue by helloAHHHHHHMYSPINE** [JordanSantiagoYT/FNF-JS-Engine#779]
### What feature do you want to get added on the **base** engine?

Make a troll that occurs 0.001% chance. When you pause the game and select "toggle botplay" and your extremely lucky and the troll occurs, the "toggle botplay" option will instead be renamed to "no botplay for you" and then disappear (it will not enable botplay) This resets and the option will be back to normal (without the troll unless it happens again) when you restart the song

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by NAEL2XD** [comment]
possible in lua

**Comment by moxie-coder** [comment]
> possible in lua, infact i can make it for you

what he said
