### ISSUE TITLE
How can i make the Fake BPM Counter(Like hortas edition)?

### ISSUE THREAD

**Issue by mihaillov** [JordanSantiagoYT/FNF-JS-Engine#781]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

in the agony there is the Fake BPM Counter!How can i make this as event,or script(Without curBpm!With fake value)?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by moxie-coder** [comment]
can you show an example? cuz idk what you mean

**Comment by mihaillov** [comment]
sorry if late,cuz i am sick
The example:https://youtu.be/k7vIizpzP00?si=oxNevI6nOiQKzZi2

**Comment by mihaillov** [comment]
?

**Comment by mihaillov** [comment]
second example:https://youtu.be/HzGRRUFRDjs?si=9wSFSJsIlgUO4fUR (I mean the text with BPM that not affecting to real BPM(curBpm))

**Comment by mihaillov** [comment]
answer?

**Comment by mihaillov** [comment]
I ALREADY SHOWED THE EXAMPLES

**Comment by mihaillov** [comment]
@moxie-coder you can replie to this videos showing the bpm text mechanic(when the bpm is 1000 or more in the Current BPM text,the icon is bopping by normal bpm(by default BPM.Example:BESTOW BPM is 270 but on SP_Valisia the BPM text is showing 17280,but the icon is bopping like 270 BPM)(sorry for bad english)

**Comment by moxie-coder** [comment]
> @moxie-coder you can replie to this videos showing the bpm text mechanic(when the bpm is 1000 or more in the Current BPM text,the icon is bopping by normal bpm(by default BPM.Example:BESTOW BPM is 270 but on SP_Valisia the BPM text is showing 17280,but the icon is bopping like 270 BPM)(sorry for bad english)

well excuse me for having a life, but can you have some patience you annoying ass D&B fan kid? I swear y'all are annoying little shits, all you have to do is just make a script file in Lua, and then just use the curBpm value for the initial value, then change the bpm without changing that text to the current bpm, or change it but not the bpm
 
here I got GPT to do it since I'm lazy & you're being impatient like jeez:
```lua
function onCreatePost()
    -- Get the song's BPM
    local songBPM = getProperty('SONG.bpm') -- This retrieves the BPM from the current song
    
    -- Create the text to display BPM
    makeLuaText('bpmText', 'BPM: ' .. songBPM, 0, 0, 0)
    setTextSize('bpmText', 32) -- Set the font size
    setTextAlignment('bpmText', 'center') -- Align the text to the center
    
    -- Position the text in the center of the screen
    local screenWidth = getPropertyFromClass('flixel.FlxG', 'width')
    local screenHeight = getPropertyFromClass('flixel.FlxG', 'height')
    setProperty('bpmText.x', (screenWidth / 2) - (getProperty('bpmText.width') / 2))
    setProperty('bpmText.y', (screenHeight / 2) - (getProperty('bpmText.height') / 2))
    
    -- Add the text to the screen
    addLuaText('bpmText')
end
```

**Comment by mihaillov** [comment]
Thanks!By this comment

**Comment by mihaillov** [comment]
https://gamebanana.com/tools/11169 use this as event,this issue is fixed!

**Comment by moxie-coder** [comment]
alright
