### ISSUE TITLE
Why does using setObjectOrder on a character double their fps?

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-JS-Engine#784]
### What is your question?

Recording it would be too laggy but basically when i do `setObjectOrder('dad', 5)`, it makes their animations and sing animation length twice as fast

**Comment by JordanSantiagoYT** [comment]
setObjectOrder gets the character directly and removes it, then reinserts it at the position. something probably happens because of this that causes it but idk

**Comment by StinkTheStinker** [comment]
try looking for something about fps on the set object
