### ISSUE TITLE
HUH...?

### ISSUE THREAD

**Issue by NonsensicalGH** [JordanSantiagoYT/FNF-JS-Engine#785]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Idk, when i import a song this shit pops up

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: Error loading sound from file: mods/songs/clonated/Voices.ogg
openfl/media/Sound.fromFile() [line 416]
Paths.returnSound() [line 779]
Paths.voices() [line 502]
editors/ChartingState.loadSong() [line 2265]
editors/ChartingState.addSongUI() [line 641]
flixel/ui/FlxButton.onUpHandler() [line 521]
flixel/ui/FlxButton.onUpEventListener() [line 507]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment]
did the song have a different file type before imported

**Comment by NonsensicalGH** [comment]
pretty sure it was from NotSoBot Also it was .ogg
![Screenshot 2024-12-05 162727](https://github.com/user-attachments/assets/b14bff78-7228-4292-9304-e18d89071303)

**Comment by StinkTheStinker** [comment]
use fl studio to convert shit to ogg's
