### ISSUE TITLE
chart editor lags

### ISSUE THREAD

**Issue by TheFNFAddict** [JordanSantiagoYT/FNF-JS-Engine#795]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Chart editor freezes/stutters

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

One is placing notes and then playing the song. I pause the song, place a note to where a vocal is, and when I play the song again it freezes my screen. Half of the time it freezes while the song keeps playing and the other half it just completely stops.

Letting the song run is another as well. Just playing the song in the chart editor sometimes freezes a little bit, but there are times where its big and freezes for a minute.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
can't fix
