### ISSUE TITLE
I literally cannot play the engine

### ISSUE THREAD

**Issue by Piggymaster1222** [JordanSantiagoYT/FNF-JS-Engine#796]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I am not trying to open but it keeps saying there was a null object reference.

### Command Prompt/Terminal/Crash logs (if existing)

[JSEngine_2024-12-14_17'48'07.log](https://github.com/user-attachments/files/18138009/JSEngine_2024-12-14_17.48.07.log)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

I have no clue how to fix the bug at all :( but my best bet is to download a new file and transport all your files there.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by Piggymaster1222** [comment]
adding on: Character Editor is broken again

**Comment by JordanSantiagoYT** [comment]
um..

your jse is not up to date. but since it's crashing because of ClientPrefs, you'll need to delete your settings save.

**Comment by Piggymaster1222** [comment]
ok thanks. btw where is it located in the folders?

**Comment by moxie-coder** [comment]
> ok thanks. btw where is it located in the folders?

appdata, type %appdata% in file explorer, then look for JordanSantiago, and you should be able to find it from there

**Comment by Piggymaster1222** [comment]
oh ok thanks. however, I can't find it. I searched it and was unable to locate it

**Comment by Piggymaster1222** [comment]
![image](https://github.com/user-attachments/assets/f45ee978-a7ae-41ee-8539-4e229035246b)

**Comment by moxie-coder** [comment]
> ![image](https://private-user-images.githubusercontent.com/179584620/395881738-f45ee978-a7ae-41ee-8539-4e229035246b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODQ5OTAsIm5iZiI6MTczNDI4NDY5MCwicGF0aCI6Ii8xNzk1ODQ2MjAvMzk1ODgxNzM4LWY0NWVlOTc4LWE3YWUtNDFlZS04NTM5LTRlMjI5MDM1MjQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxNzQ0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzQyYmIzNTJmMWQ0NjgzYzNkNWE5N2Y1MjBiZTBhNjM3NjRiNjg3YmJkMzY4Y2ZkYzA3NjYwOGQwYjY5ZGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cAJPhWHYtS9SMTf9WrhIrmN-J7ZaNism4xdb7rG73rk)

that's not what I even meant at all, I meant press the address bar, then type %appdata% and press enter, or just press Win + R and then type %appdata% and press enter. I attached an photo of the address bar below
![image](https://github.com/user-attachments/assets/647b454d-1cf7-4216-a0d1-3b7436d301df)

**Comment by Piggymaster1222** [comment]
ooooooooh. okay!

**Comment by Piggymaster1222** [comment]
> > ok thanks. btw where is it located in the folders?
> 
> appdata, type %appdata% in file explorer, then look for JordanSantiago, and you should be able to find it from there

I found the file "JordanSantiago". what's the next step?

**Comment by Piggymaster1222** [comment]
do I just delete the blank items?

**Comment by Piggymaster1222** [comment]
I had to delete the blank items and it is all fixed! thank you @moxie-coder for helping!

**Comment by moxie-coder** [comment]
> I had to delete the blank items and it is all fixed! thank you @moxie-coder for helping!

np!
