### ISSUE TITLE
you cant scroll in options

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#800]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

https://github.com/user-attachments/assets/31aae709-5af7-4387-8830-635e78cb66cd

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

none

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
this was actually a small fix i did to fix a crash that would occur upon entering the options menu, although it appears that this causes scrolling to break. will fix in 1.40.0

**Comment by StinkTheStinker** [comment]
fixed in this [commit](https://github.com/JordanSantiagoYT/FNF-JS-Engine/commit/1919e427c405ad9e85b32f0e77dd9299f8558c1b)

@JordanSantiagoYT forgot to close this i guess
