### ISSUE TITLE
I hate the audio clipping

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#801]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

please remove audio clipping as best as you can, cuz it makes a better experience

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

a costom song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

none

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by daveandbambifan1234** [comment]
this happens when an opponent hits a note and it causes the audio to clip and the game to lag

**Comment by StinkTheStinker** [comment]
can you send footage of what you are talking about, i do not understand
even though you are on a older version

**Comment by daveandbambifan1234** [comment]
https://youtu.be/nzpLbhhPuUE

> I’m pretty sure this was already fixed in an **newer version of the engine**

...

**Comment by daveandbambifan1234** [comment]
the game lags and the audio starts clipping

**Comment by StinkTheStinker** [comment]
you make no sense
