### ISSUE TITLE
why can't i compile the game?

### ISSUE THREAD

**Issue by zeeblox09** [JordanSantiagoYT/FNF-JS-Engine#802]
### What is your question?

I just cloned the repository to my Mac files, but each time i try to build the game for a macOS target, I get this message:
```/Users/isaiah/haxelib/flixel-ui/2,6,3/flixel/addons/ui/FlxInputText.hx:291: characters 18-34 : Unknown identifier : getCamerasLegacy```
Is there something wrong with the file?

**Comment by moxie-coder** [comment]
can you do `haxelib list`? since you might be using wrong versions of libs

**Comment by moxie-coder** [comment]
okay I fixed it, try using `haxelib set flixel-addons 3.2.3` and `haxelib set flixel-ui 2.6.1` since those are too new

**Comment by zeeblox09** [comment]
> okay I fixed it, try using `haxelib set flixel-addons 3.2.3` and `haxelib set flixel-ui 2.6.1` since those are made for flixel 5.6.2
![Screenshot 2024-12-15 at 12 32 14 PM](https://github.com/user-attachments/assets/9d06ee98-fc69-43b1-b3a8-011f85406fa8)
thank you, it's working now! i guess the versions i had were too new?

**Comment by moxie-coder** [comment]
> > okay I fixed it, try using `haxelib set flixel-addons 3.2.3` and `haxelib set flixel-ui 2.6.1` since those are made for flixel 5.6.2
> 
> ![Screenshot 2024-12-15 at 12 32 14 PM](https://private-user-images.githubusercontent.com/80136283/395893885-9d06ee98-fc69-43b1-b3a8-011f85406fa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyOTY0NDcsIm5iZiI6MTczNDI5NjE0NywicGF0aCI6Ii84MDEzNjI4My8zOTU4OTM4ODUtOWQwNmVlOTgtZmM2OS00M2IxLWIzYTgtMDExZjg1NDA2ZmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDIwNTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Mzk2OTExMGM2MTVmNjY1NjQ3ZDJkZDJmM2IyNTQ2NWFlNjBhNDMxM2VhNWI1YjRkNDBhMWQwMjg4ZjE0MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0dPB1qGzKR2Zs8Mr-ezWLZ2AiB5rS0mgjmJg_npARBw) thank you, it's working now! i guess the versions i had were too new?

yes they were, I didn't fix hmm when those got updated
