### ISSUE TITLE
Unplayable chart

### ISSUE THREAD

**Issue by CYCLOLCYC** [JordanSantiagoYT/FNF-JS-Engine#803]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

So I copy & pasted the imprisonment chart from your ''mods for JS engine'' file and it works fine in the editor itself, but when I press enter the game crashes

### Command Prompt/Terminal/Crash logs (if existing)

[JSEngine_2024-12-15_14'19'29.log](https://github.com/user-attachments/files/18140533/JSEngine_2024-12-15_14.19.29.log)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Copy & Paste the song/chart -> Enter the chart editor -> Load the song and the .json file for the chart -> Press enter -> the game crashes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by moxie-coder** [comment]
duplicate
