### ISSUE TITLE
Js engine. enter song name and not loading in

### ISSUE THREAD

**Issue by Andrhevn23Rbx** [JordanSantiagoYT/FNF-JS-Engine#805]
Song error

i was gonna make an song with 263M note's until this error showed up. i tried many time's to fix but keep failing. then when i came here i was like ooh i see. soo i kinda wana ask u if u could fix or help me. by @AndreNicholasJr YT 
![Screenshot 2024-12-15 132822](https://github.com/user-attachments/assets/2072289f-62bf-4c47-8ec2-432c96b2db19)
![Screenshot 2024-12-15 133108](https://github.com/user-attachments/assets/e92ba705-ec5d-4b35-8266-40fddc67ccb3)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope  just wana make an mod

**Comment by JordanSantiagoYT** [comment]
Corrupted sound file.

**Comment by JordanSantiagoYT** [comment]
666th closed issue

**Comment by StinkTheStinker** [comment]
congrats!!11!
