### ISSUE TITLE
Screen not sized properly 

### ISSUE THREAD

**Issue by zeeblox09** [JordanSantiagoYT/FNF-JS-Engine#808]
### What is your question?

Why doesn’t the game align to the screen size? I just got the latest app update for iOS, and it keeps going here.
![IMG_0460](https://github.com/user-attachments/assets/3af09405-0a2c-4195-a6eb-c029e8df51bc)
Also I wasn’t sure how to report this so I put it as a question… I’m on iOS 18.3 beta 1

**Comment by StinkTheStinker** [comment]
since your ios is in beta, and you check if this applies to other games?

**Comment by zeeblox09** [comment]
> since your ios is in beta, and you check if this applies to other games?

This doesn't happen with other games, only this one. If it helps any further, I'm launching the game through [LiveContainer](https://github.com/khanhduytran0/LiveContainer/releases/tag/3.1.0). Is that a problem with 1.39.1? It didn't happen one version before. (1.39.0)

**Comment by StinkTheStinker** [comment]
.

**Comment by StinkTheStinker** [comment]
js engine has ios support

**Comment by StinkTheStinker** [comment]
![image](https://github.com/user-attachments/assets/df2cdcb4-f184-47df-aa98-087219668829)

**Comment by zeeblox09** [comment]
> js engine has ios support

I know... I'm using that because I'm out of App IDs to side load it normally.

**Comment by StinkTheStinker** [comment]
isnt there a way to make more

**Comment by moxie-coder** [comment]
> isnt there a way to make more

not without paying 100$ yearly to apple

**Comment by StinkTheStinker** [comment]
GOD DAMN

**Comment by zeeblox09** [comment]
> isnt there a way to make more

Uhh no it's 10 app ids max and 3 apps max
![image](https://github.com/user-attachments/assets/be7b4399-31a5-4c3a-91fc-97aa7fed7f99)
-# apps
![image](https://github.com/user-attachments/assets/0d90d8f8-4361-4f86-9c2e-d464e4d963cf)
![image](https://github.com/user-attachments/assets/2d4bf463-e9be-4172-b4e9-c1e5bbe44ca4)
-# app id list

**Comment by StinkTheStinker** [comment]
just get rid of one that you dont even use anymore

**Comment by StinkTheStinker** [comment]
theres no other way then

**Comment by StinkTheStinker** [comment]
but
you could try going to the graphics settings and changing the res

**Comment by mcagabe19** [comment]
use esign and don't use LiveContainer
https://onejailbreak.com/blog/esign-ipa-signing-app/download
