### ISSUE TITLE
JS Engine : why Main.hx do not work

### ISSUE THREAD

**Issue by SyncGit12** [JordanSantiagoYT/FNF-JS-Engine#811]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Uncaught Error: Null Object Reference
ClientPrefs.loadPrefs() [line 329]
InitState.create() [line 37]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.create() [line 367]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: Null Object Reference
ClientPrefs.loadPrefs() [line 329]
InitState.create() [line 37]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.create() [line 367]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

uh launch the game

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment]
use one of the bat files in the setup folder

**Comment by SyncGit12** [comment]
this is not source btw

**Comment by moxie-coder** [comment]
this isn’t an compile error

**Comment by SyncGit12** [comment]
somehow unscrewing a tiny bit a internal pc fan caused it for some reason

**Comment by SyncGit12** [comment]
found a fix for it

delete the JordanSantiago folder in AppData
