### ISSUE TITLE
camera indicator not showing in character editor

### ISSUE THREAD

**Issue by Kipchin1Real** [JordanSantiagoYT/FNF-JS-Engine#812]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

The camera indicator is not showing up 😭😭😭
![deez](https://github.com/user-attachments/assets/0f79651f-7b49-4d94-acce-10615a379af6)

### Command Prompt/Terminal/Crash logs (if existing)

N/A

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

1. go to character editor

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
this is caused by a newer flixel version being used, killing the graphics pointer. there's no definitive fix other than using flixel 5.6.2 for now

**Comment by SyncGit12** [comment]
is anyone going to ignore the cock

**Comment by StinkTheStinker** [comment]
> is anyone going to ignore the cock

its a chicken.

**Comment by SyncGit12** [comment]
i call it cock
