### ISSUE TITLE
Uncaught Error: Null Object Reference

### ISSUE THREAD

**Issue by lionkingnyc** [JordanSantiagoYT/FNF-JS-Engine#814]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

unable to load js engine

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: Null Object Reference
ClientPrefs.loadPrefs() [line 329]
InitState.create() [line 37]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.create() [line 367]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by StinkTheStinker** [comment]
reset options
options> press 'r'

**Comment by JordanSantiagoYT** [comment]
delete the JordanSantiago folder located in %appdata%
