### ISSUE TITLE
how the hell font is serif?

### ISSUE THREAD

**Issue by imguest24897-alt** [JordanSantiagoYT/FNF-JS-Engine#816]
### What is your question?

how the hell font is serif?

platform: windows
version: 11 24h2

**Comment by moxie-coder** [comment]
what do you mean by this

**Comment by imguest24897-alt** [comment]
> what do you mean by this

the font looks like times new roman
![image](https://github.com/user-attachments/assets/1905210f-e535-4c5a-9c83-f8da0f0a5602)

**Comment by moxie-coder** [comment]
> > what do you mean by this
> 
> the font looks like times new roman ![image](https://private-user-images.githubusercontent.com/161818573/397677936-1905210f-e535-4c5a-9c83-f8da0f0a5602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODU3MDIsIm5iZiI6MTczNDY4NTQwMiwicGF0aCI6Ii8xNjE4MTg1NzMvMzk3Njc3OTM2LTE5MDUyMTBmLWU1MzUtNGM1YS05YzgzLWY4ZGEwZjBhNTYwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwOTAzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDMyZGUyZWZjNTY4NzkzNzE0NDkyODg1YmRmMTY0YzI4NDU1ZWM3YTMwM2ZjOTdhN2NiMWVhNmM3NWVjMTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gBvFC5Bxy-ahB-OSGSXJ85eVJLea_JY--FHRcnP2T-Y)

your install might’ve gotten corrupted in some way, I’d try reinstalling

**Comment by imguest24897-alt** [comment]
> > > what do you mean by this
> > 
> > 
> > the font looks like times new roman ![image](https://private-user-images.githubusercontent.com/161818573/397677936-1905210f-e535-4c5a-9c83-f8da0f0a5602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODU3MDIsIm5iZiI6MTczNDY4NTQwMiwicGF0aCI6Ii8xNjE4MTg1NzMvMzk3Njc3OTM2LTE5MDUyMTBmLWU1MzUtNGM1YS05YzgzLWY4ZGEwZjBhNTYwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwOTAzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDMyZGUyZWZjNTY4NzkzNzE0NDkyODg1YmRmMTY0YzI4NDU1ZWM3YTMwM2ZjOTdhN2NiMWVhNmM3NWVjMTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gBvFC5Bxy-ahB-OSGSXJ85eVJLea_JY--FHRcnP2T-Y)
> 
> your install might’ve gotten corrupted in some way, I’d try reinstalling

ill try installing fonts onto my windows setup first as i think it could resolve it

**Comment by imguest24897-alt** [comment]
installing fonts didint work :/
i guess ill try some windows commands inside my powershell window

**Comment by imguest24897-alt** [comment]
and i got this from sfc scannow
`Beginning system scan.  This process will take some time.                                                                                                                                                                                       Beginning verification phase of system scan.                                                                            Verification 100% complete.                                                                                                                                                                                                                     Windows Resource Protection did not find any integrity violations.`

**Comment by imguest24897-alt** [comment]
i guess ill just give up and continue using the serif fonts on the game :P

**Comment by NAEL2XD** [comment]
Missing `vcr.ttf` font in assets/fonts or mods/fonts

**Comment by JordanSantiagoYT** [comment]
you likely deleted vcr.ttf
