### ISSUE TITLE
Icons & jsons

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-JS-Engine#822]
### What is your question?

Is it possible to switch icons on a character mid chart without having to make a new json for for them?

**Comment by JordanSantiagoYT** [comment]
> ### What is your question?
> Is it possible to switch icons on a character mid chart without having to make a new json for for them?

```
runHaxeCode([[
            game.iconP2.changeIcon('name');
]])
```
maybe

**Comment by SMWpalkia** [comment]
do you know how i could run this in a lua script? im very unfamiliar with haxe

**Comment by JordanSantiagoYT** [comment]
oh, you can put that in any lua script and it'll work

**Comment by StinkTheStinker** [comment]
as long if its in a function

**Comment by SMWpalkia** [comment]
ty 👍

**Comment by SMWpalkia** [comment]
last thing, how do i change the color of the health bar along with it?

**Comment by moxie-coder** [comment]
> last thing, how do i change the color of the health bar along with it? ik it has something to do with this ![image](https://private-user-images.githubusercontent.com/136278510/398589606-629588c8-5fcf-4b66-a580-fcdd6b69e4c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDYzNjUsIm5iZiI6MTczNTE0NjA2NSwicGF0aCI6Ii8xMzYyNzg1MTAvMzk4NTg5NjA2LTYyOTU4OGM4LTVmY2YtNGI2Ni1hNTgwLWZjZGQ2YjY5ZTRjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxNzAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWExYzAxZjc5NjRlYTIzZTQ2NTEyNTdhNDNmYmM5MDBjOWY5YmFkMzVhYWIxZjNmZDhhNjU1Y2ZmMTMyMTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KU5SLj0SAOE-pq6wa2rEwzPz-LLFe8FKpvnOPBEiAp0) ![image](https://private-user-images.githubusercontent.com/136278510/398589620-341e2528-bee0-4f1a-a8c1-4910fb66b926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDYzNjUsIm5iZiI6MTczNTE0NjA2NSwicGF0aCI6Ii8xMzYyNzg1MTAvMzk4NTg5NjIwLTM0MWUyNTI4LWJlZTAtNGYxYS1hOGMxLTQ5MTBmYjY2YjkyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxNzAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWZiYjgxNGQzYjY0NDk3NTc3Yzk2M2NkZWY2ZWZmNmJkOTMwYzdhYzZiNjIzMDZlYzE3MDNkOGZjYWQ1NGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fKefN6rWpvB8UunP7BEnnefXELuDE1G3mLTlG-IpiIY)

it works like RGB (Red Green Blue), for [Lua](https://github.com/JordanSantiagoYT/FNF-JS-Engine/blob/main/source/FunkinLua.hx#L2021), you'll need an Color picker

**Comment by SMWpalkia** [comment]
> > last thing, how do i change the color of the health bar along with it? ik it has something to do with this ![image](https://private-user-images.githubusercontent.com/136278510/398589606-629588c8-5fcf-4b66-a580-fcdd6b69e4c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDYzNjUsIm5iZiI6MTczNTE0NjA2NSwicGF0aCI6Ii8xMzYyNzg1MTAvMzk4NTg5NjA2LTYyOTU4OGM4LTVmY2YtNGI2Ni1hNTgwLWZjZGQ2YjY5ZTRjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxNzAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWExYzAxZjc5NjRlYTIzZTQ2NTEyNTdhNDNmYmM5MDBjOWY5YmFkMzVhYWIxZjNmZDhhNjU1Y2ZmMTMyMTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KU5SLj0SAOE-pq6wa2rEwzPz-LLFe8FKpvnOPBEiAp0) ![image](https://private-user-images.githubusercontent.com/136278510/398589620-341e2528-bee0-4f1a-a8c1-4910fb66b926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDYzNjUsIm5iZiI6MTczNTE0NjA2NSwicGF0aCI6Ii8xMzYyNzg1MTAvMzk4NTg5NjIwLTM0MWUyNTI4LWJlZTAtNGYxYS1hOGMxLTQ5MTBmYjY2YjkyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxNzAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWZiYjgxNGQzYjY0NDk3NTc3Yzk2M2NkZWY2ZWZmNmJkOTMwYzdhYzZiNjIzMDZlYzE3MDNkOGZjYWQ1NGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fKefN6rWpvB8UunP7BEnnefXELuDE1G3mLTlG-IpiIY)
> 
> it works like [RGB (Red Green Blue)](https://www.rapidtables.com/web/color/RGB_Color.html), for [Lua](https://github.com/JordanSantiagoYT/FNF-JS-Engine/blob/main/source/FunkinLua.hx#L2021), you'll need an Color picker

could i get a brief rundown on how this works please 
![image](https://github.com/user-attachments/assets/a5a1cccf-3f1b-4d22-9d86-1cf58def14ab)

**Comment by moxie-coder** [comment]
> > > last thing, how do i change the color of the health bar along with it? ik it has something to do with this ![image](https://private-user-images.githubusercontent.com/136278510/398589606-629588c8-5fcf-4b66-a580-fcdd6b69e4c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDYzNjUsIm5iZiI6MTczNTE0NjA2NSwicGF0aCI6Ii8xMzYyNzg1MTAvMzk4NTg5NjA2LTYyOTU4OGM4LTVmY2YtNGI2Ni1hNTgwLWZjZGQ2YjY5ZTRjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxNzAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWExYzAxZjc5NjRlYTIzZTQ2NTEyNTdhNDNmYmM5MDBjOWY5YmFkMzVhYWIxZjNmZDhhNjU1Y2ZmMTMyMTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KU5SLj0SAOE-pq6wa2rEwzPz-LLFe8FKpvnOPBEiAp0) ![image](https://private-user-images.githubusercontent.com/136278510/398589620-341e2528-bee0-4f1a-a8c1-4910fb66b926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDYzNjUsIm5iZiI6MTczNTE0NjA2NSwicGF0aCI6Ii8xMzYyNzg1MTAvMzk4NTg5NjIwLTM0MWUyNTI4LWJlZTAtNGYxYS1hOGMxLTQ5MTBmYjY2YjkyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxNzAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWZiYjgxNGQzYjY0NDk3NTc3Yzk2M2NkZWY2ZWZmNmJkOTMwYzdhYzZiNjIzMDZlYzE3MDNkOGZjYWQ1NGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fKefN6rWpvB8UunP7BEnnefXELuDE1G3mLTlG-IpiIY)
> > 
> > 
> > it works like [RGB (Red Green Blue)](https://www.rapidtables.com/web/color/RGB_Color.html), for [Lua](https://github.com/JordanSantiagoYT/FNF-JS-Engine/blob/main/source/FunkinLua.hx#L2021), you'll need an Color picker
> 
> could i get a brief rundown on how this works please? i have the colors i need i just dont know where to put them ![image](https://private-user-images.githubusercontent.com/136278510/398591310-a5a1cccf-3f1b-4d22-9d86-1cf58def14ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNTc0MzksIm5iZiI6MTczNTE1NzEzOSwicGF0aCI6Ii8xMzYyNzg1MTAvMzk4NTkxMzEwLWE1YTFjY2NmLTNmMWItNGQyMi05ZDg2LTFjZjU4ZGVmMTRhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQyMDA1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWRlNGMwYzViZDFjYTliMWExZDI2ZTk1YzM3ODg0YmIwYmEyNDQzZTY5MDkyOGRlMGUyNDc4NDc4ZjY1MjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9mSwaCyCyjfSuP31I3ceVkS0kPoWhhg43p3qiTE-dAU)

simply just do `setHealthBarColors(33FFFF, FF66FF)` as an example
