### ISSUE TITLE
JS ENGINE WONT RUN. ON IOS!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by yelleko1** [JordanSantiagoYT/FNF-JS-Engine#824]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

i just got a tablet for christmas and i wanted to put js engine on it
so i downloaded the ios port of the engine
i put it on the home screen...........and (Sorry for the sonic watch ahh quality)
![Screenshot 2024-12-25 222238](https://github.com/user-attachments/assets/e6f23f1e-0fe4-49bf-8b5e-52940a28ae79)
it keeps saying its N.ot safe
if you were wondering it says
"This app cannot be installed because its integrity could not be verified."

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

im new to this porting stuff so i may sound a little idiotic

- downloaded the ios port on my ipad
- connected my ipad to my computer
- downloaded itunes
- drag and dropped the ipa file to itunes
- it downloaded and now its on my homescreen!!! yay!!!
- oop its marked as unsafe and now i cant open it in any way

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

iOS

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by TofpFL** [comment]
More info to add: The IOS version of new JS Engine he is trying to install either "isn't from a trusted source" or that "the app file itself is corrupted".

My guess is that the build is corrupted or Apple could just be a huge dick.

**Comment by yelleko1** [comment]
1. it isnt corrupted, i fresh installed it three times
2. maybe

**Comment by JordanSantiagoYT** [comment]
iOS apps that aren't from the app store have a much different installation process, you can't just install it through itunes

**Comment by yelleko1** [comment]
ohhhhhhhhhh

**Comment by JordanSantiagoYT** [comment]
however, i know how to install apps outside the appstore and can give instructions

**Comment by yelleko1** [comment]
it works yay

**Comment by yelleko1** [comment]
Spoke too soon 
the sound does not work and the buttons also do not work
the touchscreen does though so i can get through the startup screen

**Comment by yelleko1** [comment]
nvm the resolution is just buggy i can fix that
