### ISSUE TITLE
Help The screen

### ISSUE THREAD

**Issue by AlonsoxD-hack** [JordanSantiagoYT/FNF-JS-Engine#828]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Hi my js engine iOS the screen is mini

https://github.com/user-attachments/assets/6a933b46-76fe-40bf-9ab9-8abc392eb197

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

iOS

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment]
dupe of this [issue](https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/808)

**Comment by JordanSantiagoYT** [comment]
Duplicate of #808

**Comment by StinkTheStinker** [comment]
> Duplicate of #808

i said that

**Comment by AlonsoxD-hack** [comment]
Is there any solution? ( for install ipa i use feather )
![IMG_0026](https://github.com/user-attachments/assets/f665d098-7983-4fc2-ac46-6f71f8126719)

**Comment by JordanSantiagoYT** [comment]
not sure, maybe changing the resolution in options -> graphics might help

**Comment by AlonsoxD-hack** [comment]
> not sure, maybe changing the resolution in options -> graphics might help

Ok I will try

**Comment by AlonsoxD-hack** [comment]
No Dont work
