### ISSUE TITLE
pressing notes simply lags the game and makes the audio clip

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-JS-Engine#829]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

the title explains itself

### Command Prompt/Terminal/Crash logs (if existing)

a

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

i

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

o

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by daveandbambifan1234** [comment]
it's performance is terrible no matter what's open or not
even the smallest stuff that is open will still lag the audio and lag the game too

**Comment by daveandbambifan1234** [comment]
you know what! forget about it...

**Comment by StinkTheStinker** [comment]
you basically already talked about this in [this discussion](https://github.com/JordanSantiagoYT/FNF-JS-Engine/discussions/539). 

its your computer thats terrible maybe, tell me the specs of the computer

**Comment by SyncGit12** [comment]
This guy is brainrot seriously
